<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5.3 Tabela de ANOVA para o fatorial A×B balanceado | Planejamento e Análise de Experimentos</title>
  <meta name="description" content="Livro-texto de apoio à disciplina MATD48 (Planejamento de Experimentos A), Departamento de Estatística, UFBA." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="5.3 Tabela de ANOVA para o fatorial A×B balanceado | Planejamento e Análise de Experimentos" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Livro-texto de apoio à disciplina MATD48 (Planejamento de Experimentos A), Departamento de Estatística, UFBA." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5.3 Tabela de ANOVA para o fatorial A×B balanceado | Planejamento e Análise de Experimentos" />
  
  <meta name="twitter:description" content="Livro-texto de apoio à disciplina MATD48 (Planejamento de Experimentos A), Departamento de Estatística, UFBA." />
  

<meta name="author" content="Raydonal Ospina Martínez" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="modelo-axb.html"/>
<link rel="next" href="matriz-axb.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./"><strong>Planejamento e Análise de Experimentos</strong></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefácio</a>
<ul>
<li class="chapter" data-level="" data-path="para-quem-é-este-livro.html"><a href="para-quem-é-este-livro.html"><i class="fa fa-check"></i>Para quem é este livro</a></li>
<li class="chapter" data-level="" data-path="como-o-material-está-organizado.html"><a href="como-o-material-está-organizado.html"><i class="fa fa-check"></i>Como o material está organizado</a></li>
<li class="chapter" data-level="" data-path="convenções-tipográficas.html"><a href="convenções-tipográficas.html"><i class="fa fa-check"></i>Convenções tipográficas</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="principios.html"><a href="principios.html"><i class="fa fa-check"></i><b>1</b> Princípios do delineamento de experimentos</a>
<ul>
<li class="chapter" data-level="1.1" data-path="metodo-cientifico.html"><a href="metodo-cientifico.html"><i class="fa fa-check"></i><b>1.1</b> O método científico e o papel do delineamento experimental</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="metodo-cientifico.html"><a href="metodo-cientifico.html#o-ciclo-empírico-de-observação-a-hipótese-testável"><i class="fa fa-check"></i><b>1.1.1</b> O ciclo empírico: de observação a hipótese testável</a></li>
<li class="chapter" data-level="1.1.2" data-path="metodo-cientifico.html"><a href="metodo-cientifico.html#observação-vs.-experimentação-por-que-controlado-importa"><i class="fa fa-check"></i><b>1.1.2</b> Observação vs. experimentação: por que “controlado” importa</a></li>
<li class="chapter" data-level="1.1.3" data-path="metodo-cientifico.html"><a href="metodo-cientifico.html#uma-nota-histórica-quantificar-controlar-e-só-depois-formalizar"><i class="fa fa-check"></i><b>1.1.3</b> Uma nota histórica: quantificar, controlar, e só depois formalizar</a></li>
<li class="chapter" data-level="1.1.4" data-path="metodo-cientifico.html"><a href="metodo-cientifico.html#confusão-confounding-o-problema-que-a-aleatorização-resolve"><i class="fa fa-check"></i><b>1.1.4</b> Confusão (<em>confounding</em>): o problema que a aleatorização resolve</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="unidades.html"><a href="unidades.html"><i class="fa fa-check"></i><b>1.2</b> Unidades experimentais e unidades amostrais</a></li>
<li class="chapter" data-level="1.3" data-path="fontes-variacao.html"><a href="fontes-variacao.html"><i class="fa fa-check"></i><b>1.3</b> Fontes de variação</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="fontes-variacao.html"><a href="fontes-variacao.html#aditividade-aleatorizacao"><i class="fa fa-check"></i><b>1.3.1</b> Por que essa decomposição força a forma aditiva do modelo</a></li>
<li class="chapter" data-level="1.3.2" data-path="fontes-variacao.html"><a href="fontes-variacao.html#fatores-niveis"><i class="fa fa-check"></i><b>1.3.2</b> Fatores e níveis</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="tres-aspectos.html"><a href="tres-aspectos.html"><i class="fa fa-check"></i><b>1.4</b> Os três aspectos do delineamento experimental</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="tres-aspectos.html"><a href="tres-aspectos.html#repetição-replicação"><i class="fa fa-check"></i><b>1.4.1</b> Repetição (replicação)</a></li>
<li class="chapter" data-level="1.4.2" data-path="tres-aspectos.html"><a href="tres-aspectos.html#aleatorização"><i class="fa fa-check"></i><b>1.4.2</b> Aleatorização</a></li>
<li class="chapter" data-level="1.4.3" data-path="tres-aspectos.html"><a href="tres-aspectos.html#neyman-rubin"><i class="fa fa-check"></i><b>1.4.3</b> Por que a aleatorização funciona: o modelo de resultados potenciais</a></li>
<li class="chapter" data-level="1.4.4" data-path="tres-aspectos.html"><a href="tres-aspectos.html#ate-binario"><i class="fa fa-check"></i><b>1.4.4</b> Um terceiro domínio: resultados potenciais binários em um teste A/B</a></li>
<li class="chapter" data-level="1.4.5" data-path="tres-aspectos.html"><a href="tres-aspectos.html#validade-externa"><i class="fa fa-check"></i><b>1.4.5</b> Validade interna e validade externa</a></li>
<li class="chapter" data-level="1.4.6" data-path="tres-aspectos.html"><a href="tres-aspectos.html#amostragem-e-desenho"><i class="fa fa-check"></i><b>1.4.6</b> O elo entre amostragem e planejamento de experimentos</a></li>
<li class="chapter" data-level="1.4.7" data-path="tres-aspectos.html"><a href="tres-aspectos.html#controle-local-blocagem"><i class="fa fa-check"></i><b>1.4.7</b> Controle local (blocagem)</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="resumo-do-capítulo.html"><a href="resumo-do-capítulo.html"><i class="fa fa-check"></i><b>1.5</b> Resumo do capítulo</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="modelos-lineares.html"><a href="modelos-lineares.html"><i class="fa fa-check"></i><b>2</b> Introdução aos modelos lineares</a>
<ul>
<li class="chapter" data-level="2.1" data-path="populacao-conceitual.html"><a href="populacao-conceitual.html"><i class="fa fa-check"></i><b>2.1</b> Da população conceitual de respostas ao modelo linear</a></li>
<li class="chapter" data-level="2.2" data-path="hasse.html"><a href="hasse.html"><i class="fa fa-check"></i><b>2.2</b> Diagramas de Hasse: a estrutura do delineamento antes da álgebra</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="hasse.html"><a href="hasse.html#o-diagrama-como-um-retrato-da-estrutura-do-dado"><i class="fa fa-check"></i><b>2.2.1</b> O diagrama como um retrato da estrutura do dado</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="modelo-geral.html"><a href="modelo-geral.html"><i class="fa fa-check"></i><b>2.3</b> O modelo linear geral</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="modelo-geral.html"><a href="modelo-geral.html#porque-xbeta-mais-erro"><i class="fa fa-check"></i><b>2.3.1</b> Por que esta é a forma natural, não arbitrária, do modelo</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="minimos-quadrados.html"><a href="minimos-quadrados.html"><i class="fa fa-check"></i><b>2.4</b> Estimação por mínimos quadrados</a></li>
<li class="chapter" data-level="2.5" data-path="estimabilidade.html"><a href="estimabilidade.html"><i class="fa fa-check"></i><b>2.5</b> Estimabilidade de funções lineares dos parâmetros</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="estimabilidade.html"><a href="estimabilidade.html#svd-moore-penrose"><i class="fa fa-check"></i><b>2.5.1</b> A pseudoinversa de Moore-Penrose via decomposição em valores singulares</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="gauss-markov.html"><a href="gauss-markov.html"><i class="fa fa-check"></i><b>2.6</b> O teorema de Gauss-Markov e o BLUE</a></li>
<li class="chapter" data-level="2.7" data-path="matriz-projecao.html"><a href="matriz-projecao.html"><i class="fa fa-check"></i><b>2.7</b> A matriz de projeção</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="matriz-projecao.html"><a href="matriz-projecao.html#soma-quadrados-total"><i class="fa fa-check"></i><b>2.7.1</b> A soma de quadrados total como forma quadrática</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="modelo-particionado.html"><a href="modelo-particionado.html"><i class="fa fa-check"></i><b>2.8</b> O modelo linear particionado</a></li>
<li class="chapter" data-level="2.9" data-path="fwl.html"><a href="fwl.html"><i class="fa fa-check"></i><b>2.9</b> O teorema de Frisch-Waugh-Lovell</a>
<ul>
<li class="chapter" data-level="2.9.1" data-path="fwl.html"><a href="fwl.html#fwl-experimentos"><i class="fa fa-check"></i><b>2.9.1</b> Conexão com planejamento de experimentos: por que a ANCOVA funciona</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="formas-quadraticas.html"><a href="formas-quadraticas.html"><i class="fa fa-check"></i><b>2.10</b> Distribuição de formas lineares e quadráticas</a></li>
<li class="chapter" data-level="2.11" data-path="resumo-do-capítulo-1.html"><a href="resumo-do-capítulo-1.html"><i class="fa fa-check"></i><b>2.11</b> Resumo do capítulo</a>
<ul>
<li class="chapter" data-level="" data-path="resumo-do-capítulo-1.html"><a href="resumo-do-capítulo-1.html#uma-nota-sobre-notação-de-beta-genérico-a-tau-e-depois-a-alphabetagammadots"><i class="fa fa-check"></i>Uma nota sobre notação: de <span class="math inline">\(\beta\)</span> genérico a <span class="math inline">\(\tau\)</span>, e depois a <span class="math inline">\(\alpha,\beta,\gamma,\dots\)</span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="dca.html"><a href="dca.html"><i class="fa fa-check"></i><b>3</b> Delineamento completamente aleatorizado</a>
<ul>
<li class="chapter" data-level="3.1" data-path="principios-aleatorizacao.html"><a href="principios-aleatorizacao.html"><i class="fa fa-check"></i><b>3.1</b> Princípios de aleatorização: a ideia de um teste de aleatorização</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="principios-aleatorizacao.html"><a href="principios-aleatorizacao.html#randomizacao-df-f"><i class="fa fa-check"></i><b>3.1.1</b> De onde vêm os graus de liberdade <span class="math inline">\((2,33)\)</span>: a ponte entre aleatorização, variância decomposta e <span class="math inline">\(F\)</span></a></li>
<li class="chapter" data-level="3.1.2" data-path="principios-aleatorizacao.html"><a href="principios-aleatorizacao.html#modelo-deduzido"><i class="fa fa-check"></i><b>3.1.2</b> O modelo linear deduzido da aleatorização</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="dca-uma-via.html"><a href="dca-uma-via.html"><i class="fa fa-check"></i><b>3.2</b> O delineamento completamente aleatorizado a uma via de classificação</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="dca-uma-via.html"><a href="dca-uma-via.html#modelo-dca"><i class="fa fa-check"></i><b>3.2.1</b> O modelo estatístico</a></li>
<li class="chapter" data-level="3.2.2" data-path="dca-uma-via.html"><a href="dca-uma-via.html#matricial-dca"><i class="fa fa-check"></i><b>3.2.2</b> Notação matricial: o DCA como caso particular do modelo linear geral</a></li>
<li class="chapter" data-level="3.2.3" data-path="dca-uma-via.html"><a href="dca-uma-via.html#potencial-causal"><i class="fa fa-check"></i><b>3.2.3</b> Resultados potenciais e o estimando causal</a></li>
<li class="chapter" data-level="3.2.4" data-path="dca-uma-via.html"><a href="dca-uma-via.html#ic-dca"><i class="fa fa-check"></i><b>3.2.4</b> Estimação e intervalos de confiança</a></li>
<li class="chapter" data-level="3.2.5" data-path="dca-uma-via.html"><a href="dca-uma-via.html#anova-dca"><i class="fa fa-check"></i><b>3.2.5</b> A tabela de análise de variância</a></li>
<li class="chapter" data-level="3.2.6" data-path="dca-uma-via.html"><a href="dca-uma-via.html#numero-replicas-dca"><i class="fa fa-check"></i><b>3.2.6</b> Número de réplicas necessário</a></li>
<li class="chapter" data-level="3.2.7" data-path="dca-uma-via.html"><a href="dca-uma-via.html#dca-feijao"><i class="fa fa-check"></i><b>3.2.7</b> Um segundo exemplo, com dado real: fertilizante em feijão</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="dca-submuestreo.html"><a href="dca-submuestreo.html"><i class="fa fa-check"></i><b>3.3</b> Submuestreo em um DCA</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="dca-submuestreo.html"><a href="dca-submuestreo.html#modelo-submuestreo"><i class="fa fa-check"></i><b>3.3.1</b> O modelo com dois níveis de erro</a></li>
<li class="chapter" data-level="3.3.2" data-path="dca-submuestreo.html"><a href="dca-submuestreo.html#o-diagrama-de-hasse-do-submuestreo-aninhamento-em-duas-camadas"><i class="fa fa-check"></i><b>3.3.2</b> O diagrama de Hasse do submuestreo: aninhamento em duas camadas</a></li>
<li class="chapter" data-level="3.3.3" data-path="dca-submuestreo.html"><a href="dca-submuestreo.html#anova-submuestreo"><i class="fa fa-check"></i><b>3.3.3</b> ANOVA com submuestreo</a></li>
<li class="chapter" data-level="3.3.4" data-path="dca-submuestreo.html"><a href="dca-submuestreo.html#amostra-submuestreo"><i class="fa fa-check"></i><b>3.3.4</b> Tamanho de amostra com submuestreo</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="dca-efeitos-aleatorios.html"><a href="dca-efeitos-aleatorios.html"><i class="fa fa-check"></i><b>3.4</b> O modelo de efeitos aleatórios</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="dca-efeitos-aleatorios.html"><a href="dca-efeitos-aleatorios.html#modelo-aleatorio"><i class="fa fa-check"></i><b>3.4.1</b> Quando os tratamentos são uma amostra aleatória</a></li>
<li class="chapter" data-level="3.4.2" data-path="dca-efeitos-aleatorios.html"><a href="dca-efeitos-aleatorios.html#anova-aleatorio"><i class="fa fa-check"></i><b>3.4.2</b> ANOVA e componentes de variância</a></li>
<li class="chapter" data-level="3.4.3" data-path="dca-efeitos-aleatorios.html"><a href="dca-efeitos-aleatorios.html#amostra-aleatorio"><i class="fa fa-check"></i><b>3.4.3</b> Tamanho de amostra no modelo de efeitos aleatórios</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="dca-pressupostos.html"><a href="dca-pressupostos.html"><i class="fa fa-check"></i><b>3.5</b> Verificação de pressupostos</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="dca-pressupostos.html"><a href="dca-pressupostos.html#normalidade-dca"><i class="fa fa-check"></i><b>3.5.1</b> Normalidade: gráfico Q-Q e testes formais</a></li>
<li class="chapter" data-level="3.5.2" data-path="dca-pressupostos.html"><a href="dca-pressupostos.html#homocedasticidade-dca"><i class="fa fa-check"></i><b>3.5.2</b> Homogeneidade de variância</a></li>
<li class="chapter" data-level="3.5.3" data-path="dca-pressupostos.html"><a href="dca-pressupostos.html#transformacoes-dca"><i class="fa fa-check"></i><b>3.5.3</b> Transformações usuais</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="contrastes.html"><a href="contrastes.html"><i class="fa fa-check"></i><b>3.6</b> Contrastes e comparações múltiplas</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="contrastes.html"><a href="contrastes.html#definição-esperança-e-variância-de-um-contraste"><i class="fa fa-check"></i><b>3.6.1</b> Definição, esperança e variância de um contraste</a></li>
<li class="chapter" data-level="3.6.2" data-path="contrastes.html"><a href="contrastes.html#soma-de-quadrados-de-um-contraste-e-sua-distribuição"><i class="fa fa-check"></i><b>3.6.2</b> Soma de quadrados de um contraste e sua distribuição</a></li>
<li class="chapter" data-level="3.6.3" data-path="contrastes.html"><a href="contrastes.html#notação-matricial-contraste-como-forma-linear-e-quadrática"><i class="fa fa-check"></i><b>3.6.3</b> Notação matricial: contraste como forma linear e quadrática</a></li>
<li class="chapter" data-level="3.6.4" data-path="contrastes.html"><a href="contrastes.html#contrastes-ortogonais"><i class="fa fa-check"></i><b>3.6.4</b> Contrastes ortogonais</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html"><i class="fa fa-check"></i><b>3.7</b> Procedimentos de comparação múltipla</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#data-snooping"><i class="fa fa-check"></i><b>3.7.1</b> O perigo do “data snooping”</a></li>
<li class="chapter" data-level="3.7.2" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#método-de-scheffé"><i class="fa fa-check"></i><b>3.7.2</b> Método de Scheffé</a></li>
<li class="chapter" data-level="3.7.3" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#método-de-bonferroni"><i class="fa fa-check"></i><b>3.7.3</b> Método de Bonferroni</a></li>
<li class="chapter" data-level="3.7.4" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#tukey-hsd-honestly-significant-difference"><i class="fa fa-check"></i><b>3.7.4</b> Tukey HSD (<em>honestly significant difference</em>)</a></li>
<li class="chapter" data-level="3.7.5" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#comparação-com-um-grupo-controle-dunnett"><i class="fa fa-check"></i><b>3.7.5</b> Comparação com um grupo controle: Dunnett</a></li>
<li class="chapter" data-level="3.7.6" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#teste-de-amplitude-múltipla-de-duncan"><i class="fa fa-check"></i><b>3.7.6</b> Teste de amplitude múltipla de Duncan</a></li>
<li class="chapter" data-level="3.7.7" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#agrupamento-de-tratamentos-compact-letter-display"><i class="fa fa-check"></i><b>3.7.7</b> Agrupamento de tratamentos (<em>compact letter display</em>)</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="polinomios-ortogonais.html"><a href="polinomios-ortogonais.html"><i class="fa fa-check"></i><b>3.8</b> Polinômios ortogonais</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="polinomios-ortogonais.html"><a href="polinomios-ortogonais.html#esperança-variância-e-soma-de-quadrados"><i class="fa fa-check"></i><b>3.8.1</b> Esperança, variância e soma de quadrados</a></li>
<li class="chapter" data-level="3.8.2" data-path="polinomios-ortogonais.html"><a href="polinomios-ortogonais.html#a-matriz-de-polinômios-ortogonais-como-parte-de-mathbf-x"><i class="fa fa-check"></i><b>3.8.2</b> A matriz de polinômios ortogonais como parte de <span class="math inline">\(\mathbf X\)</span></a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="ancova.html"><a href="ancova.html"><i class="fa fa-check"></i><b>3.9</b> Análise de covariância (ANCOVA)</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="ancova.html"><a href="ancova.html#o-modelo"><i class="fa fa-check"></i><b>3.9.1</b> O modelo</a></li>
<li class="chapter" data-level="3.9.2" data-path="ancova.html"><a href="ancova.html#ancova-em-notação-matricial-mais-uma-coluna-em-mathbf-x"><i class="fa fa-check"></i><b>3.9.2</b> ANCOVA em notação matricial: mais uma coluna em <span class="math inline">\(\mathbf X\)</span></a></li>
<li class="chapter" data-level="3.9.3" data-path="ancova.html"><a href="ancova.html#a-tabela-de-anova-ajustada-pela-covariável"><i class="fa fa-check"></i><b>3.9.3</b> A tabela de ANOVA ajustada pela covariável</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="kruskal-wallis.html"><a href="kruskal-wallis.html"><i class="fa fa-check"></i><b>3.10</b> Teste de Kruskal-Wallis</a>
<ul>
<li class="chapter" data-level="3.10.1" data-path="kruskal-wallis.html"><a href="kruskal-wallis.html#o-que-muda-em-relação-à-anova"><i class="fa fa-check"></i><b>3.10.1</b> O que muda em relação à ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="resumo-do-capítulo-2.html"><a href="resumo-do-capítulo-2.html"><i class="fa fa-check"></i><b>3.11</b> Resumo do capítulo</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="blocos.html"><a href="blocos.html"><i class="fa fa-check"></i><b>4</b> Delineamentos com fontes de bloqueio</a>
<ul>
<li class="chapter" data-level="4.1" data-path="dbca.html"><a href="dbca.html"><i class="fa fa-check"></i><b>4.1</b> O delineamento em blocos completos aleatorizados (DBCA)</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="dbca.html"><a href="dbca.html#motivação-o-que-dá-errado-sem-controle-local-fatores-confundidos"><i class="fa fa-check"></i><b>4.1.1</b> Motivação: o que dá errado sem controle local — fatores confundidos</a></li>
<li class="chapter" data-level="4.1.2" data-path="dbca.html"><a href="dbca.html#o-modelo-1"><i class="fa fa-check"></i><b>4.1.2</b> O modelo</a></li>
<li class="chapter" data-level="4.1.3" data-path="dbca.html"><a href="dbca.html#notação-matricial-yxbetavarepsilon"><i class="fa fa-check"></i><b>4.1.3</b> Notação matricial: <span class="math inline">\(Y=X\beta+\varepsilon\)</span></a></li>
<li class="chapter" data-level="4.1.4" data-path="dbca.html"><a href="dbca.html#blocagem-como-aleatorização-restrita-a-camada-causal"><i class="fa fa-check"></i><b>4.1.4</b> Blocagem como aleatorização restrita: a camada causal</a></li>
<li class="chapter" data-level="4.1.5" data-path="dbca.html"><a href="dbca.html#tabela-de-anova"><i class="fa fa-check"></i><b>4.1.5</b> Tabela de ANOVA</a></li>
<li class="chapter" data-level="4.1.6" data-path="dbca.html"><a href="dbca.html#esperança-dos-quadrados-médios"><i class="fa fa-check"></i><b>4.1.6</b> Esperança dos quadrados médios</a></li>
<li class="chapter" data-level="4.1.7" data-path="dbca.html"><a href="dbca.html#visualizando-aditividade-o-gráfico-de-perfis"><i class="fa fa-check"></i><b>4.1.7</b> Visualizando aditividade: o gráfico de perfis</a></li>
<li class="chapter" data-level="4.1.8" data-path="dbca.html"><a href="dbca.html#tukey-nao-aditividade"><i class="fa fa-check"></i><b>4.1.8</b> O teste de não aditividade de Tukey</a></li>
<li class="chapter" data-level="4.1.9" data-path="dbca.html"><a href="dbca.html#diagrama-de-hasse-do-dbca-por-que-não-há-nó-de-interação"><i class="fa fa-check"></i><b>4.1.9</b> Diagrama de Hasse do DBCA: por que não há nó de interação</a></li>
<li class="chapter" data-level="4.1.10" data-path="dbca.html"><a href="dbca.html#dados-faltantes-estimação-do-valor-perdido"><i class="fa fa-check"></i><b>4.1.10</b> Dados faltantes: estimação do valor perdido</a></li>
<li class="chapter" data-level="4.1.11" data-path="dbca.html"><a href="dbca.html#eficiência-relativa-do-dbca-frente-ao-dca"><i class="fa fa-check"></i><b>4.1.11</b> Eficiência relativa do DBCA frente ao DCA</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="friedman.html"><a href="friedman.html"><i class="fa fa-check"></i><b>4.2</b> Teste de Friedman</a></li>
<li class="chapter" data-level="4.3" data-path="bib.html"><a href="bib.html"><i class="fa fa-check"></i><b>4.3</b> Blocos incompletos balanceados</a></li>
<li class="chapter" data-level="4.4" data-path="quadrado-latino.html"><a href="quadrado-latino.html"><i class="fa fa-check"></i><b>4.4</b> Delineamento em quadrado latino</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="quadrado-latino.html"><a href="quadrado-latino.html#motivação-dois-gradientes-ortogonais-e-por-que-um-bloqueio-simples-não-basta"><i class="fa fa-check"></i><b>4.4.1</b> Motivação: dois gradientes ortogonais, e por que um bloqueio simples não basta</a></li>
<li class="chapter" data-level="4.4.2" data-path="quadrado-latino.html"><a href="quadrado-latino.html#o-modelo-2"><i class="fa fa-check"></i><b>4.4.2</b> O modelo</a></li>
<li class="chapter" data-level="4.4.3" data-path="quadrado-latino.html"><a href="quadrado-latino.html#diagrama-de-hasse-do-quadrado-latino-três-fatores-cruzados-dois-a-dois"><i class="fa fa-check"></i><b>4.4.3</b> Diagrama de Hasse do quadrado latino: três fatores cruzados dois a dois</a></li>
<li class="chapter" data-level="4.4.4" data-path="quadrado-latino.html"><a href="quadrado-latino.html#aleatorização-de-um-quadrado-latino-yates1933latin"><i class="fa fa-check"></i><b>4.4.4</b> Aleatorização de um quadrado latino <span class="citation">(Yates, 1933)</span></a></li>
<li class="chapter" data-level="4.4.5" data-path="quadrado-latino.html"><a href="quadrado-latino.html#quadrados-latinos-replicados"><i class="fa fa-check"></i><b>4.4.5</b> Quadrados latinos replicados</a></li>
<li class="chapter" data-level="4.4.6" data-path="quadrado-latino.html"><a href="quadrado-latino.html#quantas-réplicas-uma-análise-de-poder"><i class="fa fa-check"></i><b>4.4.6</b> Quantas réplicas? Uma análise de poder</a></li>
<li class="chapter" data-level="4.4.7" data-path="quadrado-latino.html"><a href="quadrado-latino.html#eficiencia-ql"><i class="fa fa-check"></i><b>4.4.7</b> Eficiência relativa do quadrado latino frente ao DBCA e ao DCA</a></li>
<li class="chapter" data-level="4.4.8" data-path="quadrado-latino.html"><a href="quadrado-latino.html#ql-exemplo-ecommerce"><i class="fa fa-check"></i><b>4.4.8</b> Um segundo exemplo completo: cinco variantes de checkout em e-commerce</a></li>
<li class="chapter" data-level="4.4.9" data-path="quadrado-latino.html"><a href="quadrado-latino.html#youden"><i class="fa fa-check"></i><b>4.4.9</b> Quadrados de Youden: quando o quadrado latino não pode ser completo</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="quadrado-greco-latino.html"><a href="quadrado-greco-latino.html"><i class="fa fa-check"></i><b>4.5</b> Delineamento em quadrado greco-latino</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="quadrado-greco-latino.html"><a href="quadrado-greco-latino.html#mols"><i class="fa fa-check"></i><b>4.5.1</b> Quadrados latinos mutuamente ortogonais (MOLS): existência e o problema de Euler</a></li>
<li class="chapter" data-level="4.5.2" data-path="quadrado-greco-latino.html"><a href="quadrado-greco-latino.html#o-modelo-3"><i class="fa fa-check"></i><b>4.5.2</b> O modelo</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="split-plot.html"><a href="split-plot.html"><i class="fa fa-check"></i><b>4.6</b> Parcelas subdivididas (<em>split-plot</em>)</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="split-plot.html"><a href="split-plot.html#dois-erros-experimentais-não-um"><i class="fa fa-check"></i><b>4.6.1</b> Dois erros experimentais, não um</a></li>
<li class="chapter" data-level="4.6.2" data-path="split-plot.html"><a href="split-plot.html#por-que-o-teste-de-irrigação-usa-um-erro-diferente-do-teste-de-variedade"><i class="fa fa-check"></i><b>4.6.2</b> Por que o teste de irrigação usa um erro diferente do teste de variedade</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="resumo-do-capítulo-3.html"><a href="resumo-do-capítulo-3.html"><i class="fa fa-check"></i><b>4.7</b> Resumo do capítulo</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="fatoriais.html"><a href="fatoriais.html"><i class="fa fa-check"></i><b>5</b> Delineamentos com arranjos fatoriais</a>
<ul>
<li class="chapter" data-level="5.1" data-path="por-que-fatorial.html"><a href="por-que-fatorial.html"><i class="fa fa-check"></i><b>5.1</b> Por que cruzar fatores?</a></li>
<li class="chapter" data-level="5.2" data-path="modelo-axb.html"><a href="modelo-axb.html"><i class="fa fa-check"></i><b>5.2</b> O fatorial A×B: efeitos principais e interação</a></li>
<li class="chapter" data-level="5.3" data-path="anova-axb.html"><a href="anova-axb.html"><i class="fa fa-check"></i><b>5.3</b> Tabela de ANOVA para o fatorial A×B balanceado</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="anova-axb.html"><a href="anova-axb.html#tipos-sq"><i class="fa fa-check"></i><b>5.3.1</b> Quando as células não têm o mesmo tamanho: somas de quadrados Tipo I, II e III</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="matriz-axb.html"><a href="matriz-axb.html"><i class="fa fa-check"></i><b>5.4</b> Notação matricial do fatorial A×B</a></li>
<li class="chapter" data-level="5.5" data-path="axbxc.html"><a href="axbxc.html"><i class="fa fa-check"></i><b>5.5</b> Fatoriais A×B×C: interações duplas e tripla</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="axbxc.html"><a href="axbxc.html#cubo-2x2x2"><i class="fa fa-check"></i><b>5.5.1</b> O cubo do <span class="math inline">\(2^3\)</span>: visualizando efeitos principais, duplos e triplo</a></li>
<li class="chapter" data-level="5.5.2" data-path="axbxc.html"><a href="axbxc.html#hasse-axbxc"><i class="fa fa-check"></i><b>5.5.2</b> O diagrama de Hasse do fatorial 3×3×3</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="fatoriais-blocos.html"><a href="fatoriais-blocos.html"><i class="fa fa-check"></i><b>5.6</b> Fatoriais de dois fatores em blocos completos</a></li>
<li class="chapter" data-level="5.7" data-path="resumo-do-capítulo-4.html"><a href="resumo-do-capítulo-4.html"><i class="fa fa-check"></i><b>5.7</b> Resumo do capítulo</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="fatoriais-avancado.html"><a href="fatoriais-avancado.html"><i class="fa fa-check"></i><b>6</b> Fatoriais avançados: confusão, fracionamento e superfície de resposta</a>
<ul>
<li class="chapter" data-level="6.1" data-path="fatoriais-2k.html"><a href="fatoriais-2k.html"><i class="fa fa-check"></i><b>6.1</b> Fatoriais <span class="math inline">\(2^k\)</span>: notação e ANOVA</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="fatoriais-2k.html"><a href="fatoriais-2k.html#ortogonalidade-2k"><i class="fa fa-check"></i><b>6.1.1</b> Ortogonalidade da matriz de desenho</a></li>
<li class="chapter" data-level="6.1.2" data-path="fatoriais-2k.html"><a href="fatoriais-2k.html#algoritmo-yates"><i class="fa fa-check"></i><b>6.1.2</b> O algoritmo tabular de Yates</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="nao-replicado.html"><a href="nao-replicado.html"><i class="fa fa-check"></i><b>6.2</b> Análise de um fatorial <span class="math inline">\(2^k\)</span> não replicado</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="nao-replicado.html"><a href="nao-replicado.html#gráfico-de-probabilidade-normal-half-normal-plot"><i class="fa fa-check"></i><b>6.2.1</b> Gráfico de probabilidade normal (half-normal plot)</a></li>
<li class="chapter" data-level="6.2.2" data-path="nao-replicado.html"><a href="nao-replicado.html#gráfico-de-pareto-dos-efeitos"><i class="fa fa-check"></i><b>6.2.2</b> Gráfico de Pareto dos efeitos</a></li>
<li class="chapter" data-level="6.2.3" data-path="nao-replicado.html"><a href="nao-replicado.html#margem-de-erro-pelo-método-de-lenth"><i class="fa fa-check"></i><b>6.2.3</b> Margem de erro pelo método de Lenth</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="confusao-2k.html"><a href="confusao-2k.html"><i class="fa fa-check"></i><b>6.3</b> Confusão em <span class="math inline">\(2^k\)</span>: designação de tratamentos a blocos</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="confusao-2k.html"><a href="confusao-2k.html#esquema-de-designação-o-contraste-definidor"><i class="fa fa-check"></i><b>6.3.1</b> Esquema de designação: o contraste definidor</a></li>
<li class="chapter" data-level="6.3.2" data-path="confusao-2k.html"><a href="confusao-2k.html#confusao-projecao"><i class="fa fa-check"></i><b>6.3.2</b> Confusão como colinearidade em <span class="math inline">\(\mathbf{X}\)</span></a></li>
<li class="chapter" data-level="6.3.3" data-path="confusao-2k.html"><a href="confusao-2k.html#confusão-total-vs.-confusão-parcial"><i class="fa fa-check"></i><b>6.3.3</b> Confusão total vs. confusão parcial</a></li>
<li class="chapter" data-level="6.3.4" data-path="confusao-2k.html"><a href="confusao-2k.html#hasse-confusao"><i class="fa fa-check"></i><b>6.3.4</b> Visualizando a confusão com um diagrama de Hasse</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="fatoriais-3k.html"><a href="fatoriais-3k.html"><i class="fa fa-check"></i><b>6.4</b> Fatoriais <span class="math inline">\(3^k\)</span>: ideia geral e confusão com <span class="math inline">\(AB^2\)</span></a></li>
<li class="chapter" data-level="6.5" data-path="fracionados.html"><a href="fracionados.html"><i class="fa fa-check"></i><b>6.5</b> Fatoriais fracionados de dois níveis: a ideia geral</a></li>
<li class="chapter" data-level="6.6" data-path="rumo-superficie-resposta.html"><a href="rumo-superficie-resposta.html"><i class="fa fa-check"></i><b>6.6</b> Rumo à otimização: superfície de resposta</a></li>
<li class="chapter" data-level="6.7" data-path="resumo-do-capítulo-5.html"><a href="resumo-do-capítulo-5.html"><i class="fa fa-check"></i><b>6.7</b> Resumo do capítulo</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="superficie-resposta-cap.html"><a href="superficie-resposta-cap.html"><i class="fa fa-check"></i><b>7</b> Metodologia de superfície de resposta</a>
<ul>
<li class="chapter" data-level="7.1" data-path="superficie-resposta.html"><a href="superficie-resposta.html"><i class="fa fa-check"></i><b>7.1</b> Introdução à superfície de resposta</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="superficie-resposta.html"><a href="superficie-resposta.html#ponto-estacionario"><i class="fa fa-check"></i><b>7.1.1</b> Classificando o ponto estacionário: gradiente e Hessiana</a></li>
<li class="chapter" data-level="7.1.2" data-path="superficie-resposta.html"><a href="superficie-resposta.html#analise-canonica"><i class="fa fa-check"></i><b>7.1.2</b> Análise canônica: além de classificar, descrever a forma da superfície</a></li>
<li class="chapter" data-level="7.1.3" data-path="superficie-resposta.html"><a href="superficie-resposta.html#ridge-analysis"><i class="fa fa-check"></i><b>7.1.3</b> Análise de ridge: otimizando dentro de um raio fixo da região experimental</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="steepest-ascent.html"><a href="steepest-ascent.html"><i class="fa fa-check"></i><b>7.2</b> O caminho de máxima inclinação: de um fatorial inicial até a região do ótimo</a></li>
<li class="chapter" data-level="7.3" data-path="ccd.html"><a href="ccd.html"><i class="fa fa-check"></i><b>7.3</b> Delineamento composto central (CCD)</a></li>
<li class="chapter" data-level="7.4" data-path="desejabilidade.html"><a href="desejabilidade.html"><i class="fa fa-check"></i><b>7.4</b> Otimização de múltiplas respostas: funções de desejabilidade</a></li>
<li class="chapter" data-level="7.5" data-path="desenho-robusto.html"><a href="desenho-robusto.html"><i class="fa fa-check"></i><b>7.5</b> Desenho robusto: otimizando a média e a variância ao mesmo tempo</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="desenho-robusto.html"><a href="desenho-robusto.html#a-proposta-original-de-taguchi-e-por-que-ela-foi-revista"><i class="fa fa-check"></i><b>7.5.1</b> A proposta original de Taguchi, e por que ela foi revista</a></li>
<li class="chapter" data-level="7.5.2" data-path="desenho-robusto.html"><a href="desenho-robusto.html#a-alternativa-duas-superfícies-de-resposta-uma-única-maquinaria"><i class="fa fa-check"></i><b>7.5.2</b> A alternativa: duas superfícies de resposta, uma única maquinaria</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="resumo-do-capítulo-6.html"><a href="resumo-do-capítulo-6.html"><i class="fa fa-check"></i><b>7.6</b> Resumo do capítulo</a></li>
<li class="chapter" data-level="7.7" data-path="fim-do-programa-do-semestre.html"><a href="fim-do-programa-do-semestre.html"><i class="fa fa-check"></i><b>7.7</b> Fim do programa do semestre</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ab-bandits.html"><a href="ab-bandits.html"><i class="fa fa-check"></i><b>8</b> Experimentação em produtos digitais: testes A/B e bandits</a>
<ul>
<li class="chapter" data-level="8.1" data-path="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><i class="fa fa-check"></i><b>8.1</b> Parte I — Testes A/B como delineamento completamente aleatorizado</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#ab-e-dca"><i class="fa fa-check"></i><b>8.1.1</b> Um teste A/B é um delineamento completamente aleatorizado</a></li>
<li class="chapter" data-level="8.1.2" data-path="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#ab-dificuldades"><i class="fa fa-check"></i><b>8.1.2</b> Por que testes A/B em produtos digitais são estatisticamente difíceis</a></li>
<li class="chapter" data-level="8.1.3" data-path="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#ab-peeking"><i class="fa fa-check"></i><b>8.1.3</b> O problema do “peeking”</a></li>
<li class="chapter" data-level="8.1.4" data-path="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#ab-winners-curse"><i class="fa fa-check"></i><b>8.1.4</b> Vício do vencedor (<em>winner’s curse</em>)</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><i class="fa fa-check"></i><b>8.2</b> Parte II — Bandits: quando explorar e quando explotar</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html#bandits-motivacao"><i class="fa fa-check"></i><b>8.2.1</b> Exploração, explotação e a definição de arrependimento (<em>regret</em>)</a></li>
<li class="chapter" data-level="8.2.2" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html#bandits-ucb1"><i class="fa fa-check"></i><b>8.2.2</b> Upper Confidence Bound (UCB1): otimismo perante a incerteza</a></li>
<li class="chapter" data-level="8.2.3" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html#bandits-thompson"><i class="fa fa-check"></i><b>8.2.3</b> Thompson sampling: uma solução bayesiana</a></li>
<li class="chapter" data-level="8.2.4" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html#bandits-vs-ab"><i class="fa fa-check"></i><b>8.2.4</b> Horizonte fixo ou bandit?</a></li>
<li class="chapter" data-level="8.2.5" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html#outros-topicos"><i class="fa fa-check"></i><b>8.2.5</b> Outros tópicos modernos</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="resumo-do-capítulo-7.html"><a href="resumo-do-capítulo-7.html"><i class="fa fa-check"></i><b>8.3</b> Resumo do capítulo</a></li>
<li class="chapter" data-level="8.4" data-path="encerrando-o-livro.html"><a href="encerrando-o-livro.html"><i class="fa fa-check"></i><b>8.4</b> Encerrando o livro</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://raydonal.github.io/matd48/" target="_blank">MATD48 — Página do curso</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Planejamento e Análise de Experimentos</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="anova-axb" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Tabela de ANOVA para o fatorial A×B balanceado<a href="anova-axb.html#anova-axb" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A soma de quadrados total se decompõe exatamente em quatro parcelas ortogonais:</p>
<p><span class="math display">\[SQ_{Total} = SQ_A + SQ_B + SQ_{AB} + SQ_E,\]</span></p>
<p>com</p>
<p><span class="math display">\[
SQ_A = rb\sum_i (\bar{y}_{i..} - \bar{y}_{...})^2, \quad
SQ_B = ra\sum_j (\bar{y}_{.j.} - \bar{y}_{...})^2,
\]</span>
<span class="math display">\[
SQ_{AB} = r\sum_{i,j} (\bar{y}_{ij.} - \bar{y}_{i..} - \bar{y}_{.j.} + \bar{y}_{...})^2, \quad
SQ_E = \sum_{i,j,k} (y_{ijk} - \bar{y}_{ij.})^2.
\]</span></p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:tabela-anova-axb">Tabela 5.1: </span>ANOVA do fatorial A×B balanceado
</caption>
<thead>
<tr>
<th style="text-align:left;">
Fonte de variação
</th>
<th style="text-align:left;">
Graus de liberdade
</th>
<th style="text-align:left;">
Soma de quadrados
</th>
<th style="text-align:left;">
Quadrado médio
</th>
<th style="text-align:left;">
F
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Fator A
</td>
<td style="text-align:left;">
<span class="math inline">\(a-1\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(SQ_A\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(QM_A = SQ_A/(a-1)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(QM_A/QM_E\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Fator B
</td>
<td style="text-align:left;">
<span class="math inline">\(b-1\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(SQ_B\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(QM_B = SQ_B/(b-1)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(QM_B/QM_E\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Interação A×B
</td>
<td style="text-align:left;">
<span class="math inline">\((a-1)(b-1)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(SQ_{AB}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(QM_{AB} = SQ_{AB}/[(a-1)(b-1)]\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(QM_{AB}/QM_E\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Erro
</td>
<td style="text-align:left;">
<span class="math inline">\(ab(r-1)\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(SQ_E\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(QM_E = SQ_E/[ab(r-1)]\)</span>
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Total
</td>
<td style="text-align:left;">
<span class="math inline">\(abr-1\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(SQ_{Total}\)</span>
</td>
<td style="text-align:left;">
</td>
<td style="text-align:left;">
</td>
</tr>
</tbody>
</table>
<p><strong>Por que o teste <span class="math inline">\(F\)</span> funciona: valor esperado dos quadrados médios.</strong> O Capítulo 2 (Seção
<a href="formas-quadraticas.html#formas-quadraticas">2.10</a>) mostrou que uma forma quadrática <span class="math inline">\(\mathbf{Y}&#39;\mathbf{A}\mathbf{Y}\)</span>, com
<span class="math inline">\(\mathbf{A}\)</span> idempotente de posto <span class="math inline">\(r\)</span>, é <span class="math inline">\(\sigma^2\)</span> vezes uma qui-quadrado com <span class="math inline">\(r\)</span> graus de
liberdade e parâmetro de não centralidade <span class="math inline">\(\boldsymbol{\mu}&#39;\mathbf{A}\boldsymbol{\mu}/\sigma^2\)</span>.
Cada uma das quatro somas de quadrados acima (<span class="math inline">\(SQ_A, SQ_B, SQ_{AB}, SQ_E\)</span>) é exatamente uma forma
quadrática desse tipo — a soma de quadrados de <span class="math inline">\(A\)</span>, por exemplo, usa a matriz idempotente que
projeta sobre a direção dos efeitos de <span class="math inline">\(A\)</span> dentro do espaço-coluna de <span class="math inline">\(\mathbf{X}\)</span> (Seção
<a href="matriz-axb.html#matriz-axb">5.4</a>). Isso permite calcular o valor esperado de cada quadrado médio sem depender de
nenhuma simulação:</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:tabela-eqm-axb">Tabela 5.2: </span>Esperança dos quadrados médios do fatorial A×B (efeitos fixos)
</caption>
<thead>
<tr>
<th style="text-align:left;">
Quadrado médio
</th>
<th style="text-align:left;">
Valor esperado
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
<span class="math inline">\(QM_A\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\sigma^2 + \dfrac{rb\sum_i \alpha_i^2}{a-1}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(QM_B\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\sigma^2 + \dfrac{ra\sum_j \beta_j^2}{b-1}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(QM_{AB}\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\sigma^2 + \dfrac{r\sum_{i,j} (\alpha\beta)_{ij}^2}{(a-1)(b-1)}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
<span class="math inline">\(QM_E\)</span>
</td>
<td style="text-align:left;">
<span class="math inline">\(\sigma^2\)</span>
</td>
</tr>
</tbody>
</table>
<p>Cada linha tem a mesma estrutura: <span class="math inline">\(\sigma^2\)</span> (o que <span class="math inline">\(QM_E\)</span> estima sozinho) mais um termo
não negativo que só se anula quando o efeito correspondente é identicamente zero. É exatamente
essa estrutura que justifica usar <span class="math inline">\(QM_E\)</span> como denominador comum dos três testes <span class="math inline">\(F\)</span>: sob
<span class="math inline">\(H_0: \alpha_i = 0\ \forall i\)</span>, por exemplo, <span class="math inline">\(E[QM_A] = E[QM_E] = \sigma^2\)</span> e a razão <span class="math inline">\(QM_A/QM_E\)</span>
segue uma <span class="math inline">\(F\)</span> central; sob a alternativa, o numerador de <span class="math inline">\(E[QM_A]\)</span> cresce com a soma dos quadrados
dos <span class="math inline">\(\alpha_i\)</span>, deslocando a distribuição de <span class="math inline">\(F\)</span> para a direita (não centralidade) e aumentando a
chance de rejeitar <span class="math inline">\(H_0\)</span> — a mesma lógica de poder já usada no Capítulo 3 (Seção
<a href="dca-uma-via.html#numero-replicas-dca">3.2.6</a>), agora com três parâmetros de não centralidade em jogo simultaneamente
em vez de um só.</p>
<p>Note que, diferentemente de um DCA de um único fator, o fatorial A×B testa <strong>três hipóteses</strong>
com um único conjunto de dados: <span class="math inline">\(H_0: \alpha_i = 0\ \forall i\)</span> (nenhum efeito de <span class="math inline">\(A\)</span>),
<span class="math inline">\(H_0: \beta_j = 0\ \forall j\)</span> (nenhum efeito de <span class="math inline">\(B\)</span>) e <span class="math inline">\(H_0: (\alpha\beta)_{ij} = 0\ \forall i,j\)</span>
(nenhuma interação) — todas usando o mesmo <span class="math inline">\(QM_E\)</span> como denominador, o que é exatamente a
eficiência estatística mencionada na Seção <a href="por-que-fatorial.html#por-que-fatorial">5.1</a>. Na prática, a convenção é
examinar primeiro a interação: se ela for relevante, interpretar os efeitos principais isolados
pode ser enganoso, e a análise deve reportar as médias de célula (combinação <span class="math inline">\(i,j\)</span>) diretamente.</p>
<div id="tipos-sq" class="section level3 hasAnchor" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> Quando as células não têm o mesmo tamanho: somas de quadrados Tipo I, II e III<a href="anova-axb.html#tipos-sq" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A decomposição exata <span class="math inline">\(SQ_{Total} = SQ_A+SQ_B+SQ_{AB}+SQ_E\)</span> da seção anterior depende de uma
suposição que ficou implícita: <strong>o mesmo número <span class="math inline">\(r\)</span> de réplicas em toda casela</strong> <span class="math inline">\((i,j)\)</span>. Sob
balanceamento, as colunas de <span class="math inline">\(\mathbf{X}\)</span> associadas a <span class="math inline">\(A\)</span>, a <span class="math inline">\(B\)</span> e à interação são ortogonais
entre si (a mesma ideia da Seção <a href="matriz-axb.html#matriz-axb">5.4</a> do fatorial <span class="math inline">\(2^k\)</span>, agora para um A×B geral) —
<span class="math inline">\(SQ_A\)</span> mede exatamente a mesma coisa, seja <span class="math inline">\(A\)</span> ajustado sozinho ou na presença de <span class="math inline">\(B\)</span>. Quando as
caselas têm tamanhos diferentes — a norma, não a exceção, em dados que não vêm de um experimento
de campo cuidadosamente balanceado (tráfego real de um teste A/B, perda de observações,
inscrição voluntária) —, essa ortogonalidade se perde: as colunas de <span class="math inline">\(A\)</span> e de <span class="math inline">\(B\)</span> passam a ser
correlacionadas, e “o quanto <span class="math inline">\(A\)</span> explica” passa a depender de <strong>o que mais já está no modelo</strong>
<span class="citation">(<a href="#ref-speedhockinghackney1978">Speed et al., 1978</a>)</span>. Três convenções resolvem essa ambiguidade de formas diferentes:</p>
<ul>
<li><strong>Tipo I (sequencial):</strong> cada termo é testado ajustado só pelos termos que entraram <strong>antes</strong>
dele no modelo, na ordem em que foram escritos. <span class="math inline">\(SQ_A\)</span> ignora <span class="math inline">\(B\)</span>; <span class="math inline">\(SQ_B\)</span> já ajusta para <span class="math inline">\(A\)</span>;
<span class="math inline">\(SQ_{AB}\)</span> ajusta para ambos. Consequência direta: <strong>a ordem em que os fatores são escritos na
fórmula muda o resultado</strong> — <code>aov(y ~ A*B)</code> e <code>aov(y ~ B*A)</code> dão <span class="math inline">\(SQ_A\)</span> e <span class="math inline">\(SQ_B\)</span> diferentes
(a soma dos quatro termos continua igual a <span class="math inline">\(SQ_{Total}\)</span> em qualquer ordem, só a divisão entre
<span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span> muda). É o padrão de <code>aov()</code>/<code>anova()</code> no R.</li>
<li><strong>Tipo II:</strong> cada efeito principal é ajustado pelo <strong>outro</strong> efeito principal, mas não pela
interação — simétrico em <span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span> (não depende de ordem), sob a suposição de que a interação
é desprezível o bastante para não “roubar” variação dos efeitos principais.</li>
<li><strong>Tipo III (marginal):</strong> cada termo é ajustado por <strong>todos</strong> os outros, incluindo a interação —
a mais conservadora e a única que testa exatamente as mesmas hipóteses
<span class="math inline">\(H_0: \alpha_i=0\ \forall i\)</span> etc. do caso balanceado, mesmo com interação presente. Exige
<strong>contrastes de soma zero</strong> (<code>options(contrasts = c("contr.sum", "contr.poly"))</code> no R) — com a
parametrização padrão do R (<code>contr.treatment</code>), o teste Tipo III do “efeito principal” testa uma
combinação que depende de qual nível é a referência, não o que o pesquisador normalmente quer
dizer por “efeito de <span class="math inline">\(A\)</span>”.</li>
</ul>
<div class="caixa-aplicacao">
<strong>Aplicação — Ciência de dados: teste A/B/n com tráfego desigual</strong><br>
Uma loja testa <strong>layout</strong> (Lista/Grade) × <strong>desconto exibido</strong>
(Sim/Não) sobre o tempo de permanência na página (s). Diferente de um experimento de campo, o
tráfego real não se divide em partes iguais entre as quatro combinações — a tabela abaixo mostra
tamanhos de casela desiguais (30 a 70 sessões), a situação típica de um teste A/B em produção.
</div>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="anova-axb.html#cb220-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb220-2"><a href="anova-axb.html#cb220-2" tabindex="-1"></a>n_celula <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">Lista_Nao =</span> <span class="dv">40</span>, <span class="at">Lista_Sim =</span> <span class="dv">55</span>, <span class="at">Grade_Nao =</span> <span class="dv">30</span>, <span class="at">Grade_Sim =</span> <span class="dv">70</span>)</span>
<span id="cb220-3"><a href="anova-axb.html#cb220-3" tabindex="-1"></a>media_celula <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">Lista_Nao =</span> <span class="dv">42</span>, <span class="at">Lista_Sim =</span> <span class="dv">47</span>, <span class="at">Grade_Nao =</span> <span class="dv">44</span>, <span class="at">Grade_Sim =</span> <span class="dv">53</span>)</span>
<span id="cb220-4"><a href="anova-axb.html#cb220-4" tabindex="-1"></a></span>
<span id="cb220-5"><a href="anova-axb.html#cb220-5" tabindex="-1"></a>dados_desbal <span class="ot">&lt;-</span> <span class="fu">map2_dfr</span>(n_celula, media_celula, <span class="sc">~</span> <span class="fu">tibble</span>(<span class="at">tempo =</span> <span class="fu">rnorm</span>(.x, .y, <span class="dv">8</span>)),</span>
<span id="cb220-6"><a href="anova-axb.html#cb220-6" tabindex="-1"></a>                         <span class="at">.id =</span> <span class="st">&quot;celula&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb220-7"><a href="anova-axb.html#cb220-7" tabindex="-1"></a>  <span class="fu">separate</span>(celula, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">&quot;layout&quot;</span>, <span class="st">&quot;desconto&quot;</span>), <span class="at">sep =</span> <span class="st">&quot;_&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb220-8"><a href="anova-axb.html#cb220-8" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">layout =</span> <span class="fu">factor</span>(layout, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Grade&quot;</span>, <span class="st">&quot;Lista&quot;</span>)),</span>
<span id="cb220-9"><a href="anova-axb.html#cb220-9" tabindex="-1"></a>         <span class="at">desconto =</span> <span class="fu">factor</span>(desconto, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Nao&quot;</span>, <span class="st">&quot;Sim&quot;</span>)))</span>
<span id="cb220-10"><a href="anova-axb.html#cb220-10" tabindex="-1"></a></span>
<span id="cb220-11"><a href="anova-axb.html#cb220-11" tabindex="-1"></a><span class="fu">table</span>(dados_desbal<span class="sc">$</span>layout, dados_desbal<span class="sc">$</span>desconto)</span></code></pre></div>
<pre><code>##        
##         Nao Sim
##   Grade  30  70
##   Lista  40  55</code></pre>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="anova-axb.html#cb222-1" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(tempo <span class="sc">~</span> layout <span class="sc">*</span> desconto, <span class="at">data =</span> dados_desbal))   <span class="co"># layout primeiro</span></span></code></pre></div>
<pre><code>##                  Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## layout            1   2332  2332.0  37.974 4.16e-09 ***
## desconto          1   2511  2510.8  40.886 1.21e-09 ***
## layout:desconto   1    451   450.9   7.342  0.00735 ** 
## Residuals       191  11729    61.4                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="anova-axb.html#cb224-1" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">aov</span>(tempo <span class="sc">~</span> desconto <span class="sc">*</span> layout, <span class="at">data =</span> dados_desbal))   <span class="co"># desconto primeiro</span></span></code></pre></div>
<pre><code>##                  Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## desconto          1   3114  3113.5  50.700 2.13e-11 ***
## layout            1   1729  1729.3  28.159 3.08e-07 ***
## desconto:layout   1    451   450.9   7.342  0.00735 ** 
## Residuals       191  11729    61.4                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p><span class="math inline">\(SQ_{\text{layout}}\)</span> e <span class="math inline">\(SQ_{\text{desconto}}\)</span> mudam de fato conforme a ordem — exatamente o
sintoma da falta de ortogonalidade. Nos dois casos, <span class="math inline">\(SQ_{AB}\)</span> (a interação) é idêntico, porque a
interação é sempre o último termo a entrar, ajustado por tudo o resto em qualquer ordem.</p>
<div class="caixa-r"><strong>Uso do R</strong> — Tipo II e Tipo III com <code>car::Anova()</code></div>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="anova-axb.html#cb226-1" tabindex="-1"></a>contrastes_originais <span class="ot">&lt;-</span> <span class="fu">options</span>(<span class="st">&quot;contrasts&quot;</span>)           <span class="co"># preserva o default do capitulo</span></span>
<span id="cb226-2"><a href="anova-axb.html#cb226-2" tabindex="-1"></a><span class="fu">options</span>(<span class="at">contrasts =</span> <span class="fu">c</span>(<span class="st">&quot;contr.sum&quot;</span>, <span class="st">&quot;contr.poly&quot;</span>))      <span class="co"># exigido para Tipo III fazer sentido</span></span>
<span id="cb226-3"><a href="anova-axb.html#cb226-3" tabindex="-1"></a>modelo_desbal <span class="ot">&lt;-</span> <span class="fu">lm</span>(tempo <span class="sc">~</span> layout <span class="sc">*</span> desconto, <span class="at">data =</span> dados_desbal)</span>
<span id="cb226-4"><a href="anova-axb.html#cb226-4" tabindex="-1"></a></span>
<span id="cb226-5"><a href="anova-axb.html#cb226-5" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">Anova</span>(modelo_desbal, <span class="at">type =</span> <span class="st">&quot;II&quot;</span>)</span></code></pre></div>
<pre><code>## Anova Table (Type II tests)
## 
## Response: tempo
##                  Sum Sq  Df F value    Pr(&gt;F)    
## layout           1729.3   1 28.1595 3.079e-07 ***
## desconto         2510.8   1 40.8856 1.210e-09 ***
## layout:desconto   450.9   1  7.3418   0.00735 ** 
## Residuals       11729.4 191                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="anova-axb.html#cb228-1" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">Anova</span>(modelo_desbal, <span class="at">type =</span> <span class="st">&quot;III&quot;</span>)</span></code></pre></div>
<pre><code>## Anova Table (Type III tests)
## 
## Response: tempo
##                 Sum Sq  Df   F value    Pr(&gt;F)    
## (Intercept)     380434   1 6194.9229 &lt; 2.2e-16 ***
## layout            1143   1   18.6178 2.560e-05 ***
## desconto          2610   1   42.4968 6.153e-10 ***
## layout:desconto    451   1    7.3418   0.00735 ** 
## Residuals        11729 191                        
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="anova-axb.html#cb230-1" tabindex="-1"></a><span class="fu">options</span>(contrastes_originais)   <span class="co"># restaura imediatamente -- nao deve vazar para as secoes seguintes</span></span></code></pre></div>
<p>O Tipo II dá exatamente <span class="math inline">\(SQ_{\text{layout}}=\)</span> 1729.3
(o mesmo valor de quando <code>layout</code> entra <strong>depois</strong> de <code>desconto</code> no Tipo I) e
<span class="math inline">\(SQ_{\text{desconto}}=\)</span> 2510.8
— cada um ajustado pelo outro, nenhum pela interação, e por isso independente da ordem de escrita.
O Tipo III muda de novo (ajusta também pela interação), e é o único dos três cuja soma de
quadrados de <code>layout</code>/<code>desconto</code> não bate com nenhuma das duas linhas de Tipo I acima.</p>
<p>Recomendação prática, seguindo a literatura sobre o tema <span class="citation">(<a href="#ref-langsrud2003">Langsrud, 2003</a>)</span>: olhar a interação
primeiro; se ela for desprezível, o Tipo II é preferível ao III (mais poder, mesma interpretação
de “efeito principal médio”); se a interação for relevante, nenhum teste de efeito principal —
de nenhum tipo — costuma responder a pergunta certa, e a análise deve reportar as médias de
célula diretamente (a mesma recomendação da seção anterior, agora reforçada pelo caso
desbalanceado). Delineamentos de campo bem balanceados evitam esse problema por construção — mais
uma razão prática para preferir balanceamento sempre que o custo do experimento permitir.</p>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" line-spacing="2">
<div id="ref-langsrud2003" class="csl-entry">
Langsrud, Ø. (2003). <span>ANOVA</span> for unbalanced data: Use type <span>II</span> instead of type <span>III</span> sums of squares. <em>Statistics and Computing</em>, <em>13</em>(2), 163–167.
</div>
<div id="ref-speedhockinghackney1978" class="csl-entry">
Speed, F. M., Hocking, R. R., &amp; Hackney, O. P. (1978). Methods of analysis of linear models with unbalanced data. <em>Journal of the American Statistical Association</em>, <em>73</em>(361), 105–112.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="modelo-axb.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="matriz-axb.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": false,
    "twitter": false,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
