<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>8.1 Parte I — Testes A/B como delineamento completamente aleatorizado | Planejamento e Análise de Experimentos</title>
  <meta name="description" content="Livro-texto de apoio à disciplina MATD48 (Planejamento de Experimentos A), Departamento de Estatística, UFBA." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="8.1 Parte I — Testes A/B como delineamento completamente aleatorizado | Planejamento e Análise de Experimentos" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Livro-texto de apoio à disciplina MATD48 (Planejamento de Experimentos A), Departamento de Estatística, UFBA." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="8.1 Parte I — Testes A/B como delineamento completamente aleatorizado | Planejamento e Análise de Experimentos" />
  
  <meta name="twitter:description" content="Livro-texto de apoio à disciplina MATD48 (Planejamento de Experimentos A), Departamento de Estatística, UFBA." />
  

<meta name="author" content="Raydonal Ospina Martínez" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="ab-bandits.html"/>
<link rel="next" href="parte-ii-bandits-quando-explorar-e-quando-explotar.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./"><strong>Planejamento e Análise de Experimentos</strong></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefácio</a>
<ul>
<li class="chapter" data-level="" data-path="para-quem-é-este-livro.html"><a href="para-quem-é-este-livro.html"><i class="fa fa-check"></i>Para quem é este livro</a></li>
<li class="chapter" data-level="" data-path="como-o-material-está-organizado.html"><a href="como-o-material-está-organizado.html"><i class="fa fa-check"></i>Como o material está organizado</a></li>
<li class="chapter" data-level="" data-path="convenções-tipográficas.html"><a href="convenções-tipográficas.html"><i class="fa fa-check"></i>Convenções tipográficas</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="principios.html"><a href="principios.html"><i class="fa fa-check"></i><b>1</b> Princípios do delineamento de experimentos</a>
<ul>
<li class="chapter" data-level="1.1" data-path="metodo-cientifico.html"><a href="metodo-cientifico.html"><i class="fa fa-check"></i><b>1.1</b> O método científico e o papel do delineamento experimental</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="metodo-cientifico.html"><a href="metodo-cientifico.html#o-ciclo-empírico-de-observação-a-hipótese-testável"><i class="fa fa-check"></i><b>1.1.1</b> O ciclo empírico: de observação a hipótese testável</a></li>
<li class="chapter" data-level="1.1.2" data-path="metodo-cientifico.html"><a href="metodo-cientifico.html#observação-vs.-experimentação-por-que-controlado-importa"><i class="fa fa-check"></i><b>1.1.2</b> Observação vs. experimentação: por que “controlado” importa</a></li>
<li class="chapter" data-level="1.1.3" data-path="metodo-cientifico.html"><a href="metodo-cientifico.html#uma-nota-histórica-fisher-rothamsted-e-a-origem-do-delineamento-moderno"><i class="fa fa-check"></i><b>1.1.3</b> Uma nota histórica: Fisher, Rothamsted e a origem do delineamento moderno</a></li>
<li class="chapter" data-level="1.1.4" data-path="metodo-cientifico.html"><a href="metodo-cientifico.html#confusão-confounding-o-problema-que-a-aleatorização-resolve"><i class="fa fa-check"></i><b>1.1.4</b> Confusão (<em>confounding</em>): o problema que a aleatorização resolve</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="unidades.html"><a href="unidades.html"><i class="fa fa-check"></i><b>1.2</b> Unidades experimentais e unidades amostrais</a></li>
<li class="chapter" data-level="1.3" data-path="fontes-variacao.html"><a href="fontes-variacao.html"><i class="fa fa-check"></i><b>1.3</b> Fontes de variação</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="fontes-variacao.html"><a href="fontes-variacao.html#aditividade-aleatorizacao"><i class="fa fa-check"></i><b>1.3.1</b> Por que essa decomposição força a forma aditiva do modelo</a></li>
<li class="chapter" data-level="1.3.2" data-path="fontes-variacao.html"><a href="fontes-variacao.html#fatores-niveis"><i class="fa fa-check"></i><b>1.3.2</b> Fatores e níveis</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="tres-aspectos.html"><a href="tres-aspectos.html"><i class="fa fa-check"></i><b>1.4</b> Os três aspectos do delineamento experimental</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="tres-aspectos.html"><a href="tres-aspectos.html#repetição-replicação"><i class="fa fa-check"></i><b>1.4.1</b> Repetição (replicação)</a></li>
<li class="chapter" data-level="1.4.2" data-path="tres-aspectos.html"><a href="tres-aspectos.html#aleatorização"><i class="fa fa-check"></i><b>1.4.2</b> Aleatorização</a></li>
<li class="chapter" data-level="1.4.3" data-path="tres-aspectos.html"><a href="tres-aspectos.html#neyman-rubin"><i class="fa fa-check"></i><b>1.4.3</b> Por que a aleatorização funciona: o modelo de resultados potenciais</a></li>
<li class="chapter" data-level="1.4.4" data-path="tres-aspectos.html"><a href="tres-aspectos.html#validade-externa"><i class="fa fa-check"></i><b>1.4.4</b> Validade interna e validade externa</a></li>
<li class="chapter" data-level="1.4.5" data-path="tres-aspectos.html"><a href="tres-aspectos.html#amostragem-e-desenho"><i class="fa fa-check"></i><b>1.4.5</b> O elo entre amostragem e planejamento de experimentos</a></li>
<li class="chapter" data-level="1.4.6" data-path="tres-aspectos.html"><a href="tres-aspectos.html#controle-local-blocagem"><i class="fa fa-check"></i><b>1.4.6</b> Controle local (blocagem)</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="resumo-do-capítulo.html"><a href="resumo-do-capítulo.html"><i class="fa fa-check"></i><b>1.5</b> Resumo do capítulo</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="modelos-lineares.html"><a href="modelos-lineares.html"><i class="fa fa-check"></i><b>2</b> Introdução aos modelos lineares</a>
<ul>
<li class="chapter" data-level="2.1" data-path="hasse.html"><a href="hasse.html"><i class="fa fa-check"></i><b>2.1</b> Diagramas de Hasse: a estrutura do delineamento antes da álgebra</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="hasse.html"><a href="hasse.html#o-diagrama-como-um-retrato-da-estrutura-do-dado"><i class="fa fa-check"></i><b>2.1.1</b> O diagrama como um retrato da estrutura do dado</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="modelo-geral.html"><a href="modelo-geral.html"><i class="fa fa-check"></i><b>2.2</b> O modelo linear geral</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="modelo-geral.html"><a href="modelo-geral.html#porque-xbeta-mais-erro"><i class="fa fa-check"></i><b>2.2.1</b> Por que esta é a forma natural, não arbitrária, do modelo</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="minimos-quadrados.html"><a href="minimos-quadrados.html"><i class="fa fa-check"></i><b>2.3</b> Estimação por mínimos quadrados</a></li>
<li class="chapter" data-level="2.4" data-path="estimabilidade.html"><a href="estimabilidade.html"><i class="fa fa-check"></i><b>2.4</b> Estimabilidade de funções lineares dos parâmetros</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="estimabilidade.html"><a href="estimabilidade.html#svd-moore-penrose"><i class="fa fa-check"></i><b>2.4.1</b> A pseudoinversa de Moore-Penrose via decomposição em valores singulares</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="gauss-markov.html"><a href="gauss-markov.html"><i class="fa fa-check"></i><b>2.5</b> O teorema de Gauss-Markov e o BLUE</a></li>
<li class="chapter" data-level="2.6" data-path="matriz-projecao.html"><a href="matriz-projecao.html"><i class="fa fa-check"></i><b>2.6</b> A matriz de projeção</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="matriz-projecao.html"><a href="matriz-projecao.html#soma-quadrados-total"><i class="fa fa-check"></i><b>2.6.1</b> A soma de quadrados total como forma quadrática</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="modelo-particionado.html"><a href="modelo-particionado.html"><i class="fa fa-check"></i><b>2.7</b> O modelo linear particionado</a></li>
<li class="chapter" data-level="2.8" data-path="fwl.html"><a href="fwl.html"><i class="fa fa-check"></i><b>2.8</b> O teorema de Frisch-Waugh-Lovell</a>
<ul>
<li class="chapter" data-level="2.8.1" data-path="fwl.html"><a href="fwl.html#fwl-experimentos"><i class="fa fa-check"></i><b>2.8.1</b> Conexão com planejamento de experimentos: por que a ANCOVA funciona</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="formas-quadraticas.html"><a href="formas-quadraticas.html"><i class="fa fa-check"></i><b>2.9</b> Distribuição de formas lineares e quadráticas</a></li>
<li class="chapter" data-level="2.10" data-path="resumo-do-capítulo-1.html"><a href="resumo-do-capítulo-1.html"><i class="fa fa-check"></i><b>2.10</b> Resumo do capítulo</a>
<ul>
<li class="chapter" data-level="" data-path="resumo-do-capítulo-1.html"><a href="resumo-do-capítulo-1.html#uma-nota-sobre-notação-de-beta-genérico-a-tau-e-depois-a-alphabetagammadots"><i class="fa fa-check"></i>Uma nota sobre notação: de <span class="math inline">\(\beta\)</span> genérico a <span class="math inline">\(\tau\)</span>, e depois a <span class="math inline">\(\alpha,\beta,\gamma,\dots\)</span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="dca.html"><a href="dca.html"><i class="fa fa-check"></i><b>3</b> Delineamento completamente aleatorizado</a>
<ul>
<li class="chapter" data-level="3.1" data-path="principios-aleatorizacao.html"><a href="principios-aleatorizacao.html"><i class="fa fa-check"></i><b>3.1</b> Princípios de aleatorização: a ideia de um teste de aleatorização</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="principios-aleatorizacao.html"><a href="principios-aleatorizacao.html#randomizacao-df-f"><i class="fa fa-check"></i><b>3.1.1</b> De onde vêm os graus de liberdade <span class="math inline">\((2,33)\)</span>: a ponte entre aleatorização, variância decomposta e <span class="math inline">\(F\)</span></a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="dca-uma-via.html"><a href="dca-uma-via.html"><i class="fa fa-check"></i><b>3.2</b> O delineamento completamente aleatorizado a uma via de classificação</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="dca-uma-via.html"><a href="dca-uma-via.html#modelo-dca"><i class="fa fa-check"></i><b>3.2.1</b> O modelo estatístico</a></li>
<li class="chapter" data-level="3.2.2" data-path="dca-uma-via.html"><a href="dca-uma-via.html#matricial-dca"><i class="fa fa-check"></i><b>3.2.2</b> Notação matricial: o DCA como caso particular do modelo linear geral</a></li>
<li class="chapter" data-level="3.2.3" data-path="dca-uma-via.html"><a href="dca-uma-via.html#potencial-causal"><i class="fa fa-check"></i><b>3.2.3</b> Resultados potenciais e o estimando causal</a></li>
<li class="chapter" data-level="3.2.4" data-path="dca-uma-via.html"><a href="dca-uma-via.html#ic-dca"><i class="fa fa-check"></i><b>3.2.4</b> Estimação e intervalos de confiança</a></li>
<li class="chapter" data-level="3.2.5" data-path="dca-uma-via.html"><a href="dca-uma-via.html#anova-dca"><i class="fa fa-check"></i><b>3.2.5</b> A tabela de análise de variância</a></li>
<li class="chapter" data-level="3.2.6" data-path="dca-uma-via.html"><a href="dca-uma-via.html#numero-replicas-dca"><i class="fa fa-check"></i><b>3.2.6</b> Número de réplicas necessário</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="dca-submuestreo.html"><a href="dca-submuestreo.html"><i class="fa fa-check"></i><b>3.3</b> Submuestreo em um DCA</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="dca-submuestreo.html"><a href="dca-submuestreo.html#modelo-submuestreo"><i class="fa fa-check"></i><b>3.3.1</b> O modelo com dois níveis de erro</a></li>
<li class="chapter" data-level="3.3.2" data-path="dca-submuestreo.html"><a href="dca-submuestreo.html#o-diagrama-de-hasse-do-submuestreo-aninhamento-em-duas-camadas"><i class="fa fa-check"></i><b>3.3.2</b> O diagrama de Hasse do submuestreo: aninhamento em duas camadas</a></li>
<li class="chapter" data-level="3.3.3" data-path="dca-submuestreo.html"><a href="dca-submuestreo.html#anova-submuestreo"><i class="fa fa-check"></i><b>3.3.3</b> ANOVA com submuestreo</a></li>
<li class="chapter" data-level="3.3.4" data-path="dca-submuestreo.html"><a href="dca-submuestreo.html#amostra-submuestreo"><i class="fa fa-check"></i><b>3.3.4</b> Tamanho de amostra com submuestreo</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="dca-efeitos-aleatorios.html"><a href="dca-efeitos-aleatorios.html"><i class="fa fa-check"></i><b>3.4</b> O modelo de efeitos aleatórios</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="dca-efeitos-aleatorios.html"><a href="dca-efeitos-aleatorios.html#modelo-aleatorio"><i class="fa fa-check"></i><b>3.4.1</b> Quando os tratamentos são uma amostra aleatória</a></li>
<li class="chapter" data-level="3.4.2" data-path="dca-efeitos-aleatorios.html"><a href="dca-efeitos-aleatorios.html#anova-aleatorio"><i class="fa fa-check"></i><b>3.4.2</b> ANOVA e componentes de variância</a></li>
<li class="chapter" data-level="3.4.3" data-path="dca-efeitos-aleatorios.html"><a href="dca-efeitos-aleatorios.html#amostra-aleatorio"><i class="fa fa-check"></i><b>3.4.3</b> Tamanho de amostra no modelo de efeitos aleatórios</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="dca-pressupostos.html"><a href="dca-pressupostos.html"><i class="fa fa-check"></i><b>3.5</b> Verificação de pressupostos</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="dca-pressupostos.html"><a href="dca-pressupostos.html#normalidade-dca"><i class="fa fa-check"></i><b>3.5.1</b> Normalidade: gráfico Q-Q e testes formais</a></li>
<li class="chapter" data-level="3.5.2" data-path="dca-pressupostos.html"><a href="dca-pressupostos.html#homocedasticidade-dca"><i class="fa fa-check"></i><b>3.5.2</b> Homogeneidade de variância</a></li>
<li class="chapter" data-level="3.5.3" data-path="dca-pressupostos.html"><a href="dca-pressupostos.html#transformacoes-dca"><i class="fa fa-check"></i><b>3.5.3</b> Transformações usuais</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="contrastes.html"><a href="contrastes.html"><i class="fa fa-check"></i><b>3.6</b> Contrastes e comparações múltiplas</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="contrastes.html"><a href="contrastes.html#definição-esperança-e-variância-de-um-contraste"><i class="fa fa-check"></i><b>3.6.1</b> Definição, esperança e variância de um contraste</a></li>
<li class="chapter" data-level="3.6.2" data-path="contrastes.html"><a href="contrastes.html#soma-de-quadrados-de-um-contraste-e-sua-distribuição"><i class="fa fa-check"></i><b>3.6.2</b> Soma de quadrados de um contraste e sua distribuição</a></li>
<li class="chapter" data-level="3.6.3" data-path="contrastes.html"><a href="contrastes.html#notação-matricial-contraste-como-forma-linear-e-quadrática"><i class="fa fa-check"></i><b>3.6.3</b> Notação matricial: contraste como forma linear e quadrática</a></li>
<li class="chapter" data-level="3.6.4" data-path="contrastes.html"><a href="contrastes.html#contrastes-ortogonais"><i class="fa fa-check"></i><b>3.6.4</b> Contrastes ortogonais</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html"><i class="fa fa-check"></i><b>3.7</b> Procedimentos de comparação múltipla</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#data-snooping"><i class="fa fa-check"></i><b>3.7.1</b> O perigo do “data snooping”</a></li>
<li class="chapter" data-level="3.7.2" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#método-de-scheffé"><i class="fa fa-check"></i><b>3.7.2</b> Método de Scheffé</a></li>
<li class="chapter" data-level="3.7.3" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#método-de-bonferroni"><i class="fa fa-check"></i><b>3.7.3</b> Método de Bonferroni</a></li>
<li class="chapter" data-level="3.7.4" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#tukey-hsd-honestly-significant-difference"><i class="fa fa-check"></i><b>3.7.4</b> Tukey HSD (<em>honestly significant difference</em>)</a></li>
<li class="chapter" data-level="3.7.5" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#comparação-com-um-grupo-controle-dunnett"><i class="fa fa-check"></i><b>3.7.5</b> Comparação com um grupo controle: Dunnett</a></li>
<li class="chapter" data-level="3.7.6" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#teste-de-amplitude-múltipla-de-duncan"><i class="fa fa-check"></i><b>3.7.6</b> Teste de amplitude múltipla de Duncan</a></li>
<li class="chapter" data-level="3.7.7" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#agrupamento-de-tratamentos-compact-letter-display"><i class="fa fa-check"></i><b>3.7.7</b> Agrupamento de tratamentos (<em>compact letter display</em>)</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="polinomios-ortogonais.html"><a href="polinomios-ortogonais.html"><i class="fa fa-check"></i><b>3.8</b> Polinômios ortogonais</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="polinomios-ortogonais.html"><a href="polinomios-ortogonais.html#esperança-variância-e-soma-de-quadrados"><i class="fa fa-check"></i><b>3.8.1</b> Esperança, variância e soma de quadrados</a></li>
<li class="chapter" data-level="3.8.2" data-path="polinomios-ortogonais.html"><a href="polinomios-ortogonais.html#a-matriz-de-polinômios-ortogonais-como-parte-de-mathbf-x"><i class="fa fa-check"></i><b>3.8.2</b> A matriz de polinômios ortogonais como parte de <span class="math inline">\(\mathbf X\)</span></a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="ancova.html"><a href="ancova.html"><i class="fa fa-check"></i><b>3.9</b> Análise de covariância (ANCOVA)</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="ancova.html"><a href="ancova.html#o-modelo"><i class="fa fa-check"></i><b>3.9.1</b> O modelo</a></li>
<li class="chapter" data-level="3.9.2" data-path="ancova.html"><a href="ancova.html#ancova-em-notação-matricial-mais-uma-coluna-em-mathbf-x"><i class="fa fa-check"></i><b>3.9.2</b> ANCOVA em notação matricial: mais uma coluna em <span class="math inline">\(\mathbf X\)</span></a></li>
<li class="chapter" data-level="3.9.3" data-path="ancova.html"><a href="ancova.html#a-tabela-de-anova-ajustada-pela-covariável"><i class="fa fa-check"></i><b>3.9.3</b> A tabela de ANOVA ajustada pela covariável</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="kruskal-wallis.html"><a href="kruskal-wallis.html"><i class="fa fa-check"></i><b>3.10</b> Teste de Kruskal-Wallis</a>
<ul>
<li class="chapter" data-level="3.10.1" data-path="kruskal-wallis.html"><a href="kruskal-wallis.html#o-que-muda-em-relação-à-anova"><i class="fa fa-check"></i><b>3.10.1</b> O que muda em relação à ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="resumo-do-capítulo-2.html"><a href="resumo-do-capítulo-2.html"><i class="fa fa-check"></i><b>3.11</b> Resumo do capítulo</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="blocos.html"><a href="blocos.html"><i class="fa fa-check"></i><b>4</b> Delineamentos com fontes de bloqueio</a>
<ul>
<li class="chapter" data-level="4.1" data-path="dbca.html"><a href="dbca.html"><i class="fa fa-check"></i><b>4.1</b> O delineamento em blocos completos aleatorizados (DBCA)</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="dbca.html"><a href="dbca.html#motivação-o-que-dá-errado-sem-controle-local-fatores-confundidos"><i class="fa fa-check"></i><b>4.1.1</b> Motivação: o que dá errado sem controle local — fatores confundidos</a></li>
<li class="chapter" data-level="4.1.2" data-path="dbca.html"><a href="dbca.html#o-modelo-1"><i class="fa fa-check"></i><b>4.1.2</b> O modelo</a></li>
<li class="chapter" data-level="4.1.3" data-path="dbca.html"><a href="dbca.html#notação-matricial-yxbetavarepsilon"><i class="fa fa-check"></i><b>4.1.3</b> Notação matricial: <span class="math inline">\(Y=X\beta+\varepsilon\)</span></a></li>
<li class="chapter" data-level="4.1.4" data-path="dbca.html"><a href="dbca.html#blocagem-como-aleatorização-restrita-a-camada-causal"><i class="fa fa-check"></i><b>4.1.4</b> Blocagem como aleatorização restrita: a camada causal</a></li>
<li class="chapter" data-level="4.1.5" data-path="dbca.html"><a href="dbca.html#tabela-de-anova"><i class="fa fa-check"></i><b>4.1.5</b> Tabela de ANOVA</a></li>
<li class="chapter" data-level="4.1.6" data-path="dbca.html"><a href="dbca.html#esperança-dos-quadrados-médios"><i class="fa fa-check"></i><b>4.1.6</b> Esperança dos quadrados médios</a></li>
<li class="chapter" data-level="4.1.7" data-path="dbca.html"><a href="dbca.html#visualizando-aditividade-o-gráfico-de-perfis"><i class="fa fa-check"></i><b>4.1.7</b> Visualizando aditividade: o gráfico de perfis</a></li>
<li class="chapter" data-level="4.1.8" data-path="dbca.html"><a href="dbca.html#diagrama-de-hasse-do-dbca-por-que-não-há-nó-de-interação"><i class="fa fa-check"></i><b>4.1.8</b> Diagrama de Hasse do DBCA: por que não há nó de interação</a></li>
<li class="chapter" data-level="4.1.9" data-path="dbca.html"><a href="dbca.html#dados-faltantes-estimação-do-valor-perdido"><i class="fa fa-check"></i><b>4.1.9</b> Dados faltantes: estimação do valor perdido</a></li>
<li class="chapter" data-level="4.1.10" data-path="dbca.html"><a href="dbca.html#eficiência-relativa-do-dbca-frente-ao-dca"><i class="fa fa-check"></i><b>4.1.10</b> Eficiência relativa do DBCA frente ao DCA</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="friedman.html"><a href="friedman.html"><i class="fa fa-check"></i><b>4.2</b> Teste de Friedman</a></li>
<li class="chapter" data-level="4.3" data-path="bib.html"><a href="bib.html"><i class="fa fa-check"></i><b>4.3</b> Blocos incompletos balanceados</a></li>
<li class="chapter" data-level="4.4" data-path="quadrado-latino.html"><a href="quadrado-latino.html"><i class="fa fa-check"></i><b>4.4</b> Delineamento em quadrado latino</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="quadrado-latino.html"><a href="quadrado-latino.html#motivação-dois-gradientes-ortogonais-e-por-que-um-bloqueio-simples-não-basta"><i class="fa fa-check"></i><b>4.4.1</b> Motivação: dois gradientes ortogonais, e por que um bloqueio simples não basta</a></li>
<li class="chapter" data-level="4.4.2" data-path="quadrado-latino.html"><a href="quadrado-latino.html#o-modelo-2"><i class="fa fa-check"></i><b>4.4.2</b> O modelo</a></li>
<li class="chapter" data-level="4.4.3" data-path="quadrado-latino.html"><a href="quadrado-latino.html#diagrama-de-hasse-do-quadrado-latino-três-fatores-cruzados-dois-a-dois"><i class="fa fa-check"></i><b>4.4.3</b> Diagrama de Hasse do quadrado latino: três fatores cruzados dois a dois</a></li>
<li class="chapter" data-level="4.4.4" data-path="quadrado-latino.html"><a href="quadrado-latino.html#aleatorização-de-um-quadrado-latino-yates1933latin"><i class="fa fa-check"></i><b>4.4.4</b> Aleatorização de um quadrado latino <span class="citation">(Yates, 1933)</span></a></li>
<li class="chapter" data-level="4.4.5" data-path="quadrado-latino.html"><a href="quadrado-latino.html#quadrados-latinos-replicados"><i class="fa fa-check"></i><b>4.4.5</b> Quadrados latinos replicados</a></li>
<li class="chapter" data-level="4.4.6" data-path="quadrado-latino.html"><a href="quadrado-latino.html#quantas-réplicas-uma-análise-de-poder"><i class="fa fa-check"></i><b>4.4.6</b> Quantas réplicas? Uma análise de poder</a></li>
<li class="chapter" data-level="4.4.7" data-path="quadrado-latino.html"><a href="quadrado-latino.html#eficiencia-ql"><i class="fa fa-check"></i><b>4.4.7</b> Eficiência relativa do quadrado latino frente ao DBCA e ao DCA</a></li>
<li class="chapter" data-level="4.4.8" data-path="quadrado-latino.html"><a href="quadrado-latino.html#ql-exemplo-ecommerce"><i class="fa fa-check"></i><b>4.4.8</b> Um segundo exemplo completo: cinco variantes de checkout em e-commerce</a></li>
<li class="chapter" data-level="4.4.9" data-path="quadrado-latino.html"><a href="quadrado-latino.html#youden"><i class="fa fa-check"></i><b>4.4.9</b> Quadrados de Youden: quando o quadrado latino não pode ser completo</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="quadrado-greco-latino.html"><a href="quadrado-greco-latino.html"><i class="fa fa-check"></i><b>4.5</b> Delineamento em quadrado greco-latino</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="quadrado-greco-latino.html"><a href="quadrado-greco-latino.html#mols"><i class="fa fa-check"></i><b>4.5.1</b> Quadrados latinos mutuamente ortogonais (MOLS): existência e o problema de Euler</a></li>
<li class="chapter" data-level="4.5.2" data-path="quadrado-greco-latino.html"><a href="quadrado-greco-latino.html#o-modelo-3"><i class="fa fa-check"></i><b>4.5.2</b> O modelo</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="resumo-do-capítulo-3.html"><a href="resumo-do-capítulo-3.html"><i class="fa fa-check"></i><b>4.6</b> Resumo do capítulo</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="fatoriais.html"><a href="fatoriais.html"><i class="fa fa-check"></i><b>5</b> Delineamentos com arranjos fatoriais</a>
<ul>
<li class="chapter" data-level="5.1" data-path="por-que-fatorial.html"><a href="por-que-fatorial.html"><i class="fa fa-check"></i><b>5.1</b> Por que cruzar fatores?</a></li>
<li class="chapter" data-level="5.2" data-path="modelo-axb.html"><a href="modelo-axb.html"><i class="fa fa-check"></i><b>5.2</b> O fatorial A×B: efeitos principais e interação</a></li>
<li class="chapter" data-level="5.3" data-path="anova-axb.html"><a href="anova-axb.html"><i class="fa fa-check"></i><b>5.3</b> Tabela de ANOVA para o fatorial A×B balanceado</a></li>
<li class="chapter" data-level="5.4" data-path="matriz-axb.html"><a href="matriz-axb.html"><i class="fa fa-check"></i><b>5.4</b> Notação matricial do fatorial A×B</a></li>
<li class="chapter" data-level="5.5" data-path="axbxc.html"><a href="axbxc.html"><i class="fa fa-check"></i><b>5.5</b> Fatoriais A×B×C: interações duplas e tripla</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="axbxc.html"><a href="axbxc.html#cubo-2x2x2"><i class="fa fa-check"></i><b>5.5.1</b> O cubo do <span class="math inline">\(2^3\)</span>: visualizando efeitos principais, duplos e triplo</a></li>
<li class="chapter" data-level="5.5.2" data-path="axbxc.html"><a href="axbxc.html#hasse-axbxc"><i class="fa fa-check"></i><b>5.5.2</b> O diagrama de Hasse do fatorial 3×3×3</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="fatoriais-blocos.html"><a href="fatoriais-blocos.html"><i class="fa fa-check"></i><b>5.6</b> Fatoriais de dois fatores em blocos completos</a></li>
<li class="chapter" data-level="5.7" data-path="resumo-do-capítulo-4.html"><a href="resumo-do-capítulo-4.html"><i class="fa fa-check"></i><b>5.7</b> Resumo do capítulo</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="fatoriais-avancado.html"><a href="fatoriais-avancado.html"><i class="fa fa-check"></i><b>6</b> Fatoriais avançados: confusão, fracionamento e superfície de resposta</a>
<ul>
<li class="chapter" data-level="6.1" data-path="fatoriais-2k.html"><a href="fatoriais-2k.html"><i class="fa fa-check"></i><b>6.1</b> Fatoriais <span class="math inline">\(2^k\)</span>: notação e ANOVA</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="fatoriais-2k.html"><a href="fatoriais-2k.html#ortogonalidade-2k"><i class="fa fa-check"></i><b>6.1.1</b> Ortogonalidade da matriz de desenho</a></li>
<li class="chapter" data-level="6.1.2" data-path="fatoriais-2k.html"><a href="fatoriais-2k.html#algoritmo-yates"><i class="fa fa-check"></i><b>6.1.2</b> O algoritmo tabular de Yates</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="nao-replicado.html"><a href="nao-replicado.html"><i class="fa fa-check"></i><b>6.2</b> Análise de um fatorial <span class="math inline">\(2^k\)</span> não replicado</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="nao-replicado.html"><a href="nao-replicado.html#gráfico-de-probabilidade-normal-half-normal-plot"><i class="fa fa-check"></i><b>6.2.1</b> Gráfico de probabilidade normal (half-normal plot)</a></li>
<li class="chapter" data-level="6.2.2" data-path="nao-replicado.html"><a href="nao-replicado.html#gráfico-de-pareto-dos-efeitos"><i class="fa fa-check"></i><b>6.2.2</b> Gráfico de Pareto dos efeitos</a></li>
<li class="chapter" data-level="6.2.3" data-path="nao-replicado.html"><a href="nao-replicado.html#margem-de-erro-pelo-método-de-lenth"><i class="fa fa-check"></i><b>6.2.3</b> Margem de erro pelo método de Lenth</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="confusao-2k.html"><a href="confusao-2k.html"><i class="fa fa-check"></i><b>6.3</b> Confusão em <span class="math inline">\(2^k\)</span>: designação de tratamentos a blocos</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="confusao-2k.html"><a href="confusao-2k.html#esquema-de-designação-o-contraste-definidor"><i class="fa fa-check"></i><b>6.3.1</b> Esquema de designação: o contraste definidor</a></li>
<li class="chapter" data-level="6.3.2" data-path="confusao-2k.html"><a href="confusao-2k.html#confusao-projecao"><i class="fa fa-check"></i><b>6.3.2</b> Confusão como colinearidade em <span class="math inline">\(\mathbf{X}\)</span></a></li>
<li class="chapter" data-level="6.3.3" data-path="confusao-2k.html"><a href="confusao-2k.html#confusão-total-vs.-confusão-parcial"><i class="fa fa-check"></i><b>6.3.3</b> Confusão total vs. confusão parcial</a></li>
<li class="chapter" data-level="6.3.4" data-path="confusao-2k.html"><a href="confusao-2k.html#hasse-confusao"><i class="fa fa-check"></i><b>6.3.4</b> Visualizando a confusão com um diagrama de Hasse</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="fatoriais-3k.html"><a href="fatoriais-3k.html"><i class="fa fa-check"></i><b>6.4</b> Fatoriais <span class="math inline">\(3^k\)</span>: ideia geral e confusão com <span class="math inline">\(AB^2\)</span></a></li>
<li class="chapter" data-level="6.5" data-path="fracionados.html"><a href="fracionados.html"><i class="fa fa-check"></i><b>6.5</b> Fatoriais fracionados de dois níveis: a ideia geral</a></li>
<li class="chapter" data-level="6.6" data-path="rumo-superficie-resposta.html"><a href="rumo-superficie-resposta.html"><i class="fa fa-check"></i><b>6.6</b> Rumo à otimização: superfície de resposta</a></li>
<li class="chapter" data-level="6.7" data-path="resumo-do-capítulo-5.html"><a href="resumo-do-capítulo-5.html"><i class="fa fa-check"></i><b>6.7</b> Resumo do capítulo</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="superficie-resposta-cap.html"><a href="superficie-resposta-cap.html"><i class="fa fa-check"></i><b>7</b> Metodologia de superfície de resposta</a>
<ul>
<li class="chapter" data-level="7.1" data-path="superficie-resposta.html"><a href="superficie-resposta.html"><i class="fa fa-check"></i><b>7.1</b> Introdução à superfície de resposta</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="superficie-resposta.html"><a href="superficie-resposta.html#ponto-estacionario"><i class="fa fa-check"></i><b>7.1.1</b> Classificando o ponto estacionário: gradiente e Hessiana</a></li>
<li class="chapter" data-level="7.1.2" data-path="superficie-resposta.html"><a href="superficie-resposta.html#analise-canonica"><i class="fa fa-check"></i><b>7.1.2</b> Análise canônica: além de classificar, descrever a forma da superfície</a></li>
<li class="chapter" data-level="7.1.3" data-path="superficie-resposta.html"><a href="superficie-resposta.html#ridge-analysis"><i class="fa fa-check"></i><b>7.1.3</b> Análise de ridge: otimizando dentro de um raio fixo da região experimental</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="steepest-ascent.html"><a href="steepest-ascent.html"><i class="fa fa-check"></i><b>7.2</b> O caminho de máxima inclinação: de um fatorial inicial até a região do ótimo</a></li>
<li class="chapter" data-level="7.3" data-path="ccd.html"><a href="ccd.html"><i class="fa fa-check"></i><b>7.3</b> Delineamento composto central (CCD)</a></li>
<li class="chapter" data-level="7.4" data-path="desejabilidade.html"><a href="desejabilidade.html"><i class="fa fa-check"></i><b>7.4</b> Otimização de múltiplas respostas: funções de desejabilidade</a></li>
<li class="chapter" data-level="7.5" data-path="resumo-do-capítulo-6.html"><a href="resumo-do-capítulo-6.html"><i class="fa fa-check"></i><b>7.5</b> Resumo do capítulo</a></li>
<li class="chapter" data-level="7.6" data-path="fim-do-programa-do-semestre.html"><a href="fim-do-programa-do-semestre.html"><i class="fa fa-check"></i><b>7.6</b> Fim do programa do semestre</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ab-bandits.html"><a href="ab-bandits.html"><i class="fa fa-check"></i><b>8</b> Experimentação em produtos digitais: testes A/B e bandits</a>
<ul>
<li class="chapter" data-level="8.1" data-path="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><i class="fa fa-check"></i><b>8.1</b> Parte I — Testes A/B como delineamento completamente aleatorizado</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#ab-e-dca"><i class="fa fa-check"></i><b>8.1.1</b> Um teste A/B é um delineamento completamente aleatorizado</a></li>
<li class="chapter" data-level="8.1.2" data-path="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#ab-dificuldades"><i class="fa fa-check"></i><b>8.1.2</b> Por que testes A/B em produtos digitais são estatisticamente difíceis</a></li>
<li class="chapter" data-level="8.1.3" data-path="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#ab-peeking"><i class="fa fa-check"></i><b>8.1.3</b> O problema do “peeking”</a></li>
<li class="chapter" data-level="8.1.4" data-path="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#ab-winners-curse"><i class="fa fa-check"></i><b>8.1.4</b> Vício do vencedor (<em>winner’s curse</em>)</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><i class="fa fa-check"></i><b>8.2</b> Parte II — Bandits: quando explorar e quando explotar</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html#bandits-motivacao"><i class="fa fa-check"></i><b>8.2.1</b> Exploração, explotação e a definição de arrependimento (<em>regret</em>)</a></li>
<li class="chapter" data-level="8.2.2" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html#bandits-ucb1"><i class="fa fa-check"></i><b>8.2.2</b> Upper Confidence Bound (UCB1): otimismo perante a incerteza</a></li>
<li class="chapter" data-level="8.2.3" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html#bandits-thompson"><i class="fa fa-check"></i><b>8.2.3</b> Thompson sampling: uma solução bayesiana</a></li>
<li class="chapter" data-level="8.2.4" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html#bandits-vs-ab"><i class="fa fa-check"></i><b>8.2.4</b> Horizonte fixo ou bandit?</a></li>
<li class="chapter" data-level="8.2.5" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html#outros-topicos"><i class="fa fa-check"></i><b>8.2.5</b> Outros tópicos modernos</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="resumo-do-capítulo-7.html"><a href="resumo-do-capítulo-7.html"><i class="fa fa-check"></i><b>8.3</b> Resumo do capítulo</a></li>
<li class="chapter" data-level="8.4" data-path="encerrando-o-livro.html"><a href="encerrando-o-livro.html"><i class="fa fa-check"></i><b>8.4</b> Encerrando o livro</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://raydonal.github.io/matd48/" target="_blank">MATD48 — Página do curso</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Planejamento e Análise de Experimentos</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="parte-i-testes-ab-como-delineamento-completamente-aleatorizado" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> Parte I — Testes A/B como delineamento completamente aleatorizado<a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#parte-i-testes-ab-como-delineamento-completamente-aleatorizado" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="ab-e-dca" class="section level3 hasAnchor" number="8.1.1">
<h3><span class="header-section-number">8.1.1</span> Um teste A/B é um delineamento completamente aleatorizado<a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#ab-e-dca" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Tire o vocabulário de produto — “variante”, “conversão”, “tráfego” — e o que resta é exatamente o
delineamento completamente aleatorizado (DCA) de dois tratamentos do Capítulo 3, na notação de
resultados potenciais estabelecida na Seção <a href="tres-aspectos.html#neyman-rubin">1.4.3</a> do Capítulo 1. A unidade
experimental <span class="math inline">\(i\)</span> é o <strong>usuário</strong> (ou, mais precisamente, a sessão ou o dispositivo, dependendo de
como o sistema de experimentação identifica “quem” está sendo tratado — voltaremos a essa
sutileza). O tratamento <span class="math inline">\(Z_i \in \{0,1\}\)</span> indica se o usuário <span class="math inline">\(i\)</span> foi alocado para o controle
(“A”, a versão atual do produto) ou para a variante (“B”, a mudança proposta). Cada usuário tem
dois resultados potenciais, <span class="math inline">\(Y_i(0)\)</span> e <span class="math inline">\(Y_i(1)\)</span> — por exemplo, um indicador binário de conversão
(comprou ou não, em uma sessão), o tempo gasto na página, ou a receita gerada — mas o sistema só
observa um deles, <span class="math inline">\(Y_i = Z_iY_i(1) + (1-Z_i)Y_i(0)\)</span>, exatamente como na equação
(<a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#eq:resultado-observado-ab">(8.1)</a>) abaixo, que repete a estrutura da Seção <a href="tres-aspectos.html#neyman-rubin">1.4.3</a>:</p>
<p><span class="math display" id="eq:resultado-observado-ab">\[\begin{equation}
Y_i = Z_i\,Y_i(1) + (1-Z_i)\,Y_i(0), \qquad Z_i \sim \text{Bernoulli}(1/2) \text{ (tipicamente)},
\tag{8.1}
\end{equation}\]</span></p>
<p>com <span class="math inline">\(Z_i\)</span> sorteado independentemente entre usuários. O estimando de interesse é o efeito médio do
tratamento,</p>
<p><span class="math display">\[
\text{ATE} = E[Y_i(1) - Y_i(0)],
\]</span></p>
<p>que no caso mais comum de uma métrica binária de conversão se reduz a uma diferença de proporções,
<span class="math inline">\(\text{ATE} = p_1 - p_0\)</span>, com <span class="math inline">\(p_1 = P(Y_i(1)=1)\)</span> e <span class="math inline">\(p_0 = P(Y_i(0)=1)\)</span>. O estimador natural,</p>
<p><span class="math display">\[
\widehat{\text{ATE}} = \bar Y_1^{\,obs} - \bar Y_0^{\,obs} = \hat p_1 - \hat p_0,
\]</span></p>
<p>é exatamente a diferença de médias amostrais do Capítulo 3, e a demonstração de
<span class="math inline">\(E[\widehat{\text{ATE}}]=\text{ATE}\)</span> da Seção <a href="tres-aspectos.html#neyman-rubin">1.4.3</a> se aplica sem alteração alguma:
não depende do contexto (parcela agrícola, estudante ou usuário de site), só do mecanismo de
aleatorização. Em notação de modelo linear (Capítulo 2), o mesmo problema se escreve</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 Z_i + \varepsilon_i, \qquad i=1,\dots,N,
\]</span></p>
<p>com <span class="math inline">\(\hat\beta_1\)</span> (o coeficiente de <span class="math inline">\(Z_i\)</span> em uma regressão OLS de <span class="math inline">\(Y\)</span> contra o indicador de
tratamento) numericamente idêntico a <span class="math inline">\(\hat p_1 - \hat p_0\)</span> — a regressão com um único regressor
binário <em>é</em> o teste de duas amostras, um fato que já usamos implicitamente no Capítulo 3 e que
aqui simplesmente reaparece com outro nome de aplicação.</p>
<p>O que muda de fato, em relação ao DCA de laboratório do Capítulo 3, é a <strong>mecânica de
aleatorização</strong>. Um pesquisador de psicologia sorteia 36 voluntários e anota manualmente quem
recebeu qual condição; uma plataforma digital recebe milhões de requisições por segundo e precisa
decidir, em tempo real e sem consultar um banco de dados central, se um usuário específico vê a
versão A ou B — e precisa que a <em>mesma</em> pessoa continue vendo a mesma versão em visitas
subsequentes (senão a “unidade experimental” se confunde com a “unidade de observação”, o mesmo
problema de submuestreo da Seção <a href="unidades.html#unidades">1.2</a>, só que ao contrário: aqui queremos <em>evitar</em>
múltiplas atribuições da mesma unidade). A solução industrial padrão é a <strong>aleatorização por
hash</strong>: aplica-se uma função hash determinística (por exemplo, MD5 ou MurmurHash) ao identificador
do usuário concatenado com um identificador do experimento, e o resultado — um número
pseudoaleatório, mas <em>reprodutível</em> para o mesmo par (usuário, experimento) — decide o grupo. Isso
tem duas propriedades cruciais: (1) a mesma pessoa sempre cai no mesmo grupo dentro de um mesmo
experimento, preservando a unidade experimental como o usuário e não a visita; e (2) usada com
“seeds” (sementes de hash) diferentes por experimento, a mesma pessoa pode estar em experimentos
<em>diferentes e não correlacionados</em> ao mesmo tempo, o que viabiliza rodar milhares de testes A/B
simultâneos sem que a alocação de um contamine a de outro <span class="citation">(<a href="#ref-kohavi2020trustworthy">Kohavi et al., 2020</a>)</span>.</p>
<div class="caixa-aplicacao">
<strong>Aplicação — Ciência de dados: cor do botão de checkout</strong><br>
Uma loja online quer saber se trocar a cor do botão "Finalizar compra" de cinza para verde aumenta
a taxa de conversão. O sistema de experimentação faz o hash do <code>user_id</code> de cada
visitante e atribui metade a cada grupo — grupo A (cinza, controle) e grupo B (verde, variante).
Cada visitante $i$ tem um resultado potencial binário $Y_i(0)$ (converteria vendo cinza?) e
$Y_i(1)$ (converteria vendo verde?), mas o hash decide qual dos dois é revelado. Ao final de duas
semanas de tráfego, o time compara $\hat p_1$ (conversão observada no grupo B) com $\hat p_0$
(conversão observada no grupo A).
</div>
<p>Do ponto de vista puramente algébrico, portanto, não há nada de novo aqui — e é exatamente por
isso que testes A/B se popularizaram tão rápido: qualquer time de produto, sem treinamento formal
em delineamento de experimentos, consegue programar um teste de duas amostras. O que a Seção
seguinte argumenta é que a <em>facilidade de implementar</em> um teste A/B tecnicamente correto é
enganosa — o contexto de alto volume, métricas ruidosas e pressão para decidir rápido introduz uma
família de armadilhas estatísticas que raramente aparecem no experimento de bancada clássico.</p>
</div>
<div id="ab-dificuldades" class="section level3 hasAnchor" number="8.1.2">
<h3><span class="header-section-number">8.1.2</span> Por que testes A/B em produtos digitais são estatisticamente difíceis<a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#ab-dificuldades" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Se a matemática é a mesma do Capítulo 3, por que Kohavi, Tang e Xu dedicam um livro inteiro
<span class="citation">(<a href="#ref-kohavi2020trustworthy">2020</a>)</span> só às dificuldades práticas de rodar testes A/B “à escala”? Quatro razões
concentram a maior parte do problema.</p>
<p><strong>Efeitos pequenos, variância grande.</strong> Uma mudança de layout raramente move a taxa de conversão
de um site em mais do que uma fração de ponto percentual — de <span class="math inline">\(p_0=10{,}0\%\)</span> para <span class="math inline">\(p_1=10{,}3\%\)</span>,
digamos. Para uma proporção, a variância do estimador <span class="math inline">\(\hat p\)</span> é <span class="math inline">\(p(1-p)/n\)</span>, que para <span class="math inline">\(p\approx0{,}1\)</span>
não é pequena em termos relativos: detectar uma diferença de <span class="math inline">\(0{,}3\)</span> pontos percentuais com poder
razoável (<span class="math inline">\(1-\beta=0{,}8\)</span>, <span class="math inline">\(\alpha=0{,}05\)</span>) exige, pela fórmula de tamanho amostral para duas
proporções análoga à da Seção de poder do Capítulo 3,</p>
<p><span class="math display">\[
n \approx \frac{\big(z_{\alpha/2} + z_\beta\big)^2 \big[p_0(1-p_0) + p_1(1-p_1)\big]}{(p_1-p_0)^2},
\]</span></p>
<p>algo da ordem de <strong>centenas de milhares</strong> de usuários por grupo — perfeitamente viável para uma
plataforma grande, impossível para a maioria dos experimentos de laboratório do resto deste livro.
Métricas de receita são ainda piores: distribuições fortemente assimétricas, com uma minoria de
usuários de alto gasto dominando a variância, de modo que o denominador <span class="math inline">\(p_1(1-p_1)\)</span> acima
subestima muito a dificuldade real de detectar efeitos em métricas monetárias.</p>
<p><strong>Múltiplas métricas e múltiplos testes simultâneos.</strong> Um teste A/B raramente monitora uma única
métrica. Times de produto acompanham um <strong>OEC</strong> (<em>Overall Evaluation Criterion</em>, a métrica de
decisão primária) junto de dezenas de métricas secundárias e de “guarda-corpo” (<em>guardrail
metrics</em> — métricas que não deveriam piorar, como tempo de carregamento ou taxa de erro). Ver
dezenas de métricas simultaneamente é, estruturalmente, o mesmo problema do
<a href="comparacoes-multiplas.html#comparacoes-multiplas">3.7</a>: sob <span class="math inline">\(\alpha=0{,}05\)</span> por métrica, a chance de pelo menos um falso
positivo entre 20 métricas independentes já passa de <span class="math inline">\(64\%\)</span>
(<span class="math inline">\(1-(1-0{,}05)^{20}\approx0{,}64\)</span>). A prática recomendada por <span class="citation">Kohavi et al. (<a href="#ref-kohavi2020trustworthy">2020</a>)</span> — escolher o
OEC <em>antes</em> de rodar o teste e tratá-lo com o rigor de uma hipótese pré-registrada, deixando as
métricas secundárias para geração de hipóteses, não confirmação — é uma aplicação direta do
princípio contra <em>data snooping</em> já discutido na Seção <a href="comparacoes-multiplas.html#data-snooping">3.7.1</a>.</p>
<p><strong>Efeito de novidade (e o oposto, efeito de primazia).</strong> Uma mudança de interface pode gerar uma
reação inicial que não reflete o efeito de longo prazo: usuários clicam em um botão só porque ele é
diferente (efeito de novidade, que infla o efeito estimado nos primeiros dias e desaparece depois),
ou resistem a uma mudança só por ser mudança, mesmo que objetivamente melhor (efeito de primazia,
que faz o teste subestimar o efeito real até os usuários se acostumarem). Isso viola implicitamente
uma suposição que o Capítulo 1 deixou implícita ao tratar <span class="math inline">\(Y_i(t)\)</span> como fixo: aqui, o resultado
potencial de um usuário que permanece exposto ao tratamento por semanas não é constante no tempo, e
o “ATE médio nas primeiras 48 horas” pode ser um estimando diferente do “ATE médio de longo prazo”
que o time de produto realmente quer.</p>
<p><strong>Dependência temporal dentro do mesmo usuário.</strong> O mesmo usuário volta ao site várias vezes ao
longo do período do teste, e cada visita gera uma observação — mas, exatamente como no problema de
submuestreo formalizado na Seção <a href="unidades.html#unidades">1.2</a>, essas observações repetidas <strong>não são réplicas
independentes</strong>: são correlacionadas dentro do usuário (alguém propenso a comprar tende a comprar
em várias visitas; alguém que nunca compra continua não comprando). Tratar cada visita como uma
unidade experimental independente — em vez de agregar por usuário antes de testar, como manda o
princípio de submuestreo do Capítulo 1 — infla artificialmente o tamanho amostral efetivo e produz
erros-padrão anticonservadores, exatamente o mesmo erro de pseudorreplicação identificado naquela
seção, só que reaparecendo aqui sob um nome de produto diferente.</p>
<div class="caixa-r"><strong>Uso do R</strong> — poder de um teste A/B para efeitos pequenos</div>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb250-1" tabindex="-1"></a>p0 <span class="ot">&lt;-</span> <span class="fl">0.10</span></span>
<span id="cb250-2"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb250-2" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fl">0.103</span>    <span class="co"># lift de 0,3 ponto percentual — típico de um teste de UI em e-commerce</span></span>
<span id="cb250-3"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb250-3" tabindex="-1"></a></span>
<span id="cb250-4"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb250-4" tabindex="-1"></a>poder_ab <span class="ot">&lt;-</span> <span class="fu">power.prop.test</span>(<span class="at">p1 =</span> p0, <span class="at">p2 =</span> p1, <span class="at">sig.level =</span> <span class="fl">0.05</span>, <span class="at">power =</span> <span class="fl">0.80</span>)</span>
<span id="cb250-5"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb250-5" tabindex="-1"></a>poder_ab<span class="sc">$</span>n</span></code></pre></div>
<pre><code>## [1] 159065.5</code></pre>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:ab-poder-tabela">Table 8.1: </span><span id="tab:ab-poder-tabela">Table 8.2: </span>Tamanho amostral necessário por grupo para detectar diferentes lifts, partindo de p0 = 10%, alpha = 0,05, poder = 80%
</caption>
<thead>
<tr>
<th style="text-align:left;">
Cenário
</th>
<th style="text-align:right;">
n por grupo
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Lift de 0,3 p.p. (UI)
</td>
<td style="text-align:right;">
159066
</td>
</tr>
<tr>
<td style="text-align:left;">
Lift de 1,0 p.p. (feature nova)
</td>
<td style="text-align:right;">
14751
</td>
</tr>
<tr>
<td style="text-align:left;">
Lift de 3,0 p.p. (mudança grande)
</td>
<td style="text-align:right;">
1774
</td>
</tr>
</tbody>
</table>
<p>O contraste é gritante: para detectar um efeito realista de UI (0,3 ponto percentual) são
necessários mais de 159,066 usuários <strong>por grupo</strong> — um volume que
só faz sentido em contexto de alto tráfego, e que explica por que testes A/B de produto digital são
projetados de forma tão diferente de um experimento de bancada com 30 ou 40 sujeitos.</p>
</div>
<div id="ab-peeking" class="section level3 hasAnchor" number="8.1.3">
<h3><span class="header-section-number">8.1.3</span> O problema do “peeking”<a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#ab-peeking" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A teoria do teste <span class="math inline">\(t\)</span>/<span class="math inline">\(F\)</span> clássica pressupõe que o tamanho amostral <span class="math inline">\(n\)</span> é <strong>fixo antes da coleta</strong>
e a decisão de rejeitar ou não <span class="math inline">\(H_0\)</span> é tomada <strong>uma única vez</strong>, depois que todos os <span class="math inline">\(n\)</span> dados
foram coletados. É essa suposição — não nenhuma outra — que garante que <span class="math inline">\(P(\text{rejeitar } H_0\mid H_0\text{ verdadeira}) = \alpha\)</span> exatamente. Em um ambiente de produto, porém, é natural
(e tentador) olhar o painel de resultados do teste todos os dias, calcular o valor-<span class="math inline">\(p\)</span> a cada
olhada, e parar assim que ele cruza <span class="math inline">\(0{,}05\)</span> — prática conhecida como <strong><em>peeking</em></strong> (“espiar”). O
problema é que essa prática transforma silenciosamente o procedimento em outro completamente
diferente: em vez de “um teste com <span class="math inline">\(\alpha=0{,}05\)</span>”, o que se está executando é “uma sequência de
testes, parando no primeiro que rejeitar” — e a probabilidade de que <em>pelo menos um</em> desses testes
rejeite, mesmo sob <span class="math inline">\(H_0\)</span> verdadeira, é muito maior que <span class="math inline">\(0{,}05\)</span> <span class="citation">(<a href="#ref-johari2017peeking">Johari et al., 2017</a>)</span>.</p>
<p>A intuição por trás da inflação vem de um argumento de passeio aleatório: sob <span class="math inline">\(H_0\)</span>, a estatística
de teste acumulada ao longo do tempo (por exemplo, a diferença de proporções observadas até o
instante <span class="math inline">\(t\)</span>) evolui como um processo estocástico que oscila em torno de zero, com variância
crescente. Um resultado clássico de teoria de sequências (relacionado à lei do logaritmo iterado)
garante que, se o processo é observado continuamente e o pesquisador para assim que ele cruza
<em>qualquer</em> limiar fixo, o cruzamento acontece <strong>quase certamente</strong>, mesmo que a média do processo
seja exatamente zero — basta esperar o tempo suficiente. Checar o valor-<span class="math inline">\(p\)</span> repetidamente e parar
no primeiro cruzamento de <span class="math inline">\(0{,}05\)</span> é uma versão discreta exatamente desse fenômeno: quanto mais
vezes se olha, maior a chance de que, só por acaso, uma das checagens caia abaixo do limiar.</p>
<p>A forma matematicamente correta de testar sequencialmente — permitindo checagens repetidas <em>sem</em>
inflar <span class="math inline">\(\alpha\)</span> — não é simplesmente “não olhar”, mas usar um procedimento desenhado para isso. O
<strong>teste sequencial de razão de verossimilhança</strong> (SPRT, <em>sequential probability ratio test</em>) de
<span class="citation">Wald (<a href="#ref-wald1945sprt">1945</a>)</span> formaliza a ideia: em vez de um limiar fixo de significância aplicado a um <span class="math inline">\(n\)</span> fixo,
o SPRT define dois limiares <span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span> para a razão de verossimilhanças acumulada
<span class="math inline">\(\Lambda_n = \prod_{i=1}^n f_1(Y_i)/f_0(Y_i)\)</span> entre a hipótese alternativa e a nula, e continua
coletando dados enquanto <span class="math inline">\(B &lt; \Lambda_n &lt; A\)</span>, parando para rejeitar <span class="math inline">\(H_0\)</span> assim que
<span class="math inline">\(\Lambda_n \geq A\)</span> e para não rejeitar assim que <span class="math inline">\(\Lambda_n \leq B\)</span>. Escolhendo <span class="math inline">\(A\)</span> e <span class="math inline">\(B\)</span> em função
dos erros tipo I e II desejados (<span class="math inline">\(A \approx (1-\beta)/\alpha\)</span>, <span class="math inline">\(B \approx \beta/(1-\alpha)\)</span>), o SPRT
garante as mesmas taxas de erro nominal do teste de tamanho fixo, <em>mesmo permitindo parar a
qualquer momento</em> — a diferença crucial é que os limiares de decisão do SPRT são derivados
especificamente para controlar o erro acumulado de múltiplas checagens, ao passo que reaplicar
ingenuamente o limiar <span class="math inline">\(p&lt;0{,}05\)</span> do teste de tamanho fixo a cada checagem não tem essa propriedade.
Ferramentas modernas de teste sequencial em produto (testes de razão de verossimilhança sempre
válidos, <em>always-valid p-values</em>) generalizam essa ideia para o contexto de testes A/B contínuos
<span class="citation">(<a href="#ref-johari2017peeking">Johari et al., 2017</a>)</span>, mas o princípio já está inteiro no SPRT de 1945.</p>
<div class="caixa-r"><strong>Uso do R</strong> — simulando a inflação do erro tipo I sob peeking</div>
<p>A simulação a seguir gera dados sob <span class="math inline">\(H_0\)</span> verdadeira (as duas variantes têm exatamente a mesma taxa
de conversão, <span class="math inline">\(p=0{,}10\)</span>) e compara duas formas de decidir: (i) checar o valor-<span class="math inline">\(p\)</span> a cada 100
usuários acumulados, até um máximo de 2.000 por grupo, e parar assim que <span class="math inline">\(p&lt;0{,}05\)</span> (“peeking”); e
(ii) checar uma única vez, ao final dos 2.000 usuários. Sob <span class="math inline">\(H_0\)</span>, ambas deveriam rejeitar cerca de
<span class="math inline">\(5\%\)</span> das vezes — a pergunta é se de fato rejeitam.</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb252-2"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-2" tabindex="-1"></a></span>
<span id="cb252-3"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-3" tabindex="-1"></a>n_max      <span class="ot">&lt;-</span> <span class="dv">2000</span>                       <span class="co"># tamanho amostral maximo por braco</span></span>
<span id="cb252-4"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-4" tabindex="-1"></a>checagens  <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">100</span>, n_max, <span class="at">by =</span> <span class="dv">100</span>)  <span class="co"># instantes de checagem (a cada 100 usuarios)</span></span>
<span id="cb252-5"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-5" tabindex="-1"></a>n_sim      <span class="ot">&lt;-</span> <span class="dv">3000</span>                       <span class="co"># replicas Monte Carlo</span></span>
<span id="cb252-6"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-6" tabindex="-1"></a>alpha      <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb252-7"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-7" tabindex="-1"></a>p_H0       <span class="ot">&lt;-</span> <span class="fl">0.10</span>                       <span class="co"># mesma taxa de conversao nos dois bracos (H0 verdadeira)</span></span>
<span id="cb252-8"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-8" tabindex="-1"></a></span>
<span id="cb252-9"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-9" tabindex="-1"></a>simula_uma_replica <span class="ot">&lt;-</span> <span class="cf">function</span>() {</span>
<span id="cb252-10"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-10" tabindex="-1"></a>  grupo_a <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n_max, <span class="dv">1</span>, p_H0)</span>
<span id="cb252-11"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-11" tabindex="-1"></a>  grupo_b <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(n_max, <span class="dv">1</span>, p_H0)</span>
<span id="cb252-12"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-12" tabindex="-1"></a></span>
<span id="cb252-13"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-13" tabindex="-1"></a>  rejeitou_com_peeking <span class="ot">&lt;-</span> <span class="cn">FALSE</span></span>
<span id="cb252-14"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-14" tabindex="-1"></a>  <span class="cf">for</span> (n <span class="cf">in</span> checagens) {</span>
<span id="cb252-15"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-15" tabindex="-1"></a>    xa <span class="ot">&lt;-</span> <span class="fu">sum</span>(grupo_a[<span class="dv">1</span><span class="sc">:</span>n]); xb <span class="ot">&lt;-</span> <span class="fu">sum</span>(grupo_b[<span class="dv">1</span><span class="sc">:</span>n])</span>
<span id="cb252-16"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-16" tabindex="-1"></a>    pval <span class="ot">&lt;-</span> <span class="fu">suppressWarnings</span>(<span class="fu">prop.test</span>(<span class="fu">c</span>(xa, xb), <span class="fu">c</span>(n, n), <span class="at">correct =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>p.value)</span>
<span id="cb252-17"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-17" tabindex="-1"></a>    <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.na</span>(pval) <span class="sc">&amp;&amp;</span> pval <span class="sc">&lt;</span> alpha) { rejeitou_com_peeking <span class="ot">&lt;-</span> <span class="cn">TRUE</span>; <span class="cf">break</span> }</span>
<span id="cb252-18"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-18" tabindex="-1"></a>  }</span>
<span id="cb252-19"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-19" tabindex="-1"></a></span>
<span id="cb252-20"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-20" tabindex="-1"></a>  pval_tamanho_fixo <span class="ot">&lt;-</span> <span class="fu">suppressWarnings</span>(</span>
<span id="cb252-21"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-21" tabindex="-1"></a>    <span class="fu">prop.test</span>(<span class="fu">c</span>(<span class="fu">sum</span>(grupo_a), <span class="fu">sum</span>(grupo_b)), <span class="fu">c</span>(n_max, n_max), <span class="at">correct =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>p.value</span>
<span id="cb252-22"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-22" tabindex="-1"></a>  )</span>
<span id="cb252-23"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-23" tabindex="-1"></a></span>
<span id="cb252-24"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-24" tabindex="-1"></a>  <span class="fu">c</span>(<span class="at">peeking =</span> rejeitou_com_peeking, <span class="at">fixo =</span> pval_tamanho_fixo <span class="sc">&lt;</span> alpha)</span>
<span id="cb252-25"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-25" tabindex="-1"></a>}</span>
<span id="cb252-26"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-26" tabindex="-1"></a></span>
<span id="cb252-27"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-27" tabindex="-1"></a>resultado_peeking <span class="ot">&lt;-</span> <span class="fu">replicate</span>(n_sim, <span class="fu">simula_uma_replica</span>())</span>
<span id="cb252-28"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-28" tabindex="-1"></a>taxa_peeking <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">as.logical</span>(resultado_peeking[<span class="st">&quot;peeking&quot;</span>, ]))</span>
<span id="cb252-29"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-29" tabindex="-1"></a>taxa_fixo    <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">as.logical</span>(resultado_peeking[<span class="st">&quot;fixo&quot;</span>, ]))</span>
<span id="cb252-30"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-30" tabindex="-1"></a></span>
<span id="cb252-31"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-31" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb252-32"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-32" tabindex="-1"></a>  <span class="at">Procedimento =</span> <span class="fu">c</span>(<span class="st">&quot;Checagem única (n fixo = 2.000)&quot;</span>, <span class="st">&quot;Peeking a cada 100 (até n = 2.000)&quot;</span>),</span>
<span id="cb252-33"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-33" tabindex="-1"></a>  <span class="st">`</span><span class="at">Taxa de rejeição sob H0</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">c</span>(taxa_fixo, taxa_peeking)</span>
<span id="cb252-34"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-34" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb252-35"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-35" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>, <span class="at">caption =</span> <span class="st">&quot;Taxa de falso positivo observada em 3.000 réplicas Monte Carlo sob H0 verdadeira&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb252-36"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb252-36" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:ab-peeking-sim">Table 8.3: </span><span id="tab:ab-peeking-sim">Table 8.4: </span>Taxa de falso positivo observada em 3.000 réplicas Monte Carlo sob H0 verdadeira
</caption>
<thead>
<tr>
<th style="text-align:left;">
Procedimento
</th>
<th style="text-align:right;">
Taxa de rejeição sob H0
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Checagem única (n fixo = 2.000)
</td>
<td style="text-align:right;">
0.051
</td>
</tr>
<tr>
<td style="text-align:left;">
Peeking a cada 100 (até n = 2.000)
</td>
<td style="text-align:right;">
0.251
</td>
</tr>
</tbody>
</table>
<p>A checagem única fica, como esperado, muito próxima do <span class="math inline">\(\alpha\)</span> nominal de 0.05
(5.1% observado). Com peeking a cada 100 usuários — só
20 checagens ao longo de todo o experimento, uma frequência bem menor do que o
“olhar o painel todo dia” que de fato acontece em produto — a taxa de falso positivo salta para
25.1%, quase 4.9 vezes
o valor nominal. Nenhuma das duas variantes tinha qualquer efeito real: a diferença inteira vem do
procedimento de parada. Esse é o argumento numérico por trás da recomendação, universal em times de
experimentação de produto, de nunca decidir “parar porque ficou significativo” sem um procedimento
sequencial formal (SPRT ou equivalente) desenhado para isso.</p>
</div>
<div id="ab-winners-curse" class="section level3 hasAnchor" number="8.1.4">
<h3><span class="header-section-number">8.1.4</span> Vício do vencedor (<em>winner’s curse</em>)<a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#ab-winners-curse" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Um problema relacionado, mas distinto, aparece quando várias variantes são testadas ao mesmo tempo
contra o controle (um teste “A/B/n”) e a decisão final é lançar a variante com a <strong>maior</strong>
diferença estimada. Mesmo que todas as variantes tenham, na verdade, o mesmo efeito verdadeiro —
inclusive nulo —, a variante escolhida por ter a maior estimativa amostral tende a ter sua
estimativa <strong>viesada para cima</strong>, simplesmente por ter sido selecionada por ser a maior entre
várias estimativas ruidosas. Esse fenômeno, batizado de <strong>vício do vencedor</strong> (por analogia a
leilões, em que o lance vencedor tende a superestimar o valor real do item), é uma consequência
direta de estatística de ordem: entre <span class="math inline">\(k\)</span> estimativas não-viesadas mas ruidosas de um mesmo
parâmetro, o <em>máximo</em> delas tem expectativa maior do que o parâmetro verdadeiro, e a diferença
cresce com <span class="math inline">\(k\)</span> (mais variantes testadas) e com a variância de cada estimativa individual.</p>
<p>Formalmente, sejam <span class="math inline">\(\hat\delta_1,\dots,\hat\delta_k\)</span> as diferenças estimadas de <span class="math inline">\(k\)</span> variantes
contra o controle, cada uma com <span class="math inline">\(\hat\delta_j \sim N(\delta, \sigma^2)\)</span> sob a suposição (deliberada,
para isolar o fenômeno) de que o efeito verdadeiro <span class="math inline">\(\delta\)</span> é o mesmo para todas. A variante
escolhida é <span class="math inline">\(j^\star = \arg\max_j \hat\delta_j\)</span>, e o vício do vencedor é a quantidade</p>
<p><span class="math display">\[
E\big[\hat\delta_{j^\star}\big] - \delta = E\Big[\max_j \hat\delta_j\Big] - \delta &gt; 0,
\]</span></p>
<p>estritamente positiva sempre que <span class="math inline">\(k&gt;1\)</span> e <span class="math inline">\(\sigma^2&gt;0\)</span> — uma consequência do fato de que o máximo de
variáveis aleatórias tem expectativa maior ou igual à expectativa comum de cada uma (com igualdade
só no caso degenerado <span class="math inline">\(\sigma^2=0\)</span>). É o mesmo fenômeno estatístico, com sinal trocado, por trás da
“regressão à média”: medições extremas tendem a ser seguidas por medições mais próximas da média,
porque parte do que as tornou extremas foi ruído, não sinal persistente.</p>
<div class="caixa-r"><strong>Uso do R</strong> — simulando o vício do vencedor</div>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb253-2"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-2" tabindex="-1"></a></span>
<span id="cb253-3"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-3" tabindex="-1"></a>n_variantes    <span class="ot">&lt;-</span> <span class="dv">10</span>    <span class="co"># variantes testadas simultaneamente contra o controle</span></span>
<span id="cb253-4"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-4" tabindex="-1"></a>n_por_variante <span class="ot">&lt;-</span> <span class="dv">500</span>   <span class="co"># usuarios por variante</span></span>
<span id="cb253-5"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-5" tabindex="-1"></a>efeito_real    <span class="ot">&lt;-</span> <span class="dv">0</span>     <span class="co"># todas as variantes tem, de fato, o MESMO efeito verdadeiro</span></span>
<span id="cb253-6"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-6" tabindex="-1"></a>sigma          <span class="ot">&lt;-</span> <span class="dv">1</span>     <span class="co"># desvio-padrao da metrica (escala padronizada)</span></span>
<span id="cb253-7"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-7" tabindex="-1"></a>n_sim          <span class="ot">&lt;-</span> <span class="dv">5000</span>  <span class="co"># replicas Monte Carlo</span></span>
<span id="cb253-8"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-8" tabindex="-1"></a></span>
<span id="cb253-9"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-9" tabindex="-1"></a>simula_vencedora <span class="ot">&lt;-</span> <span class="cf">function</span>() {</span>
<span id="cb253-10"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-10" tabindex="-1"></a>  estimativas <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n_variantes, <span class="at">mean =</span> efeito_real, <span class="at">sd =</span> sigma <span class="sc">/</span> <span class="fu">sqrt</span>(n_por_variante))</span>
<span id="cb253-11"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-11" tabindex="-1"></a>  estimativas[<span class="fu">which.max</span>(estimativas)]</span>
<span id="cb253-12"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-12" tabindex="-1"></a>}</span>
<span id="cb253-13"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-13" tabindex="-1"></a></span>
<span id="cb253-14"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-14" tabindex="-1"></a>estimativas_vencedoras <span class="ot">&lt;-</span> <span class="fu">replicate</span>(n_sim, <span class="fu">simula_vencedora</span>())</span>
<span id="cb253-15"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-15" tabindex="-1"></a>vies_vencedor <span class="ot">&lt;-</span> <span class="fu">mean</span>(estimativas_vencedoras) <span class="sc">-</span> efeito_real</span>
<span id="cb253-16"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-16" tabindex="-1"></a></span>
<span id="cb253-17"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-17" tabindex="-1"></a><span class="fu">tibble</span>(</span>
<span id="cb253-18"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-18" tabindex="-1"></a>  <span class="at">Quantidade =</span> <span class="fu">c</span>(<span class="st">&quot;Efeito verdadeiro (idêntico em todas as variantes)&quot;</span>,</span>
<span id="cb253-19"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-19" tabindex="-1"></a>                 <span class="st">&quot;Média das estimativas da variante vencedora (5.000 réplicas)&quot;</span>,</span>
<span id="cb253-20"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-20" tabindex="-1"></a>                 <span class="st">&quot;Vício do vencedor&quot;</span>),</span>
<span id="cb253-21"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-21" tabindex="-1"></a>  <span class="at">Valor =</span> <span class="fu">c</span>(efeito_real, <span class="fu">mean</span>(estimativas_vencedoras), vies_vencedor)</span>
<span id="cb253-22"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-22" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb253-23"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-23" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">4</span>, <span class="at">caption =</span> <span class="st">&quot;Vício do vencedor: efeito estimado da melhor entre 10 variantes idênticas&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb253-24"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#cb253-24" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:ab-winners-curse-sim">Table 8.5: </span><span id="tab:ab-winners-curse-sim">Table 8.6: </span>Vício do vencedor: efeito estimado da melhor entre 10 variantes idênticas
</caption>
<thead>
<tr>
<th style="text-align:left;">
Quantidade
</th>
<th style="text-align:right;">
Valor
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Efeito verdadeiro (idêntico em todas as variantes)
</td>
<td style="text-align:right;">
0.0000
</td>
</tr>
<tr>
<td style="text-align:left;">
Média das estimativas da variante vencedora (5.000 réplicas)
</td>
<td style="text-align:right;">
0.0691
</td>
</tr>
<tr>
<td style="text-align:left;">
Vício do vencedor
</td>
<td style="text-align:right;">
0.0691
</td>
</tr>
</tbody>
</table>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ab-winners-curse-plot"></span>
<img src="08-ab-testing-bandits_files/figure-html/ab-winners-curse-plot-1.png" alt="Distribuição, sobre 5.000 réplicas Monte Carlo, do efeito estimado da variante vencedora (a de maior estimativa entre 10 variantes com efeito verdadeiro idêntico), com o efeito verdadeiro (zero) marcado pela linha tracejada." width="80%" />
<p class="caption">
Figure 8.1: Distribuição, sobre 5.000 réplicas Monte Carlo, do efeito estimado da variante vencedora (a de maior estimativa entre 10 variantes com efeito verdadeiro idêntico), com o efeito verdadeiro (zero) marcado pela linha tracejada.
</p>
</div>
<p>Com efeito verdadeiro igual a zero em todas as 10 variantes, a variante escolhida por
ter a maior estimativa amostral aparenta, em média, um efeito de
0.069 — inteiramente espúrio, produto só da seleção pelo máximo entre <code>r n_variantes</code> estimativas ruidosas. A linha tracejada verde no gráfico marca o efeito verdadeiro
(zero); a linha sólida azul marca a média das estimativas vencedoras — a distância entre as duas é
o vício do vencedor. Isso não é um argumento contra testar várias variantes (testar várias ideias
ao mesmo tempo é eficiente), mas um argumento contra <strong>lançar uma variante com base só na
estimativa do próprio teste que a selecionou</strong>: a prática recomendada em times de experimentação
maduros é re-testar a variante vencedora isoladamente, contra o controle, em uma segunda rodada com
tráfego novo — um procedimento de validação <em>fora da amostra</em> que quebra exatamente o mecanismo de
seleção que produz o vício, análogo em espírito à separação treino/validação usada para evitar
sobreajuste em modelos preditivos.</p>
<div class="caixa-discussao">
<strong>Para discutir</strong>
<ol>
<li>A seção sobre validade interna e externa do Capítulo 1 distingue validade interna (a estimativa é
não-viesada para o ATE <em>da amostra estudada</em>) de validade externa (o resultado generaliza
para além dela). Usuários que efetivamente participam de um teste A/B — em geral uma fração do
tráfego total, às vezes restrita a uma região, uma versão de aplicativo ou um segmento de
usuários "elegíveis" para o experimento — são uma amostra aleatória de <em>todos</em> os usuários
da plataforma, ou apenas do subconjunto elegível? Que diferença prática isso faz para decidir se
o resultado se generaliza quando a mudança for lançada para 100% da base?</li>
<li>Se um teste A/B roda só durante uma semana de dezembro (alta temporada de compras), que tipo
de ameaça à validade externa isso introduz, além da amostragem de usuários em si?</li>
<li>Uma plataforma com efeitos de rede (por exemplo, uma rede social, ou um marketplace de duas
pontas) testa uma mudança que afeta a visibilidade de conteúdo. Por que a suposição SUTVA
(seção sobre o modelo de resultados potenciais, no Capítulo 1) — o resultado potencial de um usuário depende só do <em>seu</em>
tratamento, não do tratamento dos demais — é particularmente frágil nesse tipo de produto? O que
pode dar errado ao interpretar o teste como se SUTVA valesse?</li>
</ol>
</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" line-spacing="2">
<div id="ref-johari2017peeking" class="csl-entry">
Johari, R., Koomen, P., Pekelis, L., &amp; Walsh, D. (2017). Peeking at a/b tests: Why it matters, and what to do about it. <em>Proceedings of the 23rd ACM SIGKDD International Conference on Knowledge Discovery and Data Mining</em>, 1517–1525.
</div>
<div id="ref-kohavi2020trustworthy" class="csl-entry">
Kohavi, R., Tang, D., &amp; Xu, Y. (2020). <em>Trustworthy online controlled experiments: A practical guide to a/b testing</em>. Cambridge University Press.
</div>
<div id="ref-wald1945sprt" class="csl-entry">
Wald, A. (1945). Sequential tests of statistical hypotheses. <em>The Annals of Mathematical Statistics</em>, <em>16</em>(2), 117–186.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="ab-bandits.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": false,
    "twitter": false,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
