<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4.6 Parcelas subdivididas (split-plot) | Planejamento e Análise de Experimentos</title>
  <meta name="description" content="Livro-texto de apoio à disciplina MATD48 (Planejamento de Experimentos A), Departamento de Estatística, UFBA." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="4.6 Parcelas subdivididas (split-plot) | Planejamento e Análise de Experimentos" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Livro-texto de apoio à disciplina MATD48 (Planejamento de Experimentos A), Departamento de Estatística, UFBA." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4.6 Parcelas subdivididas (split-plot) | Planejamento e Análise de Experimentos" />
  
  <meta name="twitter:description" content="Livro-texto de apoio à disciplina MATD48 (Planejamento de Experimentos A), Departamento de Estatística, UFBA." />
  

<meta name="author" content="Raydonal Ospina Martínez" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="quadrado-greco-latino.html"/>
<link rel="next" href="resumo-do-capítulo-3.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./"><strong>Planejamento e Análise de Experimentos</strong></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefácio</a>
<ul>
<li class="chapter" data-level="" data-path="para-quem-é-este-livro.html"><a href="para-quem-é-este-livro.html"><i class="fa fa-check"></i>Para quem é este livro</a></li>
<li class="chapter" data-level="" data-path="como-o-material-está-organizado.html"><a href="como-o-material-está-organizado.html"><i class="fa fa-check"></i>Como o material está organizado</a></li>
<li class="chapter" data-level="" data-path="convenções-tipográficas.html"><a href="convenções-tipográficas.html"><i class="fa fa-check"></i>Convenções tipográficas</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="principios.html"><a href="principios.html"><i class="fa fa-check"></i><b>1</b> Princípios do delineamento de experimentos</a>
<ul>
<li class="chapter" data-level="1.1" data-path="metodo-cientifico.html"><a href="metodo-cientifico.html"><i class="fa fa-check"></i><b>1.1</b> O método científico e o papel do delineamento experimental</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="metodo-cientifico.html"><a href="metodo-cientifico.html#o-ciclo-empírico-de-observação-a-hipótese-testável"><i class="fa fa-check"></i><b>1.1.1</b> O ciclo empírico: de observação a hipótese testável</a></li>
<li class="chapter" data-level="1.1.2" data-path="metodo-cientifico.html"><a href="metodo-cientifico.html#observação-vs.-experimentação-por-que-controlado-importa"><i class="fa fa-check"></i><b>1.1.2</b> Observação vs. experimentação: por que “controlado” importa</a></li>
<li class="chapter" data-level="1.1.3" data-path="metodo-cientifico.html"><a href="metodo-cientifico.html#uma-nota-histórica-quantificar-controlar-e-só-depois-formalizar"><i class="fa fa-check"></i><b>1.1.3</b> Uma nota histórica: quantificar, controlar, e só depois formalizar</a></li>
<li class="chapter" data-level="1.1.4" data-path="metodo-cientifico.html"><a href="metodo-cientifico.html#confusão-confounding-o-problema-que-a-aleatorização-resolve"><i class="fa fa-check"></i><b>1.1.4</b> Confusão (<em>confounding</em>): o problema que a aleatorização resolve</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="unidades.html"><a href="unidades.html"><i class="fa fa-check"></i><b>1.2</b> Unidades experimentais e unidades amostrais</a></li>
<li class="chapter" data-level="1.3" data-path="fontes-variacao.html"><a href="fontes-variacao.html"><i class="fa fa-check"></i><b>1.3</b> Fontes de variação</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="fontes-variacao.html"><a href="fontes-variacao.html#aditividade-aleatorizacao"><i class="fa fa-check"></i><b>1.3.1</b> Por que essa decomposição força a forma aditiva do modelo</a></li>
<li class="chapter" data-level="1.3.2" data-path="fontes-variacao.html"><a href="fontes-variacao.html#fatores-niveis"><i class="fa fa-check"></i><b>1.3.2</b> Fatores e níveis</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="tres-aspectos.html"><a href="tres-aspectos.html"><i class="fa fa-check"></i><b>1.4</b> Os três aspectos do delineamento experimental</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="tres-aspectos.html"><a href="tres-aspectos.html#repetição-replicação"><i class="fa fa-check"></i><b>1.4.1</b> Repetição (replicação)</a></li>
<li class="chapter" data-level="1.4.2" data-path="tres-aspectos.html"><a href="tres-aspectos.html#aleatorização"><i class="fa fa-check"></i><b>1.4.2</b> Aleatorização</a></li>
<li class="chapter" data-level="1.4.3" data-path="tres-aspectos.html"><a href="tres-aspectos.html#neyman-rubin"><i class="fa fa-check"></i><b>1.4.3</b> Por que a aleatorização funciona: o modelo de resultados potenciais</a></li>
<li class="chapter" data-level="1.4.4" data-path="tres-aspectos.html"><a href="tres-aspectos.html#ate-binario"><i class="fa fa-check"></i><b>1.4.4</b> Um terceiro domínio: resultados potenciais binários em um teste A/B</a></li>
<li class="chapter" data-level="1.4.5" data-path="tres-aspectos.html"><a href="tres-aspectos.html#validade-externa"><i class="fa fa-check"></i><b>1.4.5</b> Validade interna e validade externa</a></li>
<li class="chapter" data-level="1.4.6" data-path="tres-aspectos.html"><a href="tres-aspectos.html#amostragem-e-desenho"><i class="fa fa-check"></i><b>1.4.6</b> O elo entre amostragem e planejamento de experimentos</a></li>
<li class="chapter" data-level="1.4.7" data-path="tres-aspectos.html"><a href="tres-aspectos.html#controle-local-blocagem"><i class="fa fa-check"></i><b>1.4.7</b> Controle local (blocagem)</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="resumo-do-capítulo.html"><a href="resumo-do-capítulo.html"><i class="fa fa-check"></i><b>1.5</b> Resumo do capítulo</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="modelos-lineares.html"><a href="modelos-lineares.html"><i class="fa fa-check"></i><b>2</b> Introdução aos modelos lineares</a>
<ul>
<li class="chapter" data-level="2.1" data-path="populacao-conceitual.html"><a href="populacao-conceitual.html"><i class="fa fa-check"></i><b>2.1</b> Da população conceitual de respostas ao modelo linear</a></li>
<li class="chapter" data-level="2.2" data-path="hasse.html"><a href="hasse.html"><i class="fa fa-check"></i><b>2.2</b> Diagramas de Hasse: a estrutura do delineamento antes da álgebra</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="hasse.html"><a href="hasse.html#o-diagrama-como-um-retrato-da-estrutura-do-dado"><i class="fa fa-check"></i><b>2.2.1</b> O diagrama como um retrato da estrutura do dado</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="modelo-geral.html"><a href="modelo-geral.html"><i class="fa fa-check"></i><b>2.3</b> O modelo linear geral</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="modelo-geral.html"><a href="modelo-geral.html#porque-xbeta-mais-erro"><i class="fa fa-check"></i><b>2.3.1</b> Por que esta é a forma natural, não arbitrária, do modelo</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="minimos-quadrados.html"><a href="minimos-quadrados.html"><i class="fa fa-check"></i><b>2.4</b> Estimação por mínimos quadrados</a></li>
<li class="chapter" data-level="2.5" data-path="estimabilidade.html"><a href="estimabilidade.html"><i class="fa fa-check"></i><b>2.5</b> Estimabilidade de funções lineares dos parâmetros</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="estimabilidade.html"><a href="estimabilidade.html#svd-moore-penrose"><i class="fa fa-check"></i><b>2.5.1</b> A pseudoinversa de Moore-Penrose via decomposição em valores singulares</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="gauss-markov.html"><a href="gauss-markov.html"><i class="fa fa-check"></i><b>2.6</b> O teorema de Gauss-Markov e o BLUE</a></li>
<li class="chapter" data-level="2.7" data-path="matriz-projecao.html"><a href="matriz-projecao.html"><i class="fa fa-check"></i><b>2.7</b> A matriz de projeção</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="matriz-projecao.html"><a href="matriz-projecao.html#soma-quadrados-total"><i class="fa fa-check"></i><b>2.7.1</b> A soma de quadrados total como forma quadrática</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="modelo-particionado.html"><a href="modelo-particionado.html"><i class="fa fa-check"></i><b>2.8</b> O modelo linear particionado</a></li>
<li class="chapter" data-level="2.9" data-path="fwl.html"><a href="fwl.html"><i class="fa fa-check"></i><b>2.9</b> O teorema de Frisch-Waugh-Lovell</a>
<ul>
<li class="chapter" data-level="2.9.1" data-path="fwl.html"><a href="fwl.html#fwl-experimentos"><i class="fa fa-check"></i><b>2.9.1</b> Conexão com planejamento de experimentos: por que a ANCOVA funciona</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="formas-quadraticas.html"><a href="formas-quadraticas.html"><i class="fa fa-check"></i><b>2.10</b> Distribuição de formas lineares e quadráticas</a></li>
<li class="chapter" data-level="2.11" data-path="resumo-do-capítulo-1.html"><a href="resumo-do-capítulo-1.html"><i class="fa fa-check"></i><b>2.11</b> Resumo do capítulo</a>
<ul>
<li class="chapter" data-level="" data-path="resumo-do-capítulo-1.html"><a href="resumo-do-capítulo-1.html#uma-nota-sobre-notação-de-beta-genérico-a-tau-e-depois-a-alphabetagammadots"><i class="fa fa-check"></i>Uma nota sobre notação: de <span class="math inline">\(\beta\)</span> genérico a <span class="math inline">\(\tau\)</span>, e depois a <span class="math inline">\(\alpha,\beta,\gamma,\dots\)</span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="dca.html"><a href="dca.html"><i class="fa fa-check"></i><b>3</b> Delineamento completamente aleatorizado</a>
<ul>
<li class="chapter" data-level="3.1" data-path="principios-aleatorizacao.html"><a href="principios-aleatorizacao.html"><i class="fa fa-check"></i><b>3.1</b> Princípios de aleatorização: a ideia de um teste de aleatorização</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="principios-aleatorizacao.html"><a href="principios-aleatorizacao.html#randomizacao-df-f"><i class="fa fa-check"></i><b>3.1.1</b> De onde vêm os graus de liberdade <span class="math inline">\((2,33)\)</span>: a ponte entre aleatorização, variância decomposta e <span class="math inline">\(F\)</span></a></li>
<li class="chapter" data-level="3.1.2" data-path="principios-aleatorizacao.html"><a href="principios-aleatorizacao.html#modelo-deduzido"><i class="fa fa-check"></i><b>3.1.2</b> O modelo linear deduzido da aleatorização</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="dca-uma-via.html"><a href="dca-uma-via.html"><i class="fa fa-check"></i><b>3.2</b> O delineamento completamente aleatorizado a uma via de classificação</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="dca-uma-via.html"><a href="dca-uma-via.html#modelo-dca"><i class="fa fa-check"></i><b>3.2.1</b> O modelo estatístico</a></li>
<li class="chapter" data-level="3.2.2" data-path="dca-uma-via.html"><a href="dca-uma-via.html#matricial-dca"><i class="fa fa-check"></i><b>3.2.2</b> Notação matricial: o DCA como caso particular do modelo linear geral</a></li>
<li class="chapter" data-level="3.2.3" data-path="dca-uma-via.html"><a href="dca-uma-via.html#potencial-causal"><i class="fa fa-check"></i><b>3.2.3</b> Resultados potenciais e o estimando causal</a></li>
<li class="chapter" data-level="3.2.4" data-path="dca-uma-via.html"><a href="dca-uma-via.html#ic-dca"><i class="fa fa-check"></i><b>3.2.4</b> Estimação e intervalos de confiança</a></li>
<li class="chapter" data-level="3.2.5" data-path="dca-uma-via.html"><a href="dca-uma-via.html#anova-dca"><i class="fa fa-check"></i><b>3.2.5</b> A tabela de análise de variância</a></li>
<li class="chapter" data-level="3.2.6" data-path="dca-uma-via.html"><a href="dca-uma-via.html#numero-replicas-dca"><i class="fa fa-check"></i><b>3.2.6</b> Número de réplicas necessário</a></li>
<li class="chapter" data-level="3.2.7" data-path="dca-uma-via.html"><a href="dca-uma-via.html#dca-feijao"><i class="fa fa-check"></i><b>3.2.7</b> Um segundo exemplo, com dado real: fertilizante em feijão</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="dca-submuestreo.html"><a href="dca-submuestreo.html"><i class="fa fa-check"></i><b>3.3</b> Submuestreo em um DCA</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="dca-submuestreo.html"><a href="dca-submuestreo.html#modelo-submuestreo"><i class="fa fa-check"></i><b>3.3.1</b> O modelo com dois níveis de erro</a></li>
<li class="chapter" data-level="3.3.2" data-path="dca-submuestreo.html"><a href="dca-submuestreo.html#o-diagrama-de-hasse-do-submuestreo-aninhamento-em-duas-camadas"><i class="fa fa-check"></i><b>3.3.2</b> O diagrama de Hasse do submuestreo: aninhamento em duas camadas</a></li>
<li class="chapter" data-level="3.3.3" data-path="dca-submuestreo.html"><a href="dca-submuestreo.html#anova-submuestreo"><i class="fa fa-check"></i><b>3.3.3</b> ANOVA com submuestreo</a></li>
<li class="chapter" data-level="3.3.4" data-path="dca-submuestreo.html"><a href="dca-submuestreo.html#amostra-submuestreo"><i class="fa fa-check"></i><b>3.3.4</b> Tamanho de amostra com submuestreo</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="dca-efeitos-aleatorios.html"><a href="dca-efeitos-aleatorios.html"><i class="fa fa-check"></i><b>3.4</b> O modelo de efeitos aleatórios</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="dca-efeitos-aleatorios.html"><a href="dca-efeitos-aleatorios.html#modelo-aleatorio"><i class="fa fa-check"></i><b>3.4.1</b> Quando os tratamentos são uma amostra aleatória</a></li>
<li class="chapter" data-level="3.4.2" data-path="dca-efeitos-aleatorios.html"><a href="dca-efeitos-aleatorios.html#anova-aleatorio"><i class="fa fa-check"></i><b>3.4.2</b> ANOVA e componentes de variância</a></li>
<li class="chapter" data-level="3.4.3" data-path="dca-efeitos-aleatorios.html"><a href="dca-efeitos-aleatorios.html#amostra-aleatorio"><i class="fa fa-check"></i><b>3.4.3</b> Tamanho de amostra no modelo de efeitos aleatórios</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="dca-pressupostos.html"><a href="dca-pressupostos.html"><i class="fa fa-check"></i><b>3.5</b> Verificação de pressupostos</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="dca-pressupostos.html"><a href="dca-pressupostos.html#normalidade-dca"><i class="fa fa-check"></i><b>3.5.1</b> Normalidade: gráfico Q-Q e testes formais</a></li>
<li class="chapter" data-level="3.5.2" data-path="dca-pressupostos.html"><a href="dca-pressupostos.html#homocedasticidade-dca"><i class="fa fa-check"></i><b>3.5.2</b> Homogeneidade de variância</a></li>
<li class="chapter" data-level="3.5.3" data-path="dca-pressupostos.html"><a href="dca-pressupostos.html#transformacoes-dca"><i class="fa fa-check"></i><b>3.5.3</b> Transformações usuais</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="contrastes.html"><a href="contrastes.html"><i class="fa fa-check"></i><b>3.6</b> Contrastes e comparações múltiplas</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="contrastes.html"><a href="contrastes.html#definição-esperança-e-variância-de-um-contraste"><i class="fa fa-check"></i><b>3.6.1</b> Definição, esperança e variância de um contraste</a></li>
<li class="chapter" data-level="3.6.2" data-path="contrastes.html"><a href="contrastes.html#soma-de-quadrados-de-um-contraste-e-sua-distribuição"><i class="fa fa-check"></i><b>3.6.2</b> Soma de quadrados de um contraste e sua distribuição</a></li>
<li class="chapter" data-level="3.6.3" data-path="contrastes.html"><a href="contrastes.html#notação-matricial-contraste-como-forma-linear-e-quadrática"><i class="fa fa-check"></i><b>3.6.3</b> Notação matricial: contraste como forma linear e quadrática</a></li>
<li class="chapter" data-level="3.6.4" data-path="contrastes.html"><a href="contrastes.html#contrastes-ortogonais"><i class="fa fa-check"></i><b>3.6.4</b> Contrastes ortogonais</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html"><i class="fa fa-check"></i><b>3.7</b> Procedimentos de comparação múltipla</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#data-snooping"><i class="fa fa-check"></i><b>3.7.1</b> O perigo do “data snooping”</a></li>
<li class="chapter" data-level="3.7.2" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#método-de-scheffé"><i class="fa fa-check"></i><b>3.7.2</b> Método de Scheffé</a></li>
<li class="chapter" data-level="3.7.3" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#método-de-bonferroni"><i class="fa fa-check"></i><b>3.7.3</b> Método de Bonferroni</a></li>
<li class="chapter" data-level="3.7.4" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#tukey-hsd-honestly-significant-difference"><i class="fa fa-check"></i><b>3.7.4</b> Tukey HSD (<em>honestly significant difference</em>)</a></li>
<li class="chapter" data-level="3.7.5" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#comparação-com-um-grupo-controle-dunnett"><i class="fa fa-check"></i><b>3.7.5</b> Comparação com um grupo controle: Dunnett</a></li>
<li class="chapter" data-level="3.7.6" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#teste-de-amplitude-múltipla-de-duncan"><i class="fa fa-check"></i><b>3.7.6</b> Teste de amplitude múltipla de Duncan</a></li>
<li class="chapter" data-level="3.7.7" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#agrupamento-de-tratamentos-compact-letter-display"><i class="fa fa-check"></i><b>3.7.7</b> Agrupamento de tratamentos (<em>compact letter display</em>)</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="polinomios-ortogonais.html"><a href="polinomios-ortogonais.html"><i class="fa fa-check"></i><b>3.8</b> Polinômios ortogonais</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="polinomios-ortogonais.html"><a href="polinomios-ortogonais.html#esperança-variância-e-soma-de-quadrados"><i class="fa fa-check"></i><b>3.8.1</b> Esperança, variância e soma de quadrados</a></li>
<li class="chapter" data-level="3.8.2" data-path="polinomios-ortogonais.html"><a href="polinomios-ortogonais.html#a-matriz-de-polinômios-ortogonais-como-parte-de-mathbf-x"><i class="fa fa-check"></i><b>3.8.2</b> A matriz de polinômios ortogonais como parte de <span class="math inline">\(\mathbf X\)</span></a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="ancova.html"><a href="ancova.html"><i class="fa fa-check"></i><b>3.9</b> Análise de covariância (ANCOVA)</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="ancova.html"><a href="ancova.html#o-modelo"><i class="fa fa-check"></i><b>3.9.1</b> O modelo</a></li>
<li class="chapter" data-level="3.9.2" data-path="ancova.html"><a href="ancova.html#ancova-em-notação-matricial-mais-uma-coluna-em-mathbf-x"><i class="fa fa-check"></i><b>3.9.2</b> ANCOVA em notação matricial: mais uma coluna em <span class="math inline">\(\mathbf X\)</span></a></li>
<li class="chapter" data-level="3.9.3" data-path="ancova.html"><a href="ancova.html#a-tabela-de-anova-ajustada-pela-covariável"><i class="fa fa-check"></i><b>3.9.3</b> A tabela de ANOVA ajustada pela covariável</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="kruskal-wallis.html"><a href="kruskal-wallis.html"><i class="fa fa-check"></i><b>3.10</b> Teste de Kruskal-Wallis</a>
<ul>
<li class="chapter" data-level="3.10.1" data-path="kruskal-wallis.html"><a href="kruskal-wallis.html#o-que-muda-em-relação-à-anova"><i class="fa fa-check"></i><b>3.10.1</b> O que muda em relação à ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="resumo-do-capítulo-2.html"><a href="resumo-do-capítulo-2.html"><i class="fa fa-check"></i><b>3.11</b> Resumo do capítulo</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="blocos.html"><a href="blocos.html"><i class="fa fa-check"></i><b>4</b> Delineamentos com fontes de bloqueio</a>
<ul>
<li class="chapter" data-level="4.1" data-path="dbca.html"><a href="dbca.html"><i class="fa fa-check"></i><b>4.1</b> O delineamento em blocos completos aleatorizados (DBCA)</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="dbca.html"><a href="dbca.html#motivação-o-que-dá-errado-sem-controle-local-fatores-confundidos"><i class="fa fa-check"></i><b>4.1.1</b> Motivação: o que dá errado sem controle local — fatores confundidos</a></li>
<li class="chapter" data-level="4.1.2" data-path="dbca.html"><a href="dbca.html#o-modelo-1"><i class="fa fa-check"></i><b>4.1.2</b> O modelo</a></li>
<li class="chapter" data-level="4.1.3" data-path="dbca.html"><a href="dbca.html#notação-matricial-yxbetavarepsilon"><i class="fa fa-check"></i><b>4.1.3</b> Notação matricial: <span class="math inline">\(Y=X\beta+\varepsilon\)</span></a></li>
<li class="chapter" data-level="4.1.4" data-path="dbca.html"><a href="dbca.html#blocagem-como-aleatorização-restrita-a-camada-causal"><i class="fa fa-check"></i><b>4.1.4</b> Blocagem como aleatorização restrita: a camada causal</a></li>
<li class="chapter" data-level="4.1.5" data-path="dbca.html"><a href="dbca.html#tabela-de-anova"><i class="fa fa-check"></i><b>4.1.5</b> Tabela de ANOVA</a></li>
<li class="chapter" data-level="4.1.6" data-path="dbca.html"><a href="dbca.html#esperança-dos-quadrados-médios"><i class="fa fa-check"></i><b>4.1.6</b> Esperança dos quadrados médios</a></li>
<li class="chapter" data-level="4.1.7" data-path="dbca.html"><a href="dbca.html#visualizando-aditividade-o-gráfico-de-perfis"><i class="fa fa-check"></i><b>4.1.7</b> Visualizando aditividade: o gráfico de perfis</a></li>
<li class="chapter" data-level="4.1.8" data-path="dbca.html"><a href="dbca.html#tukey-nao-aditividade"><i class="fa fa-check"></i><b>4.1.8</b> O teste de não aditividade de Tukey</a></li>
<li class="chapter" data-level="4.1.9" data-path="dbca.html"><a href="dbca.html#diagrama-de-hasse-do-dbca-por-que-não-há-nó-de-interação"><i class="fa fa-check"></i><b>4.1.9</b> Diagrama de Hasse do DBCA: por que não há nó de interação</a></li>
<li class="chapter" data-level="4.1.10" data-path="dbca.html"><a href="dbca.html#dados-faltantes-estimação-do-valor-perdido"><i class="fa fa-check"></i><b>4.1.10</b> Dados faltantes: estimação do valor perdido</a></li>
<li class="chapter" data-level="4.1.11" data-path="dbca.html"><a href="dbca.html#eficiência-relativa-do-dbca-frente-ao-dca"><i class="fa fa-check"></i><b>4.1.11</b> Eficiência relativa do DBCA frente ao DCA</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="friedman.html"><a href="friedman.html"><i class="fa fa-check"></i><b>4.2</b> Teste de Friedman</a></li>
<li class="chapter" data-level="4.3" data-path="bib.html"><a href="bib.html"><i class="fa fa-check"></i><b>4.3</b> Blocos incompletos balanceados</a></li>
<li class="chapter" data-level="4.4" data-path="quadrado-latino.html"><a href="quadrado-latino.html"><i class="fa fa-check"></i><b>4.4</b> Delineamento em quadrado latino</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="quadrado-latino.html"><a href="quadrado-latino.html#motivação-dois-gradientes-ortogonais-e-por-que-um-bloqueio-simples-não-basta"><i class="fa fa-check"></i><b>4.4.1</b> Motivação: dois gradientes ortogonais, e por que um bloqueio simples não basta</a></li>
<li class="chapter" data-level="4.4.2" data-path="quadrado-latino.html"><a href="quadrado-latino.html#o-modelo-2"><i class="fa fa-check"></i><b>4.4.2</b> O modelo</a></li>
<li class="chapter" data-level="4.4.3" data-path="quadrado-latino.html"><a href="quadrado-latino.html#diagrama-de-hasse-do-quadrado-latino-três-fatores-cruzados-dois-a-dois"><i class="fa fa-check"></i><b>4.4.3</b> Diagrama de Hasse do quadrado latino: três fatores cruzados dois a dois</a></li>
<li class="chapter" data-level="4.4.4" data-path="quadrado-latino.html"><a href="quadrado-latino.html#aleatorização-de-um-quadrado-latino-yates1933latin"><i class="fa fa-check"></i><b>4.4.4</b> Aleatorização de um quadrado latino <span class="citation">(Yates, 1933)</span></a></li>
<li class="chapter" data-level="4.4.5" data-path="quadrado-latino.html"><a href="quadrado-latino.html#quadrados-latinos-replicados"><i class="fa fa-check"></i><b>4.4.5</b> Quadrados latinos replicados</a></li>
<li class="chapter" data-level="4.4.6" data-path="quadrado-latino.html"><a href="quadrado-latino.html#quantas-réplicas-uma-análise-de-poder"><i class="fa fa-check"></i><b>4.4.6</b> Quantas réplicas? Uma análise de poder</a></li>
<li class="chapter" data-level="4.4.7" data-path="quadrado-latino.html"><a href="quadrado-latino.html#eficiencia-ql"><i class="fa fa-check"></i><b>4.4.7</b> Eficiência relativa do quadrado latino frente ao DBCA e ao DCA</a></li>
<li class="chapter" data-level="4.4.8" data-path="quadrado-latino.html"><a href="quadrado-latino.html#ql-exemplo-ecommerce"><i class="fa fa-check"></i><b>4.4.8</b> Um segundo exemplo completo: cinco variantes de checkout em e-commerce</a></li>
<li class="chapter" data-level="4.4.9" data-path="quadrado-latino.html"><a href="quadrado-latino.html#youden"><i class="fa fa-check"></i><b>4.4.9</b> Quadrados de Youden: quando o quadrado latino não pode ser completo</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="quadrado-greco-latino.html"><a href="quadrado-greco-latino.html"><i class="fa fa-check"></i><b>4.5</b> Delineamento em quadrado greco-latino</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="quadrado-greco-latino.html"><a href="quadrado-greco-latino.html#mols"><i class="fa fa-check"></i><b>4.5.1</b> Quadrados latinos mutuamente ortogonais (MOLS): existência e o problema de Euler</a></li>
<li class="chapter" data-level="4.5.2" data-path="quadrado-greco-latino.html"><a href="quadrado-greco-latino.html#o-modelo-3"><i class="fa fa-check"></i><b>4.5.2</b> O modelo</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="split-plot.html"><a href="split-plot.html"><i class="fa fa-check"></i><b>4.6</b> Parcelas subdivididas (<em>split-plot</em>)</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="split-plot.html"><a href="split-plot.html#dois-erros-experimentais-não-um"><i class="fa fa-check"></i><b>4.6.1</b> Dois erros experimentais, não um</a></li>
<li class="chapter" data-level="4.6.2" data-path="split-plot.html"><a href="split-plot.html#por-que-o-teste-de-irrigação-usa-um-erro-diferente-do-teste-de-variedade"><i class="fa fa-check"></i><b>4.6.2</b> Por que o teste de irrigação usa um erro diferente do teste de variedade</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="resumo-do-capítulo-3.html"><a href="resumo-do-capítulo-3.html"><i class="fa fa-check"></i><b>4.7</b> Resumo do capítulo</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="fatoriais.html"><a href="fatoriais.html"><i class="fa fa-check"></i><b>5</b> Delineamentos com arranjos fatoriais</a>
<ul>
<li class="chapter" data-level="5.1" data-path="por-que-fatorial.html"><a href="por-que-fatorial.html"><i class="fa fa-check"></i><b>5.1</b> Por que cruzar fatores?</a></li>
<li class="chapter" data-level="5.2" data-path="modelo-axb.html"><a href="modelo-axb.html"><i class="fa fa-check"></i><b>5.2</b> O fatorial A×B: efeitos principais e interação</a></li>
<li class="chapter" data-level="5.3" data-path="anova-axb.html"><a href="anova-axb.html"><i class="fa fa-check"></i><b>5.3</b> Tabela de ANOVA para o fatorial A×B balanceado</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="anova-axb.html"><a href="anova-axb.html#tipos-sq"><i class="fa fa-check"></i><b>5.3.1</b> Quando as células não têm o mesmo tamanho: somas de quadrados Tipo I, II e III</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="matriz-axb.html"><a href="matriz-axb.html"><i class="fa fa-check"></i><b>5.4</b> Notação matricial do fatorial A×B</a></li>
<li class="chapter" data-level="5.5" data-path="axbxc.html"><a href="axbxc.html"><i class="fa fa-check"></i><b>5.5</b> Fatoriais A×B×C: interações duplas e tripla</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="axbxc.html"><a href="axbxc.html#cubo-2x2x2"><i class="fa fa-check"></i><b>5.5.1</b> O cubo do <span class="math inline">\(2^3\)</span>: visualizando efeitos principais, duplos e triplo</a></li>
<li class="chapter" data-level="5.5.2" data-path="axbxc.html"><a href="axbxc.html#hasse-axbxc"><i class="fa fa-check"></i><b>5.5.2</b> O diagrama de Hasse do fatorial 3×3×3</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="fatoriais-blocos.html"><a href="fatoriais-blocos.html"><i class="fa fa-check"></i><b>5.6</b> Fatoriais de dois fatores em blocos completos</a></li>
<li class="chapter" data-level="5.7" data-path="resumo-do-capítulo-4.html"><a href="resumo-do-capítulo-4.html"><i class="fa fa-check"></i><b>5.7</b> Resumo do capítulo</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="fatoriais-avancado.html"><a href="fatoriais-avancado.html"><i class="fa fa-check"></i><b>6</b> Fatoriais avançados: confusão, fracionamento e superfície de resposta</a>
<ul>
<li class="chapter" data-level="6.1" data-path="fatoriais-2k.html"><a href="fatoriais-2k.html"><i class="fa fa-check"></i><b>6.1</b> Fatoriais <span class="math inline">\(2^k\)</span>: notação e ANOVA</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="fatoriais-2k.html"><a href="fatoriais-2k.html#ortogonalidade-2k"><i class="fa fa-check"></i><b>6.1.1</b> Ortogonalidade da matriz de desenho</a></li>
<li class="chapter" data-level="6.1.2" data-path="fatoriais-2k.html"><a href="fatoriais-2k.html#algoritmo-yates"><i class="fa fa-check"></i><b>6.1.2</b> O algoritmo tabular de Yates</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="nao-replicado.html"><a href="nao-replicado.html"><i class="fa fa-check"></i><b>6.2</b> Análise de um fatorial <span class="math inline">\(2^k\)</span> não replicado</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="nao-replicado.html"><a href="nao-replicado.html#gráfico-de-probabilidade-normal-half-normal-plot"><i class="fa fa-check"></i><b>6.2.1</b> Gráfico de probabilidade normal (half-normal plot)</a></li>
<li class="chapter" data-level="6.2.2" data-path="nao-replicado.html"><a href="nao-replicado.html#gráfico-de-pareto-dos-efeitos"><i class="fa fa-check"></i><b>6.2.2</b> Gráfico de Pareto dos efeitos</a></li>
<li class="chapter" data-level="6.2.3" data-path="nao-replicado.html"><a href="nao-replicado.html#margem-de-erro-pelo-método-de-lenth"><i class="fa fa-check"></i><b>6.2.3</b> Margem de erro pelo método de Lenth</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="confusao-2k.html"><a href="confusao-2k.html"><i class="fa fa-check"></i><b>6.3</b> Confusão em <span class="math inline">\(2^k\)</span>: designação de tratamentos a blocos</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="confusao-2k.html"><a href="confusao-2k.html#esquema-de-designação-o-contraste-definidor"><i class="fa fa-check"></i><b>6.3.1</b> Esquema de designação: o contraste definidor</a></li>
<li class="chapter" data-level="6.3.2" data-path="confusao-2k.html"><a href="confusao-2k.html#confusao-projecao"><i class="fa fa-check"></i><b>6.3.2</b> Confusão como colinearidade em <span class="math inline">\(\mathbf{X}\)</span></a></li>
<li class="chapter" data-level="6.3.3" data-path="confusao-2k.html"><a href="confusao-2k.html#confusão-total-vs.-confusão-parcial"><i class="fa fa-check"></i><b>6.3.3</b> Confusão total vs. confusão parcial</a></li>
<li class="chapter" data-level="6.3.4" data-path="confusao-2k.html"><a href="confusao-2k.html#hasse-confusao"><i class="fa fa-check"></i><b>6.3.4</b> Visualizando a confusão com um diagrama de Hasse</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="fatoriais-3k.html"><a href="fatoriais-3k.html"><i class="fa fa-check"></i><b>6.4</b> Fatoriais <span class="math inline">\(3^k\)</span>: ideia geral e confusão com <span class="math inline">\(AB^2\)</span></a></li>
<li class="chapter" data-level="6.5" data-path="fracionados.html"><a href="fracionados.html"><i class="fa fa-check"></i><b>6.5</b> Fatoriais fracionados de dois níveis: a ideia geral</a></li>
<li class="chapter" data-level="6.6" data-path="rumo-superficie-resposta.html"><a href="rumo-superficie-resposta.html"><i class="fa fa-check"></i><b>6.6</b> Rumo à otimização: superfície de resposta</a></li>
<li class="chapter" data-level="6.7" data-path="resumo-do-capítulo-5.html"><a href="resumo-do-capítulo-5.html"><i class="fa fa-check"></i><b>6.7</b> Resumo do capítulo</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="superficie-resposta-cap.html"><a href="superficie-resposta-cap.html"><i class="fa fa-check"></i><b>7</b> Metodologia de superfície de resposta</a>
<ul>
<li class="chapter" data-level="7.1" data-path="superficie-resposta.html"><a href="superficie-resposta.html"><i class="fa fa-check"></i><b>7.1</b> Introdução à superfície de resposta</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="superficie-resposta.html"><a href="superficie-resposta.html#ponto-estacionario"><i class="fa fa-check"></i><b>7.1.1</b> Classificando o ponto estacionário: gradiente e Hessiana</a></li>
<li class="chapter" data-level="7.1.2" data-path="superficie-resposta.html"><a href="superficie-resposta.html#analise-canonica"><i class="fa fa-check"></i><b>7.1.2</b> Análise canônica: além de classificar, descrever a forma da superfície</a></li>
<li class="chapter" data-level="7.1.3" data-path="superficie-resposta.html"><a href="superficie-resposta.html#ridge-analysis"><i class="fa fa-check"></i><b>7.1.3</b> Análise de ridge: otimizando dentro de um raio fixo da região experimental</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="steepest-ascent.html"><a href="steepest-ascent.html"><i class="fa fa-check"></i><b>7.2</b> O caminho de máxima inclinação: de um fatorial inicial até a região do ótimo</a></li>
<li class="chapter" data-level="7.3" data-path="ccd.html"><a href="ccd.html"><i class="fa fa-check"></i><b>7.3</b> Delineamento composto central (CCD)</a></li>
<li class="chapter" data-level="7.4" data-path="desejabilidade.html"><a href="desejabilidade.html"><i class="fa fa-check"></i><b>7.4</b> Otimização de múltiplas respostas: funções de desejabilidade</a></li>
<li class="chapter" data-level="7.5" data-path="desenho-robusto.html"><a href="desenho-robusto.html"><i class="fa fa-check"></i><b>7.5</b> Desenho robusto: otimizando a média e a variância ao mesmo tempo</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="desenho-robusto.html"><a href="desenho-robusto.html#a-proposta-original-de-taguchi-e-por-que-ela-foi-revista"><i class="fa fa-check"></i><b>7.5.1</b> A proposta original de Taguchi, e por que ela foi revista</a></li>
<li class="chapter" data-level="7.5.2" data-path="desenho-robusto.html"><a href="desenho-robusto.html#a-alternativa-duas-superfícies-de-resposta-uma-única-maquinaria"><i class="fa fa-check"></i><b>7.5.2</b> A alternativa: duas superfícies de resposta, uma única maquinaria</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="resumo-do-capítulo-6.html"><a href="resumo-do-capítulo-6.html"><i class="fa fa-check"></i><b>7.6</b> Resumo do capítulo</a></li>
<li class="chapter" data-level="7.7" data-path="fim-do-programa-do-semestre.html"><a href="fim-do-programa-do-semestre.html"><i class="fa fa-check"></i><b>7.7</b> Fim do programa do semestre</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ab-bandits.html"><a href="ab-bandits.html"><i class="fa fa-check"></i><b>8</b> Experimentação em produtos digitais: testes A/B e bandits</a>
<ul>
<li class="chapter" data-level="8.1" data-path="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><i class="fa fa-check"></i><b>8.1</b> Parte I — Testes A/B como delineamento completamente aleatorizado</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#ab-e-dca"><i class="fa fa-check"></i><b>8.1.1</b> Um teste A/B é um delineamento completamente aleatorizado</a></li>
<li class="chapter" data-level="8.1.2" data-path="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#ab-dificuldades"><i class="fa fa-check"></i><b>8.1.2</b> Por que testes A/B em produtos digitais são estatisticamente difíceis</a></li>
<li class="chapter" data-level="8.1.3" data-path="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#ab-peeking"><i class="fa fa-check"></i><b>8.1.3</b> O problema do “peeking”</a></li>
<li class="chapter" data-level="8.1.4" data-path="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#ab-winners-curse"><i class="fa fa-check"></i><b>8.1.4</b> Vício do vencedor (<em>winner’s curse</em>)</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><i class="fa fa-check"></i><b>8.2</b> Parte II — Bandits: quando explorar e quando explotar</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html#bandits-motivacao"><i class="fa fa-check"></i><b>8.2.1</b> Exploração, explotação e a definição de arrependimento (<em>regret</em>)</a></li>
<li class="chapter" data-level="8.2.2" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html#bandits-ucb1"><i class="fa fa-check"></i><b>8.2.2</b> Upper Confidence Bound (UCB1): otimismo perante a incerteza</a></li>
<li class="chapter" data-level="8.2.3" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html#bandits-thompson"><i class="fa fa-check"></i><b>8.2.3</b> Thompson sampling: uma solução bayesiana</a></li>
<li class="chapter" data-level="8.2.4" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html#bandits-vs-ab"><i class="fa fa-check"></i><b>8.2.4</b> Horizonte fixo ou bandit?</a></li>
<li class="chapter" data-level="8.2.5" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html#outros-topicos"><i class="fa fa-check"></i><b>8.2.5</b> Outros tópicos modernos</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="resumo-do-capítulo-7.html"><a href="resumo-do-capítulo-7.html"><i class="fa fa-check"></i><b>8.3</b> Resumo do capítulo</a></li>
<li class="chapter" data-level="8.4" data-path="encerrando-o-livro.html"><a href="encerrando-o-livro.html"><i class="fa fa-check"></i><b>8.4</b> Encerrando o livro</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://raydonal.github.io/matd48/" target="_blank">MATD48 — Página do curso</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Planejamento e Análise de Experimentos</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="split-plot" class="section level2 hasAnchor" number="4.6">
<h2><span class="header-section-number">4.6</span> Parcelas subdivididas (<em>split-plot</em>)<a href="split-plot.html#split-plot" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="caixa-discussao"><strong>Além do programa do semestre</strong> — esta seção não
corresponde a nenhuma das Aulas 09–11: é material extra, na mesma linha do Capítulo 8, que estende
o Capítulo 4 além do que cabe em três aulas.</div>
<p>Todas as seções anteriores deste capítulo assumem que <strong>um único</strong> mecanismo de aleatorização
atribui tratamentos a unidades experimentais. Em muitos experimentos de campo — a origem histórica
deste delineamento, em Rothamsted, nos anos 1920 e 1930 <span class="citation">(<a href="#ref-yates1937design">Yates, 1937</a>)</span> —, isso é
logisticamente inviável: certos fatores só podem ser aplicados a <strong>parcelas grandes</strong> (um sistema
de irrigação cobre uma faixa inteira de terreno; não há como irrigar diferentemente cada metro
quadrado), enquanto outros fatores variam livremente em <strong>parcelas pequenas</strong> dentro de cada
parcela grande (a variedade plantada pode mudar a cada poucos metros). O delineamento em
<strong>parcelas subdivididas</strong> (<em>split-plot</em>) formaliza exatamente essa restrição prática — não é uma
escolha de conveniência estatística, é a estrutura que o próprio processo físico de aleatorização
impõe <span class="citation">(<a href="#ref-montgomery2017design">Montgomery, 2017</a>)</span>.</p>
<div class="caixa-aplicacao">
<strong>Aplicação — Agricultura: irrigação e variedade na produção de sorgo</strong><br>
Um experimento compara 3 métodos de irrigação e 4 variedades de sorgo. O terreno é dividido em
4 blocos (homogêneos internamente); dentro de cada bloco, o método de irrigação é sorteado a
<strong>3 parcelas principais</strong> — faixas grandes de terra, porque cada sistema de irrigação
exige uma faixa contígua. Cada parcela principal é então subdividida em <strong>4 subparcelas</strong>,
e a variedade é sorteada às subparcelas dentro de cada parcela principal. Produção (kg/parcela) é
medida em cada subparcela.
</div>
<div id="dois-erros-experimentais-não-um" class="section level3 hasAnchor" number="4.6.1">
<h3><span class="header-section-number">4.6.1</span> Dois erros experimentais, não um<a href="split-plot.html#dois-erros-experimentais-não-um" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A restrição prática acima tem uma consequência estatística direta: <strong>há dois processos de
aleatorização independentes</strong>, um em cada nível (aleatorizar irrigação às parcelas principais
dentro de cada bloco; aleatorizar variedade às subparcelas dentro de cada parcela principal) — e
cada aleatorização gera seu próprio erro experimental. O modelo precisa de <strong>dois</strong> termos de erro
distintos, não um:</p>
<p><span class="math display">\[
Y_{ijk} = \mu + \rho_i + \alpha_j + \underbrace{\delta_{ij}}_{\text{erro da parcela principal}}
+ \beta_k + (\alpha\beta)_{jk} + \underbrace{\varepsilon_{ijk}}_{\text{erro da subparcela}},
\]</span></p>
<p>com <span class="math inline">\(i=1,\ldots,r\)</span> blocos, <span class="math inline">\(j=1,\ldots,a\)</span> níveis do fator de parcela principal (irrigação),
<span class="math inline">\(k=1,\ldots,b\)</span> níveis do fator de subparcela (variedade), <span class="math inline">\(\delta_{ij}\overset{iid}\sim N(0,\sigma^2_\delta)\)</span> o erro da parcela principal (a variação entre parcelas principais dentro do
mesmo bloco, não explicada por irrigação) e <span class="math inline">\(\varepsilon_{ijk}\overset{iid}\sim N(0,\sigma^2_\varepsilon)\)</span>
o erro da subparcela (a variação entre subparcelas dentro da mesma parcela principal), independente
de <span class="math inline">\(\delta_{ij}\)</span>. <span class="math inline">\(\rho_i\)</span> (bloco) e <span class="math inline">\(\alpha_j\)</span> (irrigação) são efeitos fixos sujeitos às
restrições usuais de soma zero, assim como <span class="math inline">\(\beta_k\)</span> (variedade) e <span class="math inline">\((\alpha\beta)_{jk}\)</span>
(interação).</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="split-plot.html#cb215-1" tabindex="-1"></a>nos_sp <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb215-2"><a href="split-plot.html#cb215-2" tabindex="-1"></a>  <span class="at">termo   =</span> <span class="fu">c</span>(<span class="st">&quot;Média&quot;</span>, <span class="st">&quot;Bloco&quot;</span>, <span class="st">&quot;Irrigação&quot;</span>, <span class="st">&quot;Variedade&quot;</span>, <span class="st">&quot;Erro(a)</span><span class="sc">\n</span><span class="st">(parcela principal)&quot;</span>,</span>
<span id="cb215-3"><a href="split-plot.html#cb215-3" tabindex="-1"></a>              <span class="st">&quot;Irrigação</span><span class="sc">\n</span><span class="st">×Variedade&quot;</span>, <span class="st">&quot;Erro(b)</span><span class="sc">\n</span><span class="st">(subparcela)&quot;</span>),</span>
<span id="cb215-4"><a href="split-plot.html#cb215-4" tabindex="-1"></a>  <span class="at">classes =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">4</span><span class="sc">*</span><span class="dv">3</span>, <span class="dv">3</span><span class="sc">*</span><span class="dv">4</span>, <span class="dv">4</span><span class="sc">*</span><span class="dv">3</span><span class="sc">*</span><span class="dv">4</span>)</span>
<span id="cb215-5"><a href="split-plot.html#cb215-5" tabindex="-1"></a>)</span>
<span id="cb215-6"><a href="split-plot.html#cb215-6" tabindex="-1"></a>arestas_sp <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb215-7"><a href="split-plot.html#cb215-7" tabindex="-1"></a>  <span class="at">de   =</span> <span class="fu">c</span>(<span class="st">&quot;Média&quot;</span>, <span class="st">&quot;Média&quot;</span>, <span class="st">&quot;Média&quot;</span>, <span class="st">&quot;Bloco&quot;</span>, <span class="st">&quot;Irrigação&quot;</span>, <span class="st">&quot;Irrigação&quot;</span>, <span class="st">&quot;Variedade&quot;</span>,</span>
<span id="cb215-8"><a href="split-plot.html#cb215-8" tabindex="-1"></a>           <span class="st">&quot;Erro(a)</span><span class="sc">\n</span><span class="st">(parcela principal)&quot;</span>, <span class="st">&quot;Irrigação</span><span class="sc">\n</span><span class="st">×Variedade&quot;</span>),</span>
<span id="cb215-9"><a href="split-plot.html#cb215-9" tabindex="-1"></a>  <span class="at">para =</span> <span class="fu">c</span>(<span class="st">&quot;Bloco&quot;</span>, <span class="st">&quot;Irrigação&quot;</span>, <span class="st">&quot;Variedade&quot;</span>, <span class="st">&quot;Erro(a)</span><span class="sc">\n</span><span class="st">(parcela principal)&quot;</span>,</span>
<span id="cb215-10"><a href="split-plot.html#cb215-10" tabindex="-1"></a>           <span class="st">&quot;Erro(a)</span><span class="sc">\n</span><span class="st">(parcela principal)&quot;</span>, <span class="st">&quot;Irrigação</span><span class="sc">\n</span><span class="st">×Variedade&quot;</span>,</span>
<span id="cb215-11"><a href="split-plot.html#cb215-11" tabindex="-1"></a>           <span class="st">&quot;Irrigação</span><span class="sc">\n</span><span class="st">×Variedade&quot;</span>, <span class="st">&quot;Erro(b)</span><span class="sc">\n</span><span class="st">(subparcela)&quot;</span>, <span class="st">&quot;Erro(b)</span><span class="sc">\n</span><span class="st">(subparcela)&quot;</span>)</span>
<span id="cb215-12"><a href="split-plot.html#cb215-12" tabindex="-1"></a>)</span>
<span id="cb215-13"><a href="split-plot.html#cb215-13" tabindex="-1"></a></span>
<span id="cb215-14"><a href="split-plot.html#cb215-14" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(</span>
<span id="cb215-15"><a href="split-plot.html#cb215-15" tabindex="-1"></a>  <span class="fu">hasse_svg</span>(nos_sp, arestas_sp,</span>
<span id="cb215-16"><a href="split-plot.html#cb215-16" tabindex="-1"></a>            <span class="at">arquivo =</span> <span class="st">&quot;figuras/hasse/split-plot.svg&quot;</span>,</span>
<span id="cb215-17"><a href="split-plot.html#cb215-17" tabindex="-1"></a>            <span class="at">titulo  =</span> <span class="st">&quot;Split-plot: r=4, a=3, b=4 (N=48)&quot;</span>,</span>
<span id="cb215-18"><a href="split-plot.html#cb215-18" tabindex="-1"></a>            <span class="at">tamanho =</span> <span class="fu">c</span>(<span class="fl">5.5</span>, <span class="dv">4</span>))</span>
<span id="cb215-19"><a href="split-plot.html#cb215-19" tabindex="-1"></a>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:hasse-split-plot"></span>
<img src="figuras/hasse/split-plot.svg" alt="Diagrama de Hasse do split-plot: r=4 blocos, a=3 métodos de irrigação (parcela principal), b=4 variedades (subparcela), N=48. Note os DOIS nós de erro -- Erro(a), que fecha o estrato da parcela principal, e Erro(b), que fecha o estrato da subparcela -- em vez do único nó de Erro do DBCA (Figura anterior)." width="85%" />
<p class="caption">
Figura 4.4: Diagrama de Hasse do split-plot: r=4 blocos, a=3 métodos de irrigação (parcela principal), b=4 variedades (subparcela), N=48. Note os DOIS nós de erro – Erro(a), que fecha o estrato da parcela principal, e Erro(b), que fecha o estrato da subparcela – em vez do único nó de Erro do DBCA (Figura anterior).
</p>
</div>
<p>A soma de todos os <span class="math inline">\(gl\)</span> é <span class="math inline">\(1+3+2+3+6+6+27=48=N\)</span> — dois nós de erro em vez de um, exatamente porque
há dois estratos de aleatorização, cada um com sua própria variação residual. <span class="math inline">\(gl(\text{Erro(a)}) = ra - 1 - gl(\text{Bloco}) - gl(\text{Irrigação}) = 12-1-3-2=6=(r-1)(a-1)\)</span>; <span class="math inline">\(gl(\text{Erro(b)}) = rab - [\text{soma dos } gl \text{ de todos os outros seis nós}] = 48-21=27=a(r-1)(b-1)\)</span>.</p>
</div>
<div id="por-que-o-teste-de-irrigação-usa-um-erro-diferente-do-teste-de-variedade" class="section level3 hasAnchor" number="4.6.2">
<h3><span class="header-section-number">4.6.2</span> Por que o teste de irrigação usa um erro diferente do teste de variedade<a href="split-plot.html#por-que-o-teste-de-irrigação-usa-um-erro-diferente-do-teste-de-variedade" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A esperança dos quadrados médios torna explícito por que dois erros são necessários, e não apenas
uma curiosidade algébrica do diagrama:</p>
<p><span class="math display">\[
\mathbb E[QM_{\text{Erro(a)}}] = \sigma^2_\varepsilon + b\,\sigma^2_\delta, \qquad
\mathbb E[QM_{\text{Irrigação}}] = \sigma^2_\varepsilon + b\,\sigma^2_\delta +
\frac{rb}{a-1}\sum_j \alpha_j^2,
\]</span>
<span class="math display">\[
\mathbb E[QM_{\text{Erro(b)}}] = \sigma^2_\varepsilon, \qquad
\mathbb E[QM_{\text{Variedade}}] = \sigma^2_\varepsilon + \frac{ra}{b-1}\sum_k \beta_k^2.
\]</span></p>
<p>O termo <span class="math inline">\(b\,\sigma^2_\delta\)</span> aparece em <span class="math inline">\(QM_{\text{Irrigação}}\)</span> <strong>e</strong> em <span class="math inline">\(QM_{\text{Erro(a)}}\)</span>, mas
<strong>não</strong> em <span class="math inline">\(QM_{\text{Erro(b)}}\)</span>: por isso o teste de irrigação precisa usar
<span class="math inline">\(F=QM_{\text{Irrigação}}/QM_{\text{Erro(a)}}\)</span>, nunca <span class="math inline">\(QM_{\text{Erro(b)}}\)</span> — usar o erro errado no
denominador (um engano comum, fácil de cometer se o código não especificar a estrutura de erro)
infla artificialmente a estatística <span class="math inline">\(F\)</span> do fator de parcela principal, porque <span class="math inline">\(QM_{\text{Erro(b)}}\)</span>
não contém a variação entre parcelas principais que também afeta <span class="math inline">\(QM_{\text{Irrigação}}\)</span>. O teste
de variedade (e da interação) usa corretamente <span class="math inline">\(QM_{\text{Erro(b)}}\)</span>, sem <span class="math inline">\(\sigma^2_\delta\)</span> em
nenhum dos dois lados da razão.</p>
<p>Consequência prática, não só teórica: como <span class="math inline">\(\sigma^2_\delta\)</span> tipicamente excede <span class="math inline">\(\sigma^2_\varepsilon\)</span>
(parcelas principais variam mais entre si do que subparcelas dentro da mesma parcela principal), o
fator de parcela principal é estimado com <strong>menos</strong> precisão que o fator de subparcela — mesmo
com o mesmo número de observações. É um trade-off deliberado do delineamento: ganha-se viabilidade
logística ao custo de precisão no fator que a logística obrigou a ficar na parcela principal.</p>
<div class="caixa-r"><strong>Uso do R</strong> — split-plot com <code>aov(..., Error(bloco/irrigacao))</code></div>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb216-1"><a href="split-plot.html#cb216-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">48</span>)</span>
<span id="cb216-2"><a href="split-plot.html#cb216-2" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="dv">4</span>; a <span class="ot">&lt;-</span> <span class="dv">3</span>; b <span class="ot">&lt;-</span> <span class="dv">4</span></span>
<span id="cb216-3"><a href="split-plot.html#cb216-3" tabindex="-1"></a>dados_sp <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(<span class="at">variedade =</span> <span class="fu">factor</span>(<span class="dv">1</span><span class="sc">:</span>b), <span class="at">irrigacao =</span> <span class="fu">factor</span>(<span class="dv">1</span><span class="sc">:</span>a), <span class="at">bloco =</span> <span class="fu">factor</span>(<span class="dv">1</span><span class="sc">:</span>r))</span>
<span id="cb216-4"><a href="split-plot.html#cb216-4" tabindex="-1"></a></span>
<span id="cb216-5"><a href="split-plot.html#cb216-5" tabindex="-1"></a>efeito_irrig <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">3</span>, <span class="dv">6</span>)[dados_sp<span class="sc">$</span>irrigacao]</span>
<span id="cb216-6"><a href="split-plot.html#cb216-6" tabindex="-1"></a>efeito_var   <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">4</span>)[dados_sp<span class="sc">$</span>variedade]</span>
<span id="cb216-7"><a href="split-plot.html#cb216-7" tabindex="-1"></a>erro_a <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(r <span class="sc">*</span> a, <span class="dv">0</span>, <span class="dv">2</span>)[<span class="fu">interaction</span>(dados_sp<span class="sc">$</span>bloco, dados_sp<span class="sc">$</span>irrigacao, <span class="at">drop =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> <span class="fu">as.integer</span>()]</span>
<span id="cb216-8"><a href="split-plot.html#cb216-8" tabindex="-1"></a></span>
<span id="cb216-9"><a href="split-plot.html#cb216-9" tabindex="-1"></a>dados_sp<span class="sc">$</span>producao <span class="ot">&lt;-</span> <span class="dv">20</span> <span class="sc">+</span> efeito_irrig <span class="sc">+</span> efeito_var <span class="sc">+</span> erro_a <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="fu">nrow</span>(dados_sp), <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb216-10"><a href="split-plot.html#cb216-10" tabindex="-1"></a></span>
<span id="cb216-11"><a href="split-plot.html#cb216-11" tabindex="-1"></a>mod_sp <span class="ot">&lt;-</span> <span class="fu">aov</span>(producao <span class="sc">~</span> irrigacao <span class="sc">*</span> variedade <span class="sc">+</span> <span class="fu">Error</span>(bloco<span class="sc">/</span>irrigacao), <span class="at">data =</span> dados_sp)</span>
<span id="cb216-12"><a href="split-plot.html#cb216-12" tabindex="-1"></a><span class="fu">summary</span>(mod_sp)</span></code></pre></div>
<pre><code>## 
## Error: bloco
##           Df Sum Sq Mean Sq F value Pr(&gt;F)
## Residuals  3  121.5   40.49               
## 
## Error: bloco:irrigacao
##           Df Sum Sq Mean Sq F value  Pr(&gt;F)   
## irrigacao  2  545.4  272.68   13.26 0.00628 **
## Residuals  6  123.4   20.57                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Error: Within
##                     Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## variedade            3  94.19  31.398  31.329 6.1e-09 ***
## irrigacao:variedade  6   1.25   0.208   0.208   0.971    
## Residuals           27  27.06   1.002                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Os graus de liberdade batem exatamente com o diagrama de Hasse acima: 3 (bloco), 2 e 6
(irrigação e seu erro, no estrato <code>bloco:irrigacao</code>), e 3, 6, 27 (variedade, interação e o erro de
subparcela, no estrato <code>Within</code>) — o <code>Error(bloco/irrigacao)</code> do R <strong>é</strong> a declaração explícita dos
dois estratos de aleatorização do diagrama, não uma opção de sintaxe arbitrária.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:split-plot-plot"></span>
<img src="04-blocos_files/figure-html/split-plot-plot-1.png" alt="Produção de sorgo por variedade, separada por método de irrigação. Retas quase paralelas entre os três painéis indicam ausência de interação irrigação-variedade -- consistente com o p-valor não significativo da interação na tabela acima." width="75%" />
<p class="caption">
Figura 4.5: Produção de sorgo por variedade, separada por método de irrigação. Retas quase paralelas entre os três painéis indicam ausência de interação irrigação-variedade – consistente com o p-valor não significativo da interação na tabela acima.
</p>
</div>
<p>Neste conjunto de dados simulado, irrigação é significativa
(<span class="math inline">\(F_{2,6}=13.3\)</span>, <span class="math inline">\(p=0.006\)</span>) mas testada com apenas 6 gl de erro;
variedade é fortemente significativa (<span class="math inline">\(F_{3,27}=31.3\)</span>,
<span class="math inline">\(p&lt;0{,}001\)</span>), testada com 27 gl de erro —
precisão bem maior, exatamente o padrão que a análise de <span class="math inline">\(\mathbb E[QM]\)</span> previu. A interação não é
significativa (<span class="math inline">\(p=0.97\)</span>), visível no gráfico como retas aproximadamente paralelas
entre os três níveis de irrigação.</p>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" line-spacing="2">
<div id="ref-montgomery2017design" class="csl-entry">
Montgomery, D. C. (2017). <em>Design and analysis of experiments</em> (9th ed.). John Wiley &amp; Sons.
</div>
<div id="ref-yates1937design" class="csl-entry">
Yates, F. (1937). <em>The design and analysis of factorial experiments</em>. Imperial Bureau of Soil Science.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="quadrado-greco-latino.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="resumo-do-capítulo-3.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": false,
    "twitter": false,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
