<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7.1 Introdução à superfície de resposta | Planejamento e Análise de Experimentos</title>
  <meta name="description" content="Livro-texto de apoio à disciplina MATD48 (Planejamento de Experimentos A), Departamento de Estatística, UFBA." />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="7.1 Introdução à superfície de resposta | Planejamento e Análise de Experimentos" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Livro-texto de apoio à disciplina MATD48 (Planejamento de Experimentos A), Departamento de Estatística, UFBA." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7.1 Introdução à superfície de resposta | Planejamento e Análise de Experimentos" />
  
  <meta name="twitter:description" content="Livro-texto de apoio à disciplina MATD48 (Planejamento de Experimentos A), Departamento de Estatística, UFBA." />
  

<meta name="author" content="Raydonal Ospina Martínez" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="superficie-resposta-cap.html"/>
<link rel="next" href="steepest-ascent.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./"><strong>Planejamento e Análise de Experimentos</strong></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefácio</a>
<ul>
<li class="chapter" data-level="" data-path="para-quem-é-este-livro.html"><a href="para-quem-é-este-livro.html"><i class="fa fa-check"></i>Para quem é este livro</a></li>
<li class="chapter" data-level="" data-path="como-o-material-está-organizado.html"><a href="como-o-material-está-organizado.html"><i class="fa fa-check"></i>Como o material está organizado</a></li>
<li class="chapter" data-level="" data-path="convenções-tipográficas.html"><a href="convenções-tipográficas.html"><i class="fa fa-check"></i>Convenções tipográficas</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="principios.html"><a href="principios.html"><i class="fa fa-check"></i><b>1</b> Princípios do delineamento de experimentos</a>
<ul>
<li class="chapter" data-level="1.1" data-path="metodo-cientifico.html"><a href="metodo-cientifico.html"><i class="fa fa-check"></i><b>1.1</b> O método científico e o papel do delineamento experimental</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="metodo-cientifico.html"><a href="metodo-cientifico.html#o-ciclo-empírico-de-observação-a-hipótese-testável"><i class="fa fa-check"></i><b>1.1.1</b> O ciclo empírico: de observação a hipótese testável</a></li>
<li class="chapter" data-level="1.1.2" data-path="metodo-cientifico.html"><a href="metodo-cientifico.html#observação-vs.-experimentação-por-que-controlado-importa"><i class="fa fa-check"></i><b>1.1.2</b> Observação vs. experimentação: por que “controlado” importa</a></li>
<li class="chapter" data-level="1.1.3" data-path="metodo-cientifico.html"><a href="metodo-cientifico.html#uma-nota-histórica-quantificar-controlar-e-só-depois-formalizar"><i class="fa fa-check"></i><b>1.1.3</b> Uma nota histórica: quantificar, controlar, e só depois formalizar</a></li>
<li class="chapter" data-level="1.1.4" data-path="metodo-cientifico.html"><a href="metodo-cientifico.html#confusão-confounding-o-problema-que-a-aleatorização-resolve"><i class="fa fa-check"></i><b>1.1.4</b> Confusão (<em>confounding</em>): o problema que a aleatorização resolve</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="unidades.html"><a href="unidades.html"><i class="fa fa-check"></i><b>1.2</b> Unidades experimentais e unidades amostrais</a></li>
<li class="chapter" data-level="1.3" data-path="fontes-variacao.html"><a href="fontes-variacao.html"><i class="fa fa-check"></i><b>1.3</b> Fontes de variação</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="fontes-variacao.html"><a href="fontes-variacao.html#aditividade-aleatorizacao"><i class="fa fa-check"></i><b>1.3.1</b> Por que essa decomposição força a forma aditiva do modelo</a></li>
<li class="chapter" data-level="1.3.2" data-path="fontes-variacao.html"><a href="fontes-variacao.html#fatores-niveis"><i class="fa fa-check"></i><b>1.3.2</b> Fatores e níveis</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="tres-aspectos.html"><a href="tres-aspectos.html"><i class="fa fa-check"></i><b>1.4</b> Os três aspectos do delineamento experimental</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="tres-aspectos.html"><a href="tres-aspectos.html#repetição-replicação"><i class="fa fa-check"></i><b>1.4.1</b> Repetição (replicação)</a></li>
<li class="chapter" data-level="1.4.2" data-path="tres-aspectos.html"><a href="tres-aspectos.html#aleatorização"><i class="fa fa-check"></i><b>1.4.2</b> Aleatorização</a></li>
<li class="chapter" data-level="1.4.3" data-path="tres-aspectos.html"><a href="tres-aspectos.html#neyman-rubin"><i class="fa fa-check"></i><b>1.4.3</b> Por que a aleatorização funciona: o modelo de resultados potenciais</a></li>
<li class="chapter" data-level="1.4.4" data-path="tres-aspectos.html"><a href="tres-aspectos.html#ate-binario"><i class="fa fa-check"></i><b>1.4.4</b> Um terceiro domínio: resultados potenciais binários em um teste A/B</a></li>
<li class="chapter" data-level="1.4.5" data-path="tres-aspectos.html"><a href="tres-aspectos.html#validade-externa"><i class="fa fa-check"></i><b>1.4.5</b> Validade interna e validade externa</a></li>
<li class="chapter" data-level="1.4.6" data-path="tres-aspectos.html"><a href="tres-aspectos.html#amostragem-e-desenho"><i class="fa fa-check"></i><b>1.4.6</b> O elo entre amostragem e planejamento de experimentos</a></li>
<li class="chapter" data-level="1.4.7" data-path="tres-aspectos.html"><a href="tres-aspectos.html#controle-local-blocagem"><i class="fa fa-check"></i><b>1.4.7</b> Controle local (blocagem)</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="resumo-do-capítulo.html"><a href="resumo-do-capítulo.html"><i class="fa fa-check"></i><b>1.5</b> Resumo do capítulo</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="modelos-lineares.html"><a href="modelos-lineares.html"><i class="fa fa-check"></i><b>2</b> Introdução aos modelos lineares</a>
<ul>
<li class="chapter" data-level="2.1" data-path="populacao-conceitual.html"><a href="populacao-conceitual.html"><i class="fa fa-check"></i><b>2.1</b> Da população conceitual de respostas ao modelo linear</a></li>
<li class="chapter" data-level="2.2" data-path="hasse.html"><a href="hasse.html"><i class="fa fa-check"></i><b>2.2</b> Diagramas de Hasse: a estrutura do delineamento antes da álgebra</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="hasse.html"><a href="hasse.html#o-diagrama-como-um-retrato-da-estrutura-do-dado"><i class="fa fa-check"></i><b>2.2.1</b> O diagrama como um retrato da estrutura do dado</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="modelo-geral.html"><a href="modelo-geral.html"><i class="fa fa-check"></i><b>2.3</b> O modelo linear geral</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="modelo-geral.html"><a href="modelo-geral.html#porque-xbeta-mais-erro"><i class="fa fa-check"></i><b>2.3.1</b> Por que esta é a forma natural, não arbitrária, do modelo</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="minimos-quadrados.html"><a href="minimos-quadrados.html"><i class="fa fa-check"></i><b>2.4</b> Estimação por mínimos quadrados</a></li>
<li class="chapter" data-level="2.5" data-path="estimabilidade.html"><a href="estimabilidade.html"><i class="fa fa-check"></i><b>2.5</b> Estimabilidade de funções lineares dos parâmetros</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="estimabilidade.html"><a href="estimabilidade.html#svd-moore-penrose"><i class="fa fa-check"></i><b>2.5.1</b> A pseudoinversa de Moore-Penrose via decomposição em valores singulares</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="gauss-markov.html"><a href="gauss-markov.html"><i class="fa fa-check"></i><b>2.6</b> O teorema de Gauss-Markov e o BLUE</a></li>
<li class="chapter" data-level="2.7" data-path="matriz-projecao.html"><a href="matriz-projecao.html"><i class="fa fa-check"></i><b>2.7</b> A matriz de projeção</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="matriz-projecao.html"><a href="matriz-projecao.html#soma-quadrados-total"><i class="fa fa-check"></i><b>2.7.1</b> A soma de quadrados total como forma quadrática</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="modelo-particionado.html"><a href="modelo-particionado.html"><i class="fa fa-check"></i><b>2.8</b> O modelo linear particionado</a></li>
<li class="chapter" data-level="2.9" data-path="fwl.html"><a href="fwl.html"><i class="fa fa-check"></i><b>2.9</b> O teorema de Frisch-Waugh-Lovell</a>
<ul>
<li class="chapter" data-level="2.9.1" data-path="fwl.html"><a href="fwl.html#fwl-experimentos"><i class="fa fa-check"></i><b>2.9.1</b> Conexão com planejamento de experimentos: por que a ANCOVA funciona</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="formas-quadraticas.html"><a href="formas-quadraticas.html"><i class="fa fa-check"></i><b>2.10</b> Distribuição de formas lineares e quadráticas</a></li>
<li class="chapter" data-level="2.11" data-path="resumo-do-capítulo-1.html"><a href="resumo-do-capítulo-1.html"><i class="fa fa-check"></i><b>2.11</b> Resumo do capítulo</a>
<ul>
<li class="chapter" data-level="" data-path="resumo-do-capítulo-1.html"><a href="resumo-do-capítulo-1.html#uma-nota-sobre-notação-de-beta-genérico-a-tau-e-depois-a-alphabetagammadots"><i class="fa fa-check"></i>Uma nota sobre notação: de <span class="math inline">\(\beta\)</span> genérico a <span class="math inline">\(\tau\)</span>, e depois a <span class="math inline">\(\alpha,\beta,\gamma,\dots\)</span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="dca.html"><a href="dca.html"><i class="fa fa-check"></i><b>3</b> Delineamento completamente aleatorizado</a>
<ul>
<li class="chapter" data-level="3.1" data-path="principios-aleatorizacao.html"><a href="principios-aleatorizacao.html"><i class="fa fa-check"></i><b>3.1</b> Princípios de aleatorização: a ideia de um teste de aleatorização</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="principios-aleatorizacao.html"><a href="principios-aleatorizacao.html#randomizacao-df-f"><i class="fa fa-check"></i><b>3.1.1</b> De onde vêm os graus de liberdade <span class="math inline">\((2,33)\)</span>: a ponte entre aleatorização, variância decomposta e <span class="math inline">\(F\)</span></a></li>
<li class="chapter" data-level="3.1.2" data-path="principios-aleatorizacao.html"><a href="principios-aleatorizacao.html#modelo-deduzido"><i class="fa fa-check"></i><b>3.1.2</b> O modelo linear deduzido da aleatorização</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="dca-uma-via.html"><a href="dca-uma-via.html"><i class="fa fa-check"></i><b>3.2</b> O delineamento completamente aleatorizado a uma via de classificação</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="dca-uma-via.html"><a href="dca-uma-via.html#modelo-dca"><i class="fa fa-check"></i><b>3.2.1</b> O modelo estatístico</a></li>
<li class="chapter" data-level="3.2.2" data-path="dca-uma-via.html"><a href="dca-uma-via.html#matricial-dca"><i class="fa fa-check"></i><b>3.2.2</b> Notação matricial: o DCA como caso particular do modelo linear geral</a></li>
<li class="chapter" data-level="3.2.3" data-path="dca-uma-via.html"><a href="dca-uma-via.html#potencial-causal"><i class="fa fa-check"></i><b>3.2.3</b> Resultados potenciais e o estimando causal</a></li>
<li class="chapter" data-level="3.2.4" data-path="dca-uma-via.html"><a href="dca-uma-via.html#ic-dca"><i class="fa fa-check"></i><b>3.2.4</b> Estimação e intervalos de confiança</a></li>
<li class="chapter" data-level="3.2.5" data-path="dca-uma-via.html"><a href="dca-uma-via.html#anova-dca"><i class="fa fa-check"></i><b>3.2.5</b> A tabela de análise de variância</a></li>
<li class="chapter" data-level="3.2.6" data-path="dca-uma-via.html"><a href="dca-uma-via.html#numero-replicas-dca"><i class="fa fa-check"></i><b>3.2.6</b> Número de réplicas necessário</a></li>
<li class="chapter" data-level="3.2.7" data-path="dca-uma-via.html"><a href="dca-uma-via.html#dca-feijao"><i class="fa fa-check"></i><b>3.2.7</b> Um segundo exemplo, com dado real: fertilizante em feijão</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="dca-submuestreo.html"><a href="dca-submuestreo.html"><i class="fa fa-check"></i><b>3.3</b> Submuestreo em um DCA</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="dca-submuestreo.html"><a href="dca-submuestreo.html#modelo-submuestreo"><i class="fa fa-check"></i><b>3.3.1</b> O modelo com dois níveis de erro</a></li>
<li class="chapter" data-level="3.3.2" data-path="dca-submuestreo.html"><a href="dca-submuestreo.html#o-diagrama-de-hasse-do-submuestreo-aninhamento-em-duas-camadas"><i class="fa fa-check"></i><b>3.3.2</b> O diagrama de Hasse do submuestreo: aninhamento em duas camadas</a></li>
<li class="chapter" data-level="3.3.3" data-path="dca-submuestreo.html"><a href="dca-submuestreo.html#anova-submuestreo"><i class="fa fa-check"></i><b>3.3.3</b> ANOVA com submuestreo</a></li>
<li class="chapter" data-level="3.3.4" data-path="dca-submuestreo.html"><a href="dca-submuestreo.html#amostra-submuestreo"><i class="fa fa-check"></i><b>3.3.4</b> Tamanho de amostra com submuestreo</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="dca-efeitos-aleatorios.html"><a href="dca-efeitos-aleatorios.html"><i class="fa fa-check"></i><b>3.4</b> O modelo de efeitos aleatórios</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="dca-efeitos-aleatorios.html"><a href="dca-efeitos-aleatorios.html#modelo-aleatorio"><i class="fa fa-check"></i><b>3.4.1</b> Quando os tratamentos são uma amostra aleatória</a></li>
<li class="chapter" data-level="3.4.2" data-path="dca-efeitos-aleatorios.html"><a href="dca-efeitos-aleatorios.html#anova-aleatorio"><i class="fa fa-check"></i><b>3.4.2</b> ANOVA e componentes de variância</a></li>
<li class="chapter" data-level="3.4.3" data-path="dca-efeitos-aleatorios.html"><a href="dca-efeitos-aleatorios.html#amostra-aleatorio"><i class="fa fa-check"></i><b>3.4.3</b> Tamanho de amostra no modelo de efeitos aleatórios</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="dca-pressupostos.html"><a href="dca-pressupostos.html"><i class="fa fa-check"></i><b>3.5</b> Verificação de pressupostos</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="dca-pressupostos.html"><a href="dca-pressupostos.html#normalidade-dca"><i class="fa fa-check"></i><b>3.5.1</b> Normalidade: gráfico Q-Q e testes formais</a></li>
<li class="chapter" data-level="3.5.2" data-path="dca-pressupostos.html"><a href="dca-pressupostos.html#homocedasticidade-dca"><i class="fa fa-check"></i><b>3.5.2</b> Homogeneidade de variância</a></li>
<li class="chapter" data-level="3.5.3" data-path="dca-pressupostos.html"><a href="dca-pressupostos.html#transformacoes-dca"><i class="fa fa-check"></i><b>3.5.3</b> Transformações usuais</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="contrastes.html"><a href="contrastes.html"><i class="fa fa-check"></i><b>3.6</b> Contrastes e comparações múltiplas</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="contrastes.html"><a href="contrastes.html#definição-esperança-e-variância-de-um-contraste"><i class="fa fa-check"></i><b>3.6.1</b> Definição, esperança e variância de um contraste</a></li>
<li class="chapter" data-level="3.6.2" data-path="contrastes.html"><a href="contrastes.html#soma-de-quadrados-de-um-contraste-e-sua-distribuição"><i class="fa fa-check"></i><b>3.6.2</b> Soma de quadrados de um contraste e sua distribuição</a></li>
<li class="chapter" data-level="3.6.3" data-path="contrastes.html"><a href="contrastes.html#notação-matricial-contraste-como-forma-linear-e-quadrática"><i class="fa fa-check"></i><b>3.6.3</b> Notação matricial: contraste como forma linear e quadrática</a></li>
<li class="chapter" data-level="3.6.4" data-path="contrastes.html"><a href="contrastes.html#contrastes-ortogonais"><i class="fa fa-check"></i><b>3.6.4</b> Contrastes ortogonais</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html"><i class="fa fa-check"></i><b>3.7</b> Procedimentos de comparação múltipla</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#data-snooping"><i class="fa fa-check"></i><b>3.7.1</b> O perigo do “data snooping”</a></li>
<li class="chapter" data-level="3.7.2" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#método-de-scheffé"><i class="fa fa-check"></i><b>3.7.2</b> Método de Scheffé</a></li>
<li class="chapter" data-level="3.7.3" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#método-de-bonferroni"><i class="fa fa-check"></i><b>3.7.3</b> Método de Bonferroni</a></li>
<li class="chapter" data-level="3.7.4" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#tukey-hsd-honestly-significant-difference"><i class="fa fa-check"></i><b>3.7.4</b> Tukey HSD (<em>honestly significant difference</em>)</a></li>
<li class="chapter" data-level="3.7.5" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#comparação-com-um-grupo-controle-dunnett"><i class="fa fa-check"></i><b>3.7.5</b> Comparação com um grupo controle: Dunnett</a></li>
<li class="chapter" data-level="3.7.6" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#teste-de-amplitude-múltipla-de-duncan"><i class="fa fa-check"></i><b>3.7.6</b> Teste de amplitude múltipla de Duncan</a></li>
<li class="chapter" data-level="3.7.7" data-path="comparacoes-multiplas.html"><a href="comparacoes-multiplas.html#agrupamento-de-tratamentos-compact-letter-display"><i class="fa fa-check"></i><b>3.7.7</b> Agrupamento de tratamentos (<em>compact letter display</em>)</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="polinomios-ortogonais.html"><a href="polinomios-ortogonais.html"><i class="fa fa-check"></i><b>3.8</b> Polinômios ortogonais</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="polinomios-ortogonais.html"><a href="polinomios-ortogonais.html#esperança-variância-e-soma-de-quadrados"><i class="fa fa-check"></i><b>3.8.1</b> Esperança, variância e soma de quadrados</a></li>
<li class="chapter" data-level="3.8.2" data-path="polinomios-ortogonais.html"><a href="polinomios-ortogonais.html#a-matriz-de-polinômios-ortogonais-como-parte-de-mathbf-x"><i class="fa fa-check"></i><b>3.8.2</b> A matriz de polinômios ortogonais como parte de <span class="math inline">\(\mathbf X\)</span></a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="ancova.html"><a href="ancova.html"><i class="fa fa-check"></i><b>3.9</b> Análise de covariância (ANCOVA)</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="ancova.html"><a href="ancova.html#o-modelo"><i class="fa fa-check"></i><b>3.9.1</b> O modelo</a></li>
<li class="chapter" data-level="3.9.2" data-path="ancova.html"><a href="ancova.html#ancova-em-notação-matricial-mais-uma-coluna-em-mathbf-x"><i class="fa fa-check"></i><b>3.9.2</b> ANCOVA em notação matricial: mais uma coluna em <span class="math inline">\(\mathbf X\)</span></a></li>
<li class="chapter" data-level="3.9.3" data-path="ancova.html"><a href="ancova.html#a-tabela-de-anova-ajustada-pela-covariável"><i class="fa fa-check"></i><b>3.9.3</b> A tabela de ANOVA ajustada pela covariável</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="kruskal-wallis.html"><a href="kruskal-wallis.html"><i class="fa fa-check"></i><b>3.10</b> Teste de Kruskal-Wallis</a>
<ul>
<li class="chapter" data-level="3.10.1" data-path="kruskal-wallis.html"><a href="kruskal-wallis.html#o-que-muda-em-relação-à-anova"><i class="fa fa-check"></i><b>3.10.1</b> O que muda em relação à ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="resumo-do-capítulo-2.html"><a href="resumo-do-capítulo-2.html"><i class="fa fa-check"></i><b>3.11</b> Resumo do capítulo</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="blocos.html"><a href="blocos.html"><i class="fa fa-check"></i><b>4</b> Delineamentos com fontes de bloqueio</a>
<ul>
<li class="chapter" data-level="4.1" data-path="dbca.html"><a href="dbca.html"><i class="fa fa-check"></i><b>4.1</b> O delineamento em blocos completos aleatorizados (DBCA)</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="dbca.html"><a href="dbca.html#motivação-o-que-dá-errado-sem-controle-local-fatores-confundidos"><i class="fa fa-check"></i><b>4.1.1</b> Motivação: o que dá errado sem controle local — fatores confundidos</a></li>
<li class="chapter" data-level="4.1.2" data-path="dbca.html"><a href="dbca.html#o-modelo-1"><i class="fa fa-check"></i><b>4.1.2</b> O modelo</a></li>
<li class="chapter" data-level="4.1.3" data-path="dbca.html"><a href="dbca.html#notação-matricial-yxbetavarepsilon"><i class="fa fa-check"></i><b>4.1.3</b> Notação matricial: <span class="math inline">\(Y=X\beta+\varepsilon\)</span></a></li>
<li class="chapter" data-level="4.1.4" data-path="dbca.html"><a href="dbca.html#blocagem-como-aleatorização-restrita-a-camada-causal"><i class="fa fa-check"></i><b>4.1.4</b> Blocagem como aleatorização restrita: a camada causal</a></li>
<li class="chapter" data-level="4.1.5" data-path="dbca.html"><a href="dbca.html#tabela-de-anova"><i class="fa fa-check"></i><b>4.1.5</b> Tabela de ANOVA</a></li>
<li class="chapter" data-level="4.1.6" data-path="dbca.html"><a href="dbca.html#esperança-dos-quadrados-médios"><i class="fa fa-check"></i><b>4.1.6</b> Esperança dos quadrados médios</a></li>
<li class="chapter" data-level="4.1.7" data-path="dbca.html"><a href="dbca.html#visualizando-aditividade-o-gráfico-de-perfis"><i class="fa fa-check"></i><b>4.1.7</b> Visualizando aditividade: o gráfico de perfis</a></li>
<li class="chapter" data-level="4.1.8" data-path="dbca.html"><a href="dbca.html#tukey-nao-aditividade"><i class="fa fa-check"></i><b>4.1.8</b> O teste de não aditividade de Tukey</a></li>
<li class="chapter" data-level="4.1.9" data-path="dbca.html"><a href="dbca.html#diagrama-de-hasse-do-dbca-por-que-não-há-nó-de-interação"><i class="fa fa-check"></i><b>4.1.9</b> Diagrama de Hasse do DBCA: por que não há nó de interação</a></li>
<li class="chapter" data-level="4.1.10" data-path="dbca.html"><a href="dbca.html#dados-faltantes-estimação-do-valor-perdido"><i class="fa fa-check"></i><b>4.1.10</b> Dados faltantes: estimação do valor perdido</a></li>
<li class="chapter" data-level="4.1.11" data-path="dbca.html"><a href="dbca.html#eficiência-relativa-do-dbca-frente-ao-dca"><i class="fa fa-check"></i><b>4.1.11</b> Eficiência relativa do DBCA frente ao DCA</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="friedman.html"><a href="friedman.html"><i class="fa fa-check"></i><b>4.2</b> Teste de Friedman</a></li>
<li class="chapter" data-level="4.3" data-path="bib.html"><a href="bib.html"><i class="fa fa-check"></i><b>4.3</b> Blocos incompletos balanceados</a></li>
<li class="chapter" data-level="4.4" data-path="quadrado-latino.html"><a href="quadrado-latino.html"><i class="fa fa-check"></i><b>4.4</b> Delineamento em quadrado latino</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="quadrado-latino.html"><a href="quadrado-latino.html#motivação-dois-gradientes-ortogonais-e-por-que-um-bloqueio-simples-não-basta"><i class="fa fa-check"></i><b>4.4.1</b> Motivação: dois gradientes ortogonais, e por que um bloqueio simples não basta</a></li>
<li class="chapter" data-level="4.4.2" data-path="quadrado-latino.html"><a href="quadrado-latino.html#o-modelo-2"><i class="fa fa-check"></i><b>4.4.2</b> O modelo</a></li>
<li class="chapter" data-level="4.4.3" data-path="quadrado-latino.html"><a href="quadrado-latino.html#diagrama-de-hasse-do-quadrado-latino-três-fatores-cruzados-dois-a-dois"><i class="fa fa-check"></i><b>4.4.3</b> Diagrama de Hasse do quadrado latino: três fatores cruzados dois a dois</a></li>
<li class="chapter" data-level="4.4.4" data-path="quadrado-latino.html"><a href="quadrado-latino.html#aleatorização-de-um-quadrado-latino-yates1933latin"><i class="fa fa-check"></i><b>4.4.4</b> Aleatorização de um quadrado latino <span class="citation">(Yates, 1933)</span></a></li>
<li class="chapter" data-level="4.4.5" data-path="quadrado-latino.html"><a href="quadrado-latino.html#quadrados-latinos-replicados"><i class="fa fa-check"></i><b>4.4.5</b> Quadrados latinos replicados</a></li>
<li class="chapter" data-level="4.4.6" data-path="quadrado-latino.html"><a href="quadrado-latino.html#quantas-réplicas-uma-análise-de-poder"><i class="fa fa-check"></i><b>4.4.6</b> Quantas réplicas? Uma análise de poder</a></li>
<li class="chapter" data-level="4.4.7" data-path="quadrado-latino.html"><a href="quadrado-latino.html#eficiencia-ql"><i class="fa fa-check"></i><b>4.4.7</b> Eficiência relativa do quadrado latino frente ao DBCA e ao DCA</a></li>
<li class="chapter" data-level="4.4.8" data-path="quadrado-latino.html"><a href="quadrado-latino.html#ql-exemplo-ecommerce"><i class="fa fa-check"></i><b>4.4.8</b> Um segundo exemplo completo: cinco variantes de checkout em e-commerce</a></li>
<li class="chapter" data-level="4.4.9" data-path="quadrado-latino.html"><a href="quadrado-latino.html#youden"><i class="fa fa-check"></i><b>4.4.9</b> Quadrados de Youden: quando o quadrado latino não pode ser completo</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="quadrado-greco-latino.html"><a href="quadrado-greco-latino.html"><i class="fa fa-check"></i><b>4.5</b> Delineamento em quadrado greco-latino</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="quadrado-greco-latino.html"><a href="quadrado-greco-latino.html#mols"><i class="fa fa-check"></i><b>4.5.1</b> Quadrados latinos mutuamente ortogonais (MOLS): existência e o problema de Euler</a></li>
<li class="chapter" data-level="4.5.2" data-path="quadrado-greco-latino.html"><a href="quadrado-greco-latino.html#o-modelo-3"><i class="fa fa-check"></i><b>4.5.2</b> O modelo</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="split-plot.html"><a href="split-plot.html"><i class="fa fa-check"></i><b>4.6</b> Parcelas subdivididas (<em>split-plot</em>)</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="split-plot.html"><a href="split-plot.html#dois-erros-experimentais-não-um"><i class="fa fa-check"></i><b>4.6.1</b> Dois erros experimentais, não um</a></li>
<li class="chapter" data-level="4.6.2" data-path="split-plot.html"><a href="split-plot.html#por-que-o-teste-de-irrigação-usa-um-erro-diferente-do-teste-de-variedade"><i class="fa fa-check"></i><b>4.6.2</b> Por que o teste de irrigação usa um erro diferente do teste de variedade</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="resumo-do-capítulo-3.html"><a href="resumo-do-capítulo-3.html"><i class="fa fa-check"></i><b>4.7</b> Resumo do capítulo</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="fatoriais.html"><a href="fatoriais.html"><i class="fa fa-check"></i><b>5</b> Delineamentos com arranjos fatoriais</a>
<ul>
<li class="chapter" data-level="5.1" data-path="por-que-fatorial.html"><a href="por-que-fatorial.html"><i class="fa fa-check"></i><b>5.1</b> Por que cruzar fatores?</a></li>
<li class="chapter" data-level="5.2" data-path="modelo-axb.html"><a href="modelo-axb.html"><i class="fa fa-check"></i><b>5.2</b> O fatorial A×B: efeitos principais e interação</a></li>
<li class="chapter" data-level="5.3" data-path="anova-axb.html"><a href="anova-axb.html"><i class="fa fa-check"></i><b>5.3</b> Tabela de ANOVA para o fatorial A×B balanceado</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="anova-axb.html"><a href="anova-axb.html#tipos-sq"><i class="fa fa-check"></i><b>5.3.1</b> Quando as células não têm o mesmo tamanho: somas de quadrados Tipo I, II e III</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="matriz-axb.html"><a href="matriz-axb.html"><i class="fa fa-check"></i><b>5.4</b> Notação matricial do fatorial A×B</a></li>
<li class="chapter" data-level="5.5" data-path="axbxc.html"><a href="axbxc.html"><i class="fa fa-check"></i><b>5.5</b> Fatoriais A×B×C: interações duplas e tripla</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="axbxc.html"><a href="axbxc.html#cubo-2x2x2"><i class="fa fa-check"></i><b>5.5.1</b> O cubo do <span class="math inline">\(2^3\)</span>: visualizando efeitos principais, duplos e triplo</a></li>
<li class="chapter" data-level="5.5.2" data-path="axbxc.html"><a href="axbxc.html#hasse-axbxc"><i class="fa fa-check"></i><b>5.5.2</b> O diagrama de Hasse do fatorial 3×3×3</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="fatoriais-blocos.html"><a href="fatoriais-blocos.html"><i class="fa fa-check"></i><b>5.6</b> Fatoriais de dois fatores em blocos completos</a></li>
<li class="chapter" data-level="5.7" data-path="resumo-do-capítulo-4.html"><a href="resumo-do-capítulo-4.html"><i class="fa fa-check"></i><b>5.7</b> Resumo do capítulo</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="fatoriais-avancado.html"><a href="fatoriais-avancado.html"><i class="fa fa-check"></i><b>6</b> Fatoriais avançados: confusão, fracionamento e superfície de resposta</a>
<ul>
<li class="chapter" data-level="6.1" data-path="fatoriais-2k.html"><a href="fatoriais-2k.html"><i class="fa fa-check"></i><b>6.1</b> Fatoriais <span class="math inline">\(2^k\)</span>: notação e ANOVA</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="fatoriais-2k.html"><a href="fatoriais-2k.html#ortogonalidade-2k"><i class="fa fa-check"></i><b>6.1.1</b> Ortogonalidade da matriz de desenho</a></li>
<li class="chapter" data-level="6.1.2" data-path="fatoriais-2k.html"><a href="fatoriais-2k.html#algoritmo-yates"><i class="fa fa-check"></i><b>6.1.2</b> O algoritmo tabular de Yates</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="nao-replicado.html"><a href="nao-replicado.html"><i class="fa fa-check"></i><b>6.2</b> Análise de um fatorial <span class="math inline">\(2^k\)</span> não replicado</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="nao-replicado.html"><a href="nao-replicado.html#gráfico-de-probabilidade-normal-half-normal-plot"><i class="fa fa-check"></i><b>6.2.1</b> Gráfico de probabilidade normal (half-normal plot)</a></li>
<li class="chapter" data-level="6.2.2" data-path="nao-replicado.html"><a href="nao-replicado.html#gráfico-de-pareto-dos-efeitos"><i class="fa fa-check"></i><b>6.2.2</b> Gráfico de Pareto dos efeitos</a></li>
<li class="chapter" data-level="6.2.3" data-path="nao-replicado.html"><a href="nao-replicado.html#margem-de-erro-pelo-método-de-lenth"><i class="fa fa-check"></i><b>6.2.3</b> Margem de erro pelo método de Lenth</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="confusao-2k.html"><a href="confusao-2k.html"><i class="fa fa-check"></i><b>6.3</b> Confusão em <span class="math inline">\(2^k\)</span>: designação de tratamentos a blocos</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="confusao-2k.html"><a href="confusao-2k.html#esquema-de-designação-o-contraste-definidor"><i class="fa fa-check"></i><b>6.3.1</b> Esquema de designação: o contraste definidor</a></li>
<li class="chapter" data-level="6.3.2" data-path="confusao-2k.html"><a href="confusao-2k.html#confusao-projecao"><i class="fa fa-check"></i><b>6.3.2</b> Confusão como colinearidade em <span class="math inline">\(\mathbf{X}\)</span></a></li>
<li class="chapter" data-level="6.3.3" data-path="confusao-2k.html"><a href="confusao-2k.html#confusão-total-vs.-confusão-parcial"><i class="fa fa-check"></i><b>6.3.3</b> Confusão total vs. confusão parcial</a></li>
<li class="chapter" data-level="6.3.4" data-path="confusao-2k.html"><a href="confusao-2k.html#hasse-confusao"><i class="fa fa-check"></i><b>6.3.4</b> Visualizando a confusão com um diagrama de Hasse</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="fatoriais-3k.html"><a href="fatoriais-3k.html"><i class="fa fa-check"></i><b>6.4</b> Fatoriais <span class="math inline">\(3^k\)</span>: ideia geral e confusão com <span class="math inline">\(AB^2\)</span></a></li>
<li class="chapter" data-level="6.5" data-path="fracionados.html"><a href="fracionados.html"><i class="fa fa-check"></i><b>6.5</b> Fatoriais fracionados de dois níveis: a ideia geral</a></li>
<li class="chapter" data-level="6.6" data-path="rumo-superficie-resposta.html"><a href="rumo-superficie-resposta.html"><i class="fa fa-check"></i><b>6.6</b> Rumo à otimização: superfície de resposta</a></li>
<li class="chapter" data-level="6.7" data-path="resumo-do-capítulo-5.html"><a href="resumo-do-capítulo-5.html"><i class="fa fa-check"></i><b>6.7</b> Resumo do capítulo</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="superficie-resposta-cap.html"><a href="superficie-resposta-cap.html"><i class="fa fa-check"></i><b>7</b> Metodologia de superfície de resposta</a>
<ul>
<li class="chapter" data-level="7.1" data-path="superficie-resposta.html"><a href="superficie-resposta.html"><i class="fa fa-check"></i><b>7.1</b> Introdução à superfície de resposta</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="superficie-resposta.html"><a href="superficie-resposta.html#ponto-estacionario"><i class="fa fa-check"></i><b>7.1.1</b> Classificando o ponto estacionário: gradiente e Hessiana</a></li>
<li class="chapter" data-level="7.1.2" data-path="superficie-resposta.html"><a href="superficie-resposta.html#analise-canonica"><i class="fa fa-check"></i><b>7.1.2</b> Análise canônica: além de classificar, descrever a forma da superfície</a></li>
<li class="chapter" data-level="7.1.3" data-path="superficie-resposta.html"><a href="superficie-resposta.html#ridge-analysis"><i class="fa fa-check"></i><b>7.1.3</b> Análise de ridge: otimizando dentro de um raio fixo da região experimental</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="steepest-ascent.html"><a href="steepest-ascent.html"><i class="fa fa-check"></i><b>7.2</b> O caminho de máxima inclinação: de um fatorial inicial até a região do ótimo</a></li>
<li class="chapter" data-level="7.3" data-path="ccd.html"><a href="ccd.html"><i class="fa fa-check"></i><b>7.3</b> Delineamento composto central (CCD)</a></li>
<li class="chapter" data-level="7.4" data-path="desejabilidade.html"><a href="desejabilidade.html"><i class="fa fa-check"></i><b>7.4</b> Otimização de múltiplas respostas: funções de desejabilidade</a></li>
<li class="chapter" data-level="7.5" data-path="desenho-robusto.html"><a href="desenho-robusto.html"><i class="fa fa-check"></i><b>7.5</b> Desenho robusto: otimizando a média e a variância ao mesmo tempo</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="desenho-robusto.html"><a href="desenho-robusto.html#a-proposta-original-de-taguchi-e-por-que-ela-foi-revista"><i class="fa fa-check"></i><b>7.5.1</b> A proposta original de Taguchi, e por que ela foi revista</a></li>
<li class="chapter" data-level="7.5.2" data-path="desenho-robusto.html"><a href="desenho-robusto.html#a-alternativa-duas-superfícies-de-resposta-uma-única-maquinaria"><i class="fa fa-check"></i><b>7.5.2</b> A alternativa: duas superfícies de resposta, uma única maquinaria</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="resumo-do-capítulo-6.html"><a href="resumo-do-capítulo-6.html"><i class="fa fa-check"></i><b>7.6</b> Resumo do capítulo</a></li>
<li class="chapter" data-level="7.7" data-path="fim-do-programa-do-semestre.html"><a href="fim-do-programa-do-semestre.html"><i class="fa fa-check"></i><b>7.7</b> Fim do programa do semestre</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ab-bandits.html"><a href="ab-bandits.html"><i class="fa fa-check"></i><b>8</b> Experimentação em produtos digitais: testes A/B e bandits</a>
<ul>
<li class="chapter" data-level="8.1" data-path="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><i class="fa fa-check"></i><b>8.1</b> Parte I — Testes A/B como delineamento completamente aleatorizado</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#ab-e-dca"><i class="fa fa-check"></i><b>8.1.1</b> Um teste A/B é um delineamento completamente aleatorizado</a></li>
<li class="chapter" data-level="8.1.2" data-path="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#ab-dificuldades"><i class="fa fa-check"></i><b>8.1.2</b> Por que testes A/B em produtos digitais são estatisticamente difíceis</a></li>
<li class="chapter" data-level="8.1.3" data-path="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#ab-peeking"><i class="fa fa-check"></i><b>8.1.3</b> O problema do “peeking”</a></li>
<li class="chapter" data-level="8.1.4" data-path="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html"><a href="parte-i-testes-ab-como-delineamento-completamente-aleatorizado.html#ab-winners-curse"><i class="fa fa-check"></i><b>8.1.4</b> Vício do vencedor (<em>winner’s curse</em>)</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><i class="fa fa-check"></i><b>8.2</b> Parte II — Bandits: quando explorar e quando explotar</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html#bandits-motivacao"><i class="fa fa-check"></i><b>8.2.1</b> Exploração, explotação e a definição de arrependimento (<em>regret</em>)</a></li>
<li class="chapter" data-level="8.2.2" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html#bandits-ucb1"><i class="fa fa-check"></i><b>8.2.2</b> Upper Confidence Bound (UCB1): otimismo perante a incerteza</a></li>
<li class="chapter" data-level="8.2.3" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html#bandits-thompson"><i class="fa fa-check"></i><b>8.2.3</b> Thompson sampling: uma solução bayesiana</a></li>
<li class="chapter" data-level="8.2.4" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html#bandits-vs-ab"><i class="fa fa-check"></i><b>8.2.4</b> Horizonte fixo ou bandit?</a></li>
<li class="chapter" data-level="8.2.5" data-path="parte-ii-bandits-quando-explorar-e-quando-explotar.html"><a href="parte-ii-bandits-quando-explorar-e-quando-explotar.html#outros-topicos"><i class="fa fa-check"></i><b>8.2.5</b> Outros tópicos modernos</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="resumo-do-capítulo-7.html"><a href="resumo-do-capítulo-7.html"><i class="fa fa-check"></i><b>8.3</b> Resumo do capítulo</a></li>
<li class="chapter" data-level="8.4" data-path="encerrando-o-livro.html"><a href="encerrando-o-livro.html"><i class="fa fa-check"></i><b>8.4</b> Encerrando o livro</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://raydonal.github.io/matd48/" target="_blank">MATD48 — Página do curso</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Planejamento e Análise de Experimentos</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="superficie-resposta" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Introdução à superfície de resposta<a href="superficie-resposta.html#superficie-resposta" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Fatoriais <span class="math inline">\(2^k\)</span> e <span class="math inline">\(3^k\)</span> são desenhados para <strong>detectar e estimar efeitos</strong> — a pergunta é “quais
fatores importam, e há interação?”. A <strong>metodologia de superfície de resposta</strong> (MSR), formalizada
por Box e Wilson <span class="citation">(<a href="#ref-boxwilson1951">1951</a>)</span> como uma sequência de fatoriais e desenhos aumentados que
“escala” a superfície na direção de maior melhoria <span class="citation">(<a href="#ref-boxhunterhunter2005">Box et al., 2005</a>; <a href="#ref-montgomery2017design">Montgomery, 2017</a>)</span>, muda a
pergunta para “qual combinação de níveis <strong>otimiza</strong> a resposta?”, tipicamente ajustando um modelo
polinomial de segunda ordem que permite representar curvatura:</p>
<p><span class="math display">\[
y = \beta_0 + \sum_{i=1}^k \beta_i x_i + \sum_{i=1}^k \beta_{ii} x_i^2
+ \sum_{i&lt;j} \beta_{ij} x_i x_j + \varepsilon.
\]</span></p>
<p>Os termos quadráticos <span class="math inline">\(\beta_{ii}\)</span> são o que distingue este modelo do fatorial <span class="math inline">\(2^k\)</span> (que só
estima efeitos lineares e de interação): eles permitem capturar um máximo, mínimo ou ponto de
sela dentro da região experimental, em vez de apenas uma tendência linear.</p>
<div class="caixa-r"><strong>Uso do R</strong> — ajustando e visualizando a superfície de resposta
da energia de corte</div>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="superficie-resposta.html#cb259-1" tabindex="-1"></a>energia <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/energia.csv&quot;</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span>
<span id="cb259-2"><a href="superficie-resposta.html#cb259-2" tabindex="-1"></a></span>
<span id="cb259-3"><a href="superficie-resposta.html#cb259-3" tabindex="-1"></a>modelo_rsm <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb259-4"><a href="superficie-resposta.html#cb259-4" tabindex="-1"></a>  energia <span class="sc">~</span> Velocidad <span class="sc">+</span> angulo <span class="sc">+</span> <span class="fu">I</span>(Velocidad<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(angulo<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> Velocidad<span class="sc">:</span>angulo,</span>
<span id="cb259-5"><a href="superficie-resposta.html#cb259-5" tabindex="-1"></a>  <span class="at">data =</span> energia</span>
<span id="cb259-6"><a href="superficie-resposta.html#cb259-6" tabindex="-1"></a>)</span>
<span id="cb259-7"><a href="superficie-resposta.html#cb259-7" tabindex="-1"></a><span class="fu">summary</span>(modelo_rsm)<span class="sc">$</span>coefficients <span class="sc">%&gt;%</span></span>
<span id="cb259-8"><a href="superficie-resposta.html#cb259-8" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">4</span>) <span class="sc">%&gt;%</span></span>
<span id="cb259-9"><a href="superficie-resposta.html#cb259-9" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">&quot;Modelo de segunda ordem para energia de corte&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb259-10"><a href="superficie-resposta.html#cb259-10" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:energia-rsm">Tabela 7.1: </span>Modelo de segunda ordem para energia de corte
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
Std. Error
</th>
<th style="text-align:right;">
t value
</th>
<th style="text-align:right;">
Pr(&gt;|t|)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
0.0768
</td>
<td style="text-align:right;">
0.0479
</td>
<td style="text-align:right;">
1.6035
</td>
<td style="text-align:right;">
0.1193
</td>
</tr>
<tr>
<td style="text-align:left;">
Velocidad
</td>
<td style="text-align:right;">
0.0448
</td>
<td style="text-align:right;">
0.0260
</td>
<td style="text-align:right;">
1.7261
</td>
<td style="text-align:right;">
0.0946
</td>
</tr>
<tr>
<td style="text-align:left;">
angulo
</td>
<td style="text-align:right;">
-0.0041
</td>
<td style="text-align:right;">
0.0010
</td>
<td style="text-align:right;">
-3.9442
</td>
<td style="text-align:right;">
0.0004
</td>
</tr>
<tr>
<td style="text-align:left;">
I(Velocidad^2)
</td>
<td style="text-align:right;">
-0.0055
</td>
<td style="text-align:right;">
0.0037
</td>
<td style="text-align:right;">
-1.4864
</td>
<td style="text-align:right;">
0.1476
</td>
</tr>
<tr>
<td style="text-align:left;">
I(angulo^2)
</td>
<td style="text-align:right;">
0.0000
</td>
<td style="text-align:right;">
0.0000
</td>
<td style="text-align:right;">
3.6139
</td>
<td style="text-align:right;">
0.0011
</td>
</tr>
<tr>
<td style="text-align:left;">
Velocidad:angulo
</td>
<td style="text-align:right;">
-0.0002
</td>
<td style="text-align:right;">
0.0001
</td>
<td style="text-align:right;">
-1.0642
</td>
<td style="text-align:right;">
0.2957
</td>
</tr>
</tbody>
</table>
<p>O termo quadrático de <span class="math inline">\(\hat\beta_{\text{ângulo}^2}\)</span> é altamente significativo (<span class="math inline">\(p&lt;0{,}01\)</span>), e o
<span class="math inline">\(R^2\)</span> ajustado do modelo (0.773) confirma que a
superfície de segunda ordem descreve bem os dados — evidência de curvatura real, que um fatorial
<span class="math inline">\(2^k\)</span> nesses mesmos dois fatores nunca teria detectado, porque um desenho de apenas dois níveis
por fator é algebricamente cego a termos quadráticos.</p>
<p><img src="07-superficie-resposta_files/figure-html/energia-superficie-1.png" alt="" width="80%" style="display: block; margin: auto;" /></p>
<p><img src="07-superficie-resposta_files/figure-html/energia-contorno-1.png" alt="" width="80%" style="display: block; margin: auto;" /></p>
<p>A perspectiva 3D e o gráfico de contorno são duas janelas para o mesmo objeto matemático: a
primeira dá intuição sobre a forma geral da superfície (aqui, a energia sobe em algumas direções e
desce em outras — um sinal visual de que a curvatura não é simplesmente “uma tigela”); a segunda é
mais útil para leitura precisa, e para localizar exatamente onde a superfície para de subir ou
descer.</p>
<div id="ponto-estacionario" class="section level3 hasAnchor" number="7.1.1">
<h3><span class="header-section-number">7.1.1</span> Classificando o ponto estacionário: gradiente e Hessiana<a href="superficie-resposta.html#ponto-estacionario" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Derivando o modelo de segunda ordem em relação a cada regressor e igualando a zero, o <strong>ponto
estacionário</strong> <span class="math inline">\(\mathbf{x}_0\)</span> resolve o sistema linear</p>
<p><span class="math display">\[
\nabla y(\mathbf{x}_0) = \mathbf{b} + 2\mathbf{B}\mathbf{x}_0 = \mathbf{0}
\quad\Longrightarrow\quad
\mathbf{x}_0 = -\tfrac{1}{2}\mathbf{B}^{-1}\mathbf{b},
\]</span></p>
<p>em que <span class="math inline">\(\mathbf{b} = (\hat\beta_{\text{Velocidad}}, \hat\beta_{\text{ângulo}})&#39;\)</span> é o vetor de
coeficientes lineares e <span class="math inline">\(\mathbf{B}\)</span> é a matriz <strong>simétrica dos coeficientes de segunda ordem</strong>
(quadráticos na diagonal, de interação fora dela),</p>
<p><span class="math display">\[
\mathbf{B} = \begin{pmatrix} \hat\beta_{\text{Velocidad}^2} &amp; \hat\beta_{\text{Velocidad}\cdot
\text{ângulo}}/2 \\ \hat\beta_{\text{Velocidad}\cdot\text{ângulo}}/2 &amp; \hat\beta_{\text{ângulo}^2}
\end{pmatrix}.
\]</span></p>
<p>Note que <span class="math inline">\(\mathbf{B}\)</span> <strong>não</strong> é a Hessiana: do gradiente <span class="math inline">\(\nabla \hat y = \mathbf{b} + 2\mathbf{B}\mathbf{x}\)</span>
segue <span class="math inline">\(\nabla^2 \hat y = 2\mathbf{B}\)</span>. As duas matrizes têm os mesmos sinais de autovalores — por
isso a classificação do ponto estacionário é a mesma —, mas são os autovalores de <span class="math inline">\(\mathbf{B}\)</span>, e
não os da Hessiana, que aparecem como as <strong>taxas</strong> <span class="math inline">\(\lambda_i\)</span> da forma canônica adiante.</p>
<p>A <strong>natureza</strong> do ponto estacionário — máximo, mínimo ou sela — é decidida pelos autovalores de
<span class="math inline">\(\mathbf{B}\)</span>: ambos negativos indicam máximo, ambos positivos indicam mínimo, e <strong>sinais opostos
indicam ponto de sela</strong> (a superfície sobe em uma direção do espaço dos regressores e desce em
outra, exatamente o padrão sugerido pelo gráfico anterior).</p>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="superficie-resposta.html#cb260-1" tabindex="-1"></a>b_rsm <span class="ot">&lt;-</span> <span class="fu">coef</span>(modelo_rsm)</span>
<span id="cb260-2"><a href="superficie-resposta.html#cb260-2" tabindex="-1"></a>B_hess <span class="ot">&lt;-</span> <span class="fu">matrix</span>(</span>
<span id="cb260-3"><a href="superficie-resposta.html#cb260-3" tabindex="-1"></a>  <span class="fu">c</span>(<span class="dv">2</span> <span class="sc">*</span> b_rsm[<span class="st">&quot;I(Velocidad^2)&quot;</span>],     b_rsm[<span class="st">&quot;Velocidad:angulo&quot;</span>],</span>
<span id="cb260-4"><a href="superficie-resposta.html#cb260-4" tabindex="-1"></a>    b_rsm[<span class="st">&quot;Velocidad:angulo&quot;</span>],       <span class="dv">2</span> <span class="sc">*</span> b_rsm[<span class="st">&quot;I(angulo^2)&quot;</span>]),</span>
<span id="cb260-5"><a href="superficie-resposta.html#cb260-5" tabindex="-1"></a>  <span class="at">nrow =</span> <span class="dv">2</span></span>
<span id="cb260-6"><a href="superficie-resposta.html#cb260-6" tabindex="-1"></a>) <span class="sc">/</span> <span class="dv">2</span>   <span class="co"># B tem beta_ii na diagonal e beta_ij/2 fora: o 2*.../2 da diagonal devolve</span></span>
<span id="cb260-7"><a href="superficie-resposta.html#cb260-7" tabindex="-1"></a>    <span class="co"># o proprio beta_ii, e o termo de interacao fica dividido por 2</span></span>
<span id="cb260-8"><a href="superficie-resposta.html#cb260-8" tabindex="-1"></a></span>
<span id="cb260-9"><a href="superficie-resposta.html#cb260-9" tabindex="-1"></a>ponto_estacionario <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">0.5</span> <span class="sc">*</span> <span class="fu">solve</span>(B_hess) <span class="sc">%*%</span> <span class="fu">c</span>(b_rsm[<span class="st">&quot;Velocidad&quot;</span>], b_rsm[<span class="st">&quot;angulo&quot;</span>])</span>
<span id="cb260-10"><a href="superficie-resposta.html#cb260-10" tabindex="-1"></a><span class="fu">rownames</span>(ponto_estacionario) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Velocidade&quot;</span>, <span class="st">&quot;Ângulo&quot;</span>)</span>
<span id="cb260-11"><a href="superficie-resposta.html#cb260-11" tabindex="-1"></a>ponto_estacionario</span></code></pre></div>
<pre><code>##                 [,1]
## Velocidade  3.282264
## Ângulo     56.358108</code></pre>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb262-1"><a href="superficie-resposta.html#cb262-1" tabindex="-1"></a><span class="fu">eigen</span>(B_hess)<span class="sc">$</span>values   <span class="co"># sinais dos autovalores classificam o ponto</span></span></code></pre></div>
<pre><code>## [1]  4.158071e-05 -5.510702e-03</code></pre>
<p>Os dois autovalores têm <strong>sinais opostos</strong> — o ponto estacionário (<span class="math inline">\(V\approx3{,}28\)</span>,
ângulo<span class="math inline">\(\approx56{,}4°\)</span>) é uma <strong>sela</strong>, não um mínimo nem um máximo. Isso significa que, dentro da
região experimental, o menor valor de energia predito não está nesse ponto interior, mas em algum
ponto da <strong>fronteira</strong> da região — a varredura da grade confirma que o mínimo prático fica no
canto <span class="math inline">\(V=4{,}5\)</span>, ângulo<span class="math inline">\(\approx59{,}0°\)</span> (energia <span class="math inline">\(\approx0{,}027\)</span>). Esse é exatamente o tipo de
situação em que o gráfico de contorno é indispensável: sem ele, seria fácil confundir “a superfície
tem curvatura” com “a superfície tem um ótimo interior”, quando na verdade tem as duas coisas ao
mesmo tempo, mas não no mesmo ponto.</p>
</div>
<div id="analise-canonica" class="section level3 hasAnchor" number="7.1.2">
<h3><span class="header-section-number">7.1.2</span> Análise canônica: além de classificar, descrever a forma da superfície<a href="superficie-resposta.html#analise-canonica" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>A classificação do ponto estacionário acima (máximo, mínimo ou sela) usa só os <strong>sinais</strong> dos
autovalores de <span class="math inline">\(\mathbf{B}\)</span>. A <strong>análise canônica</strong> usa os autovalores <em>e</em> autovetores completos
para reescrever o modelo ajustado numa base em que a curvatura fica diagonal — revelando não só
<em>que tipo</em> de ponto estacionário existe, mas <em>quão rápido</em> a resposta muda em cada direção
principal da superfície. Partindo do modelo centrado no ponto estacionário <span class="math inline">\(\mathbf{x}_0\)</span>,
<span class="math inline">\(\hat y - \hat y_0 = (\mathbf{x}-\mathbf{x}_0)&#39;\mathbf{B}(\mathbf{x}-\mathbf{x}_0)\)</span>, e da
decomposição espectral <span class="math inline">\(\mathbf{B} = \mathbf{V}\boldsymbol\Lambda\mathbf{V}&#39;\)</span> (<span class="math inline">\(\mathbf{V}\)</span>
ortogonal, colunas = autovetores; <span class="math inline">\(\boldsymbol\Lambda=\text{diag}(\lambda_1,\lambda_2)\)</span>), a mudança
de variável <span class="math inline">\(\mathbf{w} = \mathbf{V}&#39;(\mathbf{x}-\mathbf{x}_0)\)</span> (uma rotação de eixos, não uma
translação arbitrária) elimina o termo cruzado:
<span class="math display">\[
\hat y = \hat y_0 + \lambda_1 w_1^2 + \lambda_2 w_2^2.
\]</span></p>
<div class="caixa-r"><strong>Uso do R</strong> — forma canônica da superfície da energia de corte</div>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="superficie-resposta.html#cb264-1" tabindex="-1"></a>decomp <span class="ot">&lt;-</span> <span class="fu">eigen</span>(B_hess)</span>
<span id="cb264-2"><a href="superficie-resposta.html#cb264-2" tabindex="-1"></a>V_rot <span class="ot">&lt;-</span> decomp<span class="sc">$</span>vectors</span>
<span id="cb264-3"><a href="superficie-resposta.html#cb264-3" tabindex="-1"></a>lambda_canonico <span class="ot">&lt;-</span> decomp<span class="sc">$</span>values</span>
<span id="cb264-4"><a href="superficie-resposta.html#cb264-4" tabindex="-1"></a></span>
<span id="cb264-5"><a href="superficie-resposta.html#cb264-5" tabindex="-1"></a>y0_chapeu <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelo_rsm, <span class="at">newdata =</span> <span class="fu">as.data.frame</span>(<span class="fu">t</span>(ponto_estacionario)) <span class="sc">%&gt;%</span></span>
<span id="cb264-6"><a href="superficie-resposta.html#cb264-6" tabindex="-1"></a>                        <span class="fu">setNames</span>(<span class="fu">c</span>(<span class="st">&quot;Velocidad&quot;</span>, <span class="st">&quot;angulo&quot;</span>)))</span>
<span id="cb264-7"><a href="superficie-resposta.html#cb264-7" tabindex="-1"></a></span>
<span id="cb264-8"><a href="superficie-resposta.html#cb264-8" tabindex="-1"></a><span class="fu">list</span>(<span class="at">y0 =</span> <span class="fu">unname</span>(y0_chapeu), <span class="at">lambda =</span> lambda_canonico, <span class="at">eixos_w =</span> V_rot)</span></code></pre></div>
<pre><code>## $y0
## [1] 0.03579915
## 
## $lambda
## [1]  4.158071e-05 -5.510702e-03
## 
## $eixos_w
##             [,1]        [,2]
## [1,]  0.01381628 -0.99990455
## [2,] -0.99990455 -0.01381628</code></pre>
<p>Os eixos canônicos <span class="math inline">\(w_1,w_2\)</span> são combinações lineares (rotacionadas) de velocidade e ângulo — não
correspondem a nenhum dos dois fatores originais isoladamente. O sinal oposto de
<span class="math inline">\(\lambda_1\approx\)</span> 4.16^{-5} e <span class="math inline">\(\lambda_2\approx\)</span>
-0.00551 é a mesma informação da Seção <a href="superficie-resposta.html#ponto-estacionario">7.1.1</a> (sela),
mas agora quantificada. A leitura dos sinais é direta: ao longo de <span class="math inline">\(w_i\)</span> a superfície <strong>sobe</strong> se
<span class="math inline">\(\lambda_i&gt;0\)</span> e <strong>desce</strong> se <span class="math inline">\(\lambda_i&lt;0\)</span>, a uma taxa dada por <span class="math inline">\(|\lambda_i|\)</span>. Aqui
<span class="math inline">\(\lambda_1&gt;0\)</span> e <span class="math inline">\(\lambda_2&lt;0\)</span>: a superfície sobe ao longo de <span class="math inline">\(w_1\)</span> e cai ao longo de <span class="math inline">\(w_2\)</span>.</p>
<p>O que a análise canônica acrescenta à simples classificação do ponto estacionário é a <strong>escala
relativa</strong> das duas curvaturas. Como
<span class="math inline">\(|\lambda_2|/|\lambda_1| \approx\)</span> 133,
a sela é fortemente <strong>alongada</strong>: ao longo de <span class="math inline">\(w_1\)</span> a superfície é quase plana, enquanto ao longo
de <span class="math inline">\(w_2\)</span> ela muda duas ordens de grandeza mais rápido. É <span class="math inline">\(w_2\)</span> — a direção de <strong>maior</strong>
<span class="math inline">\(|\lambda|\)</span> — que domina o comportamento local da resposta, e é nela que vale a pena mover o
processo. Uma crista quase plana como a de <span class="math inline">\(w_1\)</span> é, na prática, uma faixa de combinações
velocidade/ângulo praticamente equivalentes em energia: liberdade para otimizar <em>outro</em> critério
(custo, desgaste de ferramenta) sem perda mensurável nesta resposta <span class="citation">(<a href="#ref-myersmontgomery2016">Myers et al., 2016</a>)</span>.</p>
</div>
<div id="ridge-analysis" class="section level3 hasAnchor" number="7.1.3">
<h3><span class="header-section-number">7.1.3</span> Análise de ridge: otimizando dentro de um raio fixo da região experimental<a href="superficie-resposta.html#ridge-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Dois problemas distintos tornam o ponto estacionário um alvo insuficiente. O primeiro é ele cair
<strong>fora</strong> da região onde os dados foram coletados: aí segui-lo é extrapolar, e o modelo de segunda
ordem só é confiável <em>dentro</em> da nuvem de pontos observados. O segundo — o caso <strong>deste</strong> exemplo,
em que <span class="math inline">\(\mathbf{x}_0=(3.28\text{ m/s};\ 56.4^\circ)\)</span>
está confortavelmente dentro dos dados — é o ponto estacionário ser uma <strong>sela</strong>: ele não é nem
máximo nem mínimo, de modo que “ir até <span class="math inline">\(\mathbf{x}_0\)</span>” simplesmente não responde à pergunta de
otimização.</p>
<p>A <strong>análise de ridge</strong> <span class="citation">(<a href="#ref-myersmontgomery2016">Myers et al., 2016</a>)</span> contorna os dois casos com uma pergunta mais modesta:
para cada raio fixo <span class="math inline">\(\rho\)</span> (distância ao centro do desenho), qual é o melhor ponto sobre o círculo
(ou esfera, em mais dimensões) de raio <span class="math inline">\(\rho\)</span>? Isso é otimização restrita — otimizar
<span class="math inline">\(\hat y(\mathbf{x})\)</span> sujeito a <span class="math inline">\(\mathbf{x}&#39;\mathbf{x}=\rho^2\)</span> —, cuja condição de
estacionariedade de Lagrange é
<span class="math display">\[
\mathbf{b} + 2\mathbf{B}\mathbf{x} = 2\mu\,\mathbf{x}
\quad\Longleftrightarrow\quad
\mathbf{x}(\mu) = \tfrac{1}{2}(\mu\mathbf{I}-\mathbf{B})^{-1}\mathbf{b},
\]</span>
em que o multiplicador de Lagrange <span class="math inline">\(\mu\)</span> é ajustado até que <span class="math inline">\(\lVert\mathbf{x}(\mu)\rVert=\rho\)</span>.</p>
<p>A condição de estacionariedade sozinha <strong>não basta</strong>: para um mesmo <span class="math inline">\(\rho\)</span> ela admite várias
raízes <span class="math inline">\(\mu\)</span>, e cada uma corresponde a um ponto crítico diferente sobre o círculo. A escolha do
ramo é o que decide qual delas é a resposta procurada <span class="citation">(<a href="#ref-draper1963ridge">Draper, 1963</a>; <a href="#ref-myersmontgomery2016">Myers et al., 2016</a>)</span>:</p>
<p><span class="math display">\[
\mu &gt; \lambda_{\max}(\mathbf{B}) \;\Rightarrow\; \textbf{máximo restrito},
\qquad
\mu &lt; \lambda_{\min}(\mathbf{B}) \;\Rightarrow\; \textbf{mínimo restrito},
\]</span></p>
<p>e dentro de cada ramo <span class="math inline">\(\lVert\mathbf{x}(\mu)\rVert\)</span> é monótona em <span class="math inline">\(\mu\)</span>, o que torna o ajuste de
<span class="math inline">\(\mu\)</span> a um <span class="math inline">\(\rho\)</span> desejado um problema unidimensional bem posto. Fora desses dois ramos obtêm-se
pontos de sela da função restrita — críticos, mas nem máximo nem mínimo. Varrendo <span class="math inline">\(\rho\)</span> de <span class="math inline">\(0\)</span> até
a borda da região experimental, obtém-se o <strong>caminho de ridge</strong>: a sequência de pontos
ótimos-restritos, um para cada raio.</p>
<p>Velocidade e ângulo estão em escalas e unidades muito diferentes (<span class="math inline">\(2{,}3\)</span>–<span class="math inline">\(4{,}5\text{ m/s}\)</span> contra
<span class="math inline">\(20°\)</span>–<span class="math inline">\(60°\)</span>) — um “raio” euclidiano só faz sentido depois de <strong>codificar</strong> as duas variáveis para
uma escala comum, a mesma convenção de <span class="math inline">\(\pm1\)</span> já usada em todo o livro para fatoriais.</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="superficie-resposta.html#cb266-1" tabindex="-1"></a>c_vel <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">range</span>(energia<span class="sc">$</span>Velocidad)); s_vel <span class="ot">&lt;-</span> <span class="fu">diff</span>(<span class="fu">range</span>(energia<span class="sc">$</span>Velocidad)) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb266-2"><a href="superficie-resposta.html#cb266-2" tabindex="-1"></a>c_ang <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">range</span>(energia<span class="sc">$</span>angulo));    s_ang <span class="ot">&lt;-</span> <span class="fu">diff</span>(<span class="fu">range</span>(energia<span class="sc">$</span>angulo)) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb266-3"><a href="superficie-resposta.html#cb266-3" tabindex="-1"></a></span>
<span id="cb266-4"><a href="superficie-resposta.html#cb266-4" tabindex="-1"></a>energia_cod <span class="ot">&lt;-</span> energia <span class="sc">%&gt;%</span></span>
<span id="cb266-5"><a href="superficie-resposta.html#cb266-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">z1 =</span> (Velocidad <span class="sc">-</span> c_vel) <span class="sc">/</span> s_vel, <span class="at">z2 =</span> (angulo <span class="sc">-</span> c_ang) <span class="sc">/</span> s_ang)</span>
<span id="cb266-6"><a href="superficie-resposta.html#cb266-6" tabindex="-1"></a></span>
<span id="cb266-7"><a href="superficie-resposta.html#cb266-7" tabindex="-1"></a>modelo_rsm_cod <span class="ot">&lt;-</span> <span class="fu">lm</span>(energia <span class="sc">~</span> z1 <span class="sc">+</span> z2 <span class="sc">+</span> <span class="fu">I</span>(z1<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(z2<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> z1<span class="sc">:</span>z2, <span class="at">data =</span> energia_cod)</span>
<span id="cb266-8"><a href="superficie-resposta.html#cb266-8" tabindex="-1"></a>b_cod <span class="ot">&lt;-</span> <span class="fu">coef</span>(modelo_rsm_cod)[<span class="fu">c</span>(<span class="st">&quot;z1&quot;</span>, <span class="st">&quot;z2&quot;</span>)]</span>
<span id="cb266-9"><a href="superficie-resposta.html#cb266-9" tabindex="-1"></a>B_cod <span class="ot">&lt;-</span> <span class="fu">matrix</span>(</span>
<span id="cb266-10"><a href="superficie-resposta.html#cb266-10" tabindex="-1"></a>  <span class="fu">c</span>(<span class="dv">2</span> <span class="sc">*</span> <span class="fu">coef</span>(modelo_rsm_cod)[<span class="st">&quot;I(z1^2)&quot;</span>], <span class="fu">coef</span>(modelo_rsm_cod)[<span class="st">&quot;z1:z2&quot;</span>],</span>
<span id="cb266-11"><a href="superficie-resposta.html#cb266-11" tabindex="-1"></a>    <span class="fu">coef</span>(modelo_rsm_cod)[<span class="st">&quot;z1:z2&quot;</span>],       <span class="dv">2</span> <span class="sc">*</span> <span class="fu">coef</span>(modelo_rsm_cod)[<span class="st">&quot;I(z2^2)&quot;</span>]),</span>
<span id="cb266-12"><a href="superficie-resposta.html#cb266-12" tabindex="-1"></a>  <span class="at">nrow =</span> <span class="dv">2</span></span>
<span id="cb266-13"><a href="superficie-resposta.html#cb266-13" tabindex="-1"></a>) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb266-14"><a href="superficie-resposta.html#cb266-14" tabindex="-1"></a>y0_cod <span class="ot">&lt;-</span> <span class="fu">coef</span>(modelo_rsm_cod)[<span class="st">&quot;(Intercept)&quot;</span>]</span></code></pre></div>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="superficie-resposta.html#cb267-1" tabindex="-1"></a><span class="co"># Ate onde o raio pode ir sem extrapolar? A regiao experimental e a CAIXA</span></span>
<span id="cb267-2"><a href="superficie-resposta.html#cb267-2" tabindex="-1"></a><span class="co"># [-1,1]^2 (grade 3x3 em unidades codificadas). O circulo de raio rho so fica</span></span>
<span id="cb267-3"><a href="superficie-resposta.html#cb267-3" tabindex="-1"></a><span class="co"># inteiramente dentro da caixa ate rho = 1 (circulo INSCRITO); a partir dai ele</span></span>
<span id="cb267-4"><a href="superficie-resposta.html#cb267-4" tabindex="-1"></a><span class="co"># escapa pelos lados, tocando o desenho apenas nos quatro vertices, que estao a</span></span>
<span id="cb267-5"><a href="superficie-resposta.html#cb267-5" tabindex="-1"></a><span class="co"># raio sqrt(2). Paramos em 1: e o maior raio para o qual NENHUMA direcao theta</span></span>
<span id="cb267-6"><a href="superficie-resposta.html#cb267-6" tabindex="-1"></a><span class="co"># leva para fora dos dados.</span></span>
<span id="cb267-7"><a href="superficie-resposta.html#cb267-7" tabindex="-1"></a>raio_max <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb267-8"><a href="superficie-resposta.html#cb267-8" tabindex="-1"></a>raios <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.2</span>, raio_max, <span class="at">by =</span> <span class="fl">0.1</span>)</span>
<span id="cb267-9"><a href="superficie-resposta.html#cb267-9" tabindex="-1"></a></span>
<span id="cb267-10"><a href="superficie-resposta.html#cb267-10" tabindex="-1"></a>y_no_circulo <span class="ot">&lt;-</span> <span class="cf">function</span>(theta, rho) {</span>
<span id="cb267-11"><a href="superficie-resposta.html#cb267-11" tabindex="-1"></a>  z_theta <span class="ot">&lt;-</span> rho <span class="sc">*</span> <span class="fu">c</span>(<span class="fu">cos</span>(theta), <span class="fu">sin</span>(theta))</span>
<span id="cb267-12"><a href="superficie-resposta.html#cb267-12" tabindex="-1"></a>  <span class="fu">as.numeric</span>(y0_cod) <span class="sc">+</span> <span class="fu">as.numeric</span>(<span class="fu">t</span>(z_theta) <span class="sc">%*%</span> b_cod) <span class="sc">+</span> <span class="fu">as.numeric</span>(<span class="fu">t</span>(z_theta) <span class="sc">%*%</span> B_cod <span class="sc">%*%</span> z_theta)</span>
<span id="cb267-13"><a href="superficie-resposta.html#cb267-13" tabindex="-1"></a>}</span>
<span id="cb267-14"><a href="superficie-resposta.html#cb267-14" tabindex="-1"></a></span>
<span id="cb267-15"><a href="superficie-resposta.html#cb267-15" tabindex="-1"></a>caminho_ridge <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(raios, <span class="cf">function</span>(rho) {</span>
<span id="cb267-16"><a href="superficie-resposta.html#cb267-16" tabindex="-1"></a>  <span class="co"># y_no_circulo(theta) tem em geral DOIS mínimos e DOIS máximos em [0,2pi) (forma quadrática</span></span>
<span id="cb267-17"><a href="superficie-resposta.html#cb267-17" tabindex="-1"></a>  <span class="co"># indefinida sobre um círculo) -- optimize() assume unimodalidade e pode convergir para um</span></span>
<span id="cb267-18"><a href="superficie-resposta.html#cb267-18" tabindex="-1"></a>  <span class="co"># mínimo local errado; uma busca em grade fina, seguida de refinamento local, é mais confiável.</span></span>
<span id="cb267-19"><a href="superficie-resposta.html#cb267-19" tabindex="-1"></a>  grade_theta <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">2</span> <span class="sc">*</span> pi, <span class="at">length.out =</span> <span class="dv">721</span>)[<span class="sc">-</span><span class="dv">721</span>]</span>
<span id="cb267-20"><a href="superficie-resposta.html#cb267-20" tabindex="-1"></a>  th0 <span class="ot">&lt;-</span> grade_theta[<span class="fu">which.min</span>(<span class="fu">sapply</span>(grade_theta, y_no_circulo, <span class="at">rho =</span> rho))]</span>
<span id="cb267-21"><a href="superficie-resposta.html#cb267-21" tabindex="-1"></a>  opt <span class="ot">&lt;-</span> <span class="fu">optimize</span>(<span class="cf">function</span>(th) <span class="fu">y_no_circulo</span>(th, rho),</span>
<span id="cb267-22"><a href="superficie-resposta.html#cb267-22" tabindex="-1"></a>                   <span class="at">interval =</span> <span class="fu">c</span>(th0 <span class="sc">-</span> <span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">/</span> <span class="dv">360</span>, th0 <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">/</span> <span class="dv">360</span>), <span class="at">maximum =</span> <span class="cn">FALSE</span>)</span>
<span id="cb267-23"><a href="superficie-resposta.html#cb267-23" tabindex="-1"></a>  z_theta <span class="ot">&lt;-</span> rho <span class="sc">*</span> <span class="fu">c</span>(<span class="fu">cos</span>(opt<span class="sc">$</span>minimum), <span class="fu">sin</span>(opt<span class="sc">$</span>minimum))</span>
<span id="cb267-24"><a href="superficie-resposta.html#cb267-24" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">raio =</span> rho, <span class="at">Velocidad =</span> c_vel <span class="sc">+</span> s_vel <span class="sc">*</span> z_theta[<span class="dv">1</span>], <span class="at">angulo =</span> c_ang <span class="sc">+</span> s_ang <span class="sc">*</span> z_theta[<span class="dv">2</span>],</span>
<span id="cb267-25"><a href="superficie-resposta.html#cb267-25" tabindex="-1"></a>         <span class="at">y_predito =</span> opt<span class="sc">$</span>objective)</span>
<span id="cb267-26"><a href="superficie-resposta.html#cb267-26" tabindex="-1"></a>})</span>
<span id="cb267-27"><a href="superficie-resposta.html#cb267-27" tabindex="-1"></a></span>
<span id="cb267-28"><a href="superficie-resposta.html#cb267-28" tabindex="-1"></a><span class="co"># Fronteira da regiao experimental, para deixar visivel que o caminho fica dentro dela.</span></span>
<span id="cb267-29"><a href="superficie-resposta.html#cb267-29" tabindex="-1"></a>fronteira <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">theta =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">2</span> <span class="sc">*</span> pi, <span class="at">length.out =</span> <span class="dv">361</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb267-30"><a href="superficie-resposta.html#cb267-30" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Velocidade =</span> c_vel <span class="sc">+</span> s_vel <span class="sc">*</span> raio_max <span class="sc">*</span> <span class="fu">cos</span>(theta),</span>
<span id="cb267-31"><a href="superficie-resposta.html#cb267-31" tabindex="-1"></a>         <span class="st">`</span><span class="at">Ângulo</span><span class="st">`</span>   <span class="ot">=</span> c_ang <span class="sc">+</span> s_ang <span class="sc">*</span> raio_max <span class="sc">*</span> <span class="fu">sin</span>(theta))</span>
<span id="cb267-32"><a href="superficie-resposta.html#cb267-32" tabindex="-1"></a></span>
<span id="cb267-33"><a href="superficie-resposta.html#cb267-33" tabindex="-1"></a>caminho_ridge <span class="sc">%&gt;%</span></span>
<span id="cb267-34"><a href="superficie-resposta.html#cb267-34" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Velocidade =</span> Velocidad, <span class="st">`</span><span class="at">Ângulo</span><span class="st">`</span> <span class="ot">=</span> angulo) <span class="sc">%&gt;%</span></span>
<span id="cb267-35"><a href="superficie-resposta.html#cb267-35" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(Velocidade, <span class="st">`</span><span class="at">Ângulo</span><span class="st">`</span>)) <span class="sc">+</span></span>
<span id="cb267-36"><a href="superficie-resposta.html#cb267-36" tabindex="-1"></a>  <span class="fu">geom_path</span>(<span class="at">data =</span> fronteira, <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;grey55&quot;</span>) <span class="sc">+</span></span>
<span id="cb267-37"><a href="superficie-resposta.html#cb267-37" tabindex="-1"></a>  <span class="fu">geom_path</span>(<span class="fu">aes</span>(<span class="at">color =</span> y_predito), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb267-38"><a href="superficie-resposta.html#cb267-38" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> y_predito), <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb267-39"><a href="superficie-resposta.html#cb267-39" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>(<span class="at">name =</span> <span class="st">&quot;Energia</span><span class="sc">\n</span><span class="st">predita&quot;</span>) <span class="sc">+</span></span>
<span id="cb267-40"><a href="superficie-resposta.html#cb267-40" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Caminho de ridge: melhor ponto para cada</span><span class="sc">\n</span><span class="st">raio ao centro do desenho&quot;</span>,</span>
<span id="cb267-41"><a href="superficie-resposta.html#cb267-41" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="fu">paste0</span>(<span class="st">&quot;Tracejado: maior circulo inteiramente contido na regiao</span><span class="sc">\n</span><span class="st">experimental &quot;</span>,</span>
<span id="cb267-42"><a href="superficie-resposta.html#cb267-42" tabindex="-1"></a>                         <span class="st">&quot;(raio codificado &quot;</span>, <span class="fu">round</span>(raio_max, <span class="dv">2</span>), <span class="st">&quot;). O caminho nao o ultrapassa.&quot;</span>),</span>
<span id="cb267-43"><a href="superficie-resposta.html#cb267-43" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Velocidade de corte (m/s)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Ângulo de saída (graus)&quot;</span>) <span class="sc">+</span></span>
<span id="cb267-44"><a href="superficie-resposta.html#cb267-44" tabindex="-1"></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">12</span>)</span></code></pre></div>
<p><img src="07-superficie-resposta_files/figure-html/energia-ridge-1.png" alt="" width="80%" style="display: block; margin: auto;" /></p>
<p>O caminho de ridge sai do centro do desenho e se afasta em direção à combinação de
velocidade/ângulo que <strong>minimiza</strong> a energia predita a cada raio — aqui o objetivo é minimizar,
porque energia de corte é custo; o problema de máximo é o mesmo com o sinal trocado, e corresponde
ao ramo <span class="math inline">\(\mu &gt; \lambda_{\max}(\mathbf{B})\)</span> da condição de Lagrange. O raio só é bem definido
porque as duas variáveis foram trazidas à mesma escala.</p>
<p>Duas observações sobre o que a figura mostra. Primeira: o caminho <strong>para no círculo tracejado</strong>.
Vale explicitar por que o limite é <span class="math inline">\(\rho=1\)</span> e não <span class="math inline">\(\rho=\sqrt2\)</span>. A região experimental aqui é a
<em>caixa</em> <span class="math inline">\([-1,1]^2\)</span> — uma grade <span class="math inline">\(3\times3\)</span> —, enquanto o caminho de ridge percorre <em>círculos</em>. O
maior círculo inteiramente contido na caixa é o <strong>inscrito</strong>, de raio <span class="math inline">\(1\)</span>; o círculo de raio
<span class="math inline">\(\sqrt2\approx1{,}41\)</span> toca o desenho apenas nos quatro vértices e, em todas as demais direções,
já está fora dos dados. Como a direção ótima <span class="math inline">\(\theta\)</span> é escolhida pelo próprio procedimento, e não
por nós, só <span class="math inline">\(\rho\le1\)</span> garante que <em>nenhuma</em> direção escolhida seja extrapolação — que é a
disciplina que esta seção prega e precisa praticar. (Em desenhos cuja região é esférica por
construção, como o CCD rotacionável da próxima seção, essa distinção desaparece: lá a região <em>é</em> um
círculo, e o raio axial <span class="math inline">\(\alpha\)</span> é o limite natural.) Segunda: em vez de relatar apenas “o mínimo
fica na fronteira”, como fizemos antes, o caminho mostra <em>toda a trajetória</em> de pontos
ótimos-restritos, permitindo ao engenheiro escolher conscientemente um raio que equilibre ganho na
resposta e proximidade da região onde o modelo foi de fato estimado — quanto maior o raio, maior o
ganho predito e maior a incerteza sobre ele.</p>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" line-spacing="2">
<div id="ref-boxhunterhunter2005" class="csl-entry">
Box, G. E. P., Hunter, J. S., &amp; Hunter, W. G. (2005). <em>Statistics for experimenters: Design, innovation, and discovery</em> (2nd ed.). John Wiley &amp; Sons.
</div>
<div id="ref-boxwilson1951" class="csl-entry">
Box, G. E. P., &amp; Wilson, K. B. (1951). On the experimental attainment of optimum conditions. <em>Journal of the Royal Statistical Society, Series B</em>, <em>13</em>(1), 1–45.
</div>
<div id="ref-draper1963ridge" class="csl-entry">
Draper, N. R. (1963). Ridge analysis of response surfaces. <em>Technometrics</em>, <em>5</em>(4), 469–479. <a href="https://doi.org/10.1080/00401706.1963.10490122">https://doi.org/10.1080/00401706.1963.10490122</a>
</div>
<div id="ref-montgomery2017design" class="csl-entry">
Montgomery, D. C. (2017). <em>Design and analysis of experiments</em> (9th ed.). John Wiley &amp; Sons.
</div>
<div id="ref-myersmontgomery2016" class="csl-entry">
Myers, R. H., Montgomery, D. C., &amp; Anderson-Cook, C. M. (2016). <em>Response surface methodology: Process and product optimization using designed experiments</em> (4th ed.). John Wiley &amp; Sons.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="superficie-resposta-cap.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="steepest-ascent.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": false,
    "twitter": false,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": null,
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section",
    "scroll_highlight": true
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
